#!/usr/bin/env python3
"""K28 – 180 aktive Fähigkeiten (ABL_A001–ABL_A180), 12 je Typ.

Zeile: (Name, Kategorie P/S/St, Stärke, Genauigkeit ‰ (0 = kein Wurf), Ziel, Effekte, Tags)
Zeitkosten und Machtbudget werden berechnet (tools/abilities/abl.py), nie von Hand gesetzt.
Slot-Schema je Typ (K28 §5): 1–2 Einstieg · 3–5 Mittelklasse · 6 Schwer · 7–12 Status/Feld/Identität (Reihenfolge frei).
"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "abilities"))
from abl_write import write_kind

P, S, St = "Physical", "Special", "Status"
A = {
"Ember": [
    ("Funkenbiss", P, 40, 1000, "Single", "Status(Brand,100)", "Contact"),
    ("Glutfunke", S, 40, 1000, "Single", "Status(Brand,100)", ""),
    ("Aschewirbel", S, 60, 950, "Single", "Stage(Target,Precision,-1,300)", ""),
    ("Glutklaue", P, 70, 950, "Single", "Status(Brand,200)", "Contact"),
    ("Feuersaat", S, 55, 1000, "Row", "Terrain(Glutboden,3)", ""),
    ("Schmelzhieb", P, 90, 900, "Single", "Crit(1)", "Contact"),
    ("Feueratem", S, 95, 900, "Single", "Status(Brand,300)", ""),
    ("Esseneruption", S, 100, 850, "Enemies", "Exhaust()", ""),
    ("Hitzeflimmern", St, 0, 0, "Self", "Stage(Self,Evasion,+1);Stage(Self,Speed,+1)", ""),
    ("Schwelbrand", St, 0, 900, "Single", "Status(Brand,1000)", ""),
    ("Sonnenesse", St, 0, 0, "Field", "Weather(Heatwave,5)", ""),
    ("Lodernder Ansturm", P, 80, 1000, "Single", "Priority(1);Recoil(330)", "Contact"),
],
"Tide": [
    ("Spritzer", S, 40, 1000, "Single", "", ""),
    ("Strudelzug", S, 50, 1000, "Single", "Pull(Target)", ""),
    ("Brandungsschlag", P, 65, 1000, "Single", "Push(Target)", "Contact"),
    ("Gezeitenwelle", S, 60, 950, "Row", "Push(Target)", ""),
    ("Quellbad", St, 0, 0, "Ally", "Regen(Ally,8,3)", ""),
    ("Tiefenstrom", S, 90, 950, "Single", "", ""),
    ("Sturzflut", S, 110, 850, "Single", "Stage(Self,SpAttack,-1)", ""),
    ("Ebbe und Flut", St, 0, 0, "Field", "Terrain(Flutfeld,4)", ""),
    ("Nebelschleier", St, 0, 0, "Allies", "Stage(Allies,Evasion,+1)", ""),
    ("Wasserpeitsche", P, 35, 1000, "Single", "Multi(2,2);Stage(Target,Speed,-1,300)", "Contact"),
    ("Regenruf", St, 0, 0, "Field", "Weather(Rain,5)", ""),
    ("Schaumwall", St, 0, 0, "AllyRow", "Shield(AllyRow,15);Regen(AllyRow,5,2)", ""),
],
"Stone": [
    ("Kieselwurf", P, 40, 1000, "Single", "", ""),
    ("Felsrammen", P, 60, 950, "Single", "Status(Erschuettert,200)", "Contact"),
    ("Sandschleuder", S, 50, 950, "Single", "Stage(Target,Precision,-1,500)", ""),
    ("Geröllschauer", P, 25, 900, "Row", "Multi(2,4)", ""),
    ("Erdgrollen", S, 70, 1000, "Enemies", "", "Ground"),
    ("Monolithstoß", P, 110, 850, "Single", "Status(Erschuettert,300)", "Contact"),
    ("Steinhaut", St, 0, 0, "Self", "Stage(Self,Defense,+2)", ""),
    ("Felswall", St, 0, 0, "AllyRow", "Shield(AllyRow,20)", ""),
    ("Bergrücken", St, 0, 0, "Self", "Shield(Self,25);Taunt(1)", ""),
    ("Splitterfalle", St, 0, 0, "Field", "Trap(Splitter)", ""),
    ("Gerölllawine", P, 95, 900, "Row", "Stage(Target,Speed,-1,300)", ""),
    ("Grundfeste", St, 0, 0, "Self", "Stage(Self,Defense,+1);Stage(Self,SpDefense,+1);Heal(Self,15)", ""),
],
"Storm": [
    ("Böenhieb", P, 40, 1000, "Single", "Priority(1)", "Contact"),
    ("Klingenwind", S, 45, 1000, "Single", "Crit(1)", ""),
    ("Flatterschlag", P, 20, 950, "Single", "Multi(2,5)", "Contact"),
    ("Rückenwindschlag", P, 60, 1000, "Single", "Haste(Self,40)", "Contact"),
    ("Blitzbogen", S, 90, 900, "Single", "Status(Erschuettert,200)", ""),
    ("Donnerkeil", S, 115, 800, "Single", "WeatherBoost(Thunderstorm)", ""),
    ("Wirbelsturm", S, 60, 900, "Enemies", "Status(Schwebend,200)", ""),
    ("Böenchor", St, 0, 0, "Allies", "Haste(Allies,50)", ""),
    ("Sturmlauf", St, 0, 0, "Self", "Stage(Self,Speed,+2)", ""),
    ("Gewitterruf", St, 0, 0, "Field", "Weather(Thunderstorm,5)", ""),
    ("Kettenblitz", S, 30, 900, "Row", "Multi(2,3)", ""),
    ("Zyklonsprung", P, 75, 1000, "Single", "Haste(Self,30);MoveSelf()", "Contact"),
],
"Bloom": [
    ("Rankenhieb", P, 40, 1000, "Single", "", "Contact"),
    ("Pollenschuss", S, 40, 1000, "Single", "Stage(Target,Precision,-1,200)", ""),
    ("Saugwurzel", S, 60, 1000, "Single", "Drain(500)", ""),
    ("Dornenranke", P, 65, 950, "Single", "Bind(2)", "Contact"),
    ("Blütensturm", S, 85, 950, "Row", "", ""),
    ("Urwaldzorn", P, 110, 850, "Single", "Recoil(250)", "Contact"),
    ("Heiltau", St, 0, 0, "Ally", "Heal(Ally,40)", ""),
    ("Keimsegen", St, 0, 0, "Allies", "Regen(Allies,6,3)", ""),
    ("Wuchern", St, 0, 0, "Field", "Terrain(Ueberwuchs,5)", ""),
    ("Betäubungspollen", St, 0, 900, "Single", "Stage(Target,Speed,-2)", ""),
    ("Sonnentrunk", St, 0, 0, "Self", "Heal(Self,50);WeatherBoost(Clear)", ""),
    ("Wurzelgriff", St, 0, 0, "Self", "Regen(Self,8,4);Stage(Self,Defense,+1)", ""),
],
"Frost": [
    ("Raureifhauch", S, 40, 1000, "Single", "Delay(Target,20)", ""),
    ("Frostsplitter", P, 40, 1000, "Single", "Crit(1)", ""),
    ("Frostbiss", P, 60, 950, "Single", "Status(Verlangsamt,300)", "Contact"),
    ("Gletscherdruck", P, 85, 900, "Single", "Delay(Target,40)", "Contact"),
    ("Firnwind", S, 60, 950, "Row", "Stage(Target,Precision,-1,300)", ""),
    ("Eissturz", S, 100, 850, "Single", "Status(Starre,150)", ""),
    ("Kältestarre", St, 0, 850, "Single", "Status(Starre,1000)", ""),
    ("Weißer Atem", St, 0, 900, "Enemies", "Stage(Enemies,Precision,-1)", ""),
    ("Schneeruf", St, 0, 0, "Field", "Weather(Snow,5)", ""),
    ("Eisspiegel", St, 0, 0, "Field", "Terrain(Eisflaeche,4)", ""),
    ("Frostpanzer", St, 0, 0, "Self", "Shield(Self,20);Stage(Self,SpDefense,+1)", ""),
    ("Winterstille", S, 50, 900, "Enemies", "Delay(Enemies,30)", ""),
],
"Void": [
    ("Dunkelgriff", P, 40, 1000, "Single", "HarmonyDrain(5)", "Contact"),
    ("Leerstoß", S, 45, 1000, "Single", "", ""),
    ("Hohlklang", S, 60, 1000, "Single", "Dispel(Target)", ""),
    ("Seelenzehrer", S, 70, 950, "Single", "Drain(500)", ""),
    ("Schweigeschnitt", P, 80, 950, "Single", "Status(Entzug,300)", "Contact"),
    ("Abgrundwelle", S, 95, 900, "Row", "HarmonyDrain(10)", ""),
    ("Nullpunkt", S, 120, 800, "Single", "Stage(Self,SpAttack,-2)", ""),
    ("Verschlingen", St, 0, 900, "Single", "StealBuffs()", ""),
    ("Leerer Raum", St, 0, 0, "Field", "Terrain(Stillefeld,3)", ""),
    ("Entzugsfluch", St, 0, 900, "Single", "Status(Entzug,1000)", ""),
    ("Lichtschlucker", St, 0, 900, "Enemies", "Dispel(Enemies)", ""),
    ("Stille Klinge", P, 65, 1000, "Single", "IgnoreShield()", "Contact"),
],
"Light": [
    ("Lichtnadel", S, 40, 1000, "Single", "SureHit()", ""),
    ("Sonnenhieb", P, 45, 1000, "Single", "", "Contact"),
    ("Blendschein", S, 55, 1000, "Single", "Status(Geblendet,300)", ""),
    ("Prismenstrahl", S, 75, 950, "Single", "Reveal()", ""),
    ("Morgenrot", P, 80, 950, "Single", "WeatherBoost(Clear)", "Contact"),
    ("Zenitstoß", S, 120, 900, "Single", "Charge()", ""),
    ("Läuterung", St, 0, 0, "Allies", "Cleanse(Allies)", ""),
    ("Sonnenwehr", St, 0, 0, "AllyRow", "Shield(AllyRow,20)", ""),
    ("Strahlenkranz", S, 65, 950, "Enemies", "Status(Geblendet,200)", ""),
    ("Enthüllung", St, 0, 0, "Enemies", "Reveal();Stage(Enemies,Evasion,-1)", ""),
    ("Lichtung", St, 0, 0, "Field", "Terrain(Lichtfeld,4)", ""),
    ("Heilschein", St, 0, 0, "Ally", "Heal(Ally,35);Cleanse(Ally)", ""),
],
"Venom": [
    ("Nesselstich", P, 40, 1000, "Single", "Status(Vergiftet,300)", "Contact"),
    ("Säurespritzer", S, 40, 1000, "Single", "Stage(Target,SpDefense,-1,200)", ""),
    ("Nesselpeitsche", P, 55, 950, "Single", "Status(Vergiftet,1000)", "Contact"),
    ("Miasma", S, 50, 950, "Row", "Status(Vergiftet,500)", ""),
    ("Ätzklaue", P, 75, 950, "Single", "Stage(Target,Defense,-1,500)", "Contact"),
    ("Toxinwelle", S, 90, 900, "Single", "Status(Vergiftet,500,2)", ""),
    ("Fäulnisbiss", P, 100, 850, "Single", "TerrainBoost(Sumpf)", "Contact"),
    ("Giftnebel", St, 0, 0, "Field", "Terrain(Sumpf,4)", ""),
    ("Schleichendes Gift", St, 0, 900, "Single", "Status(Vergiftet,1000,3)", ""),
    ("Korrosion", St, 0, 900, "Single", "Stage(Target,Defense,-2)", ""),
    ("Giftkleid", St, 0, 0, "Self", "Shield(Self,15);Counter(Physical,300)", ""),
    ("Verwesung", S, 70, 1000, "Enemies", "Status(Welke,200)", ""),
],
"Metal": [
    ("Erzfaust", P, 40, 1000, "Single", "", "Contact"),
    ("Klingenwurf", P, 45, 1000, "Single", "Crit(1)", ""),
    ("Hammerschlag", P, 65, 950, "Single", "Stage(Target,Defense,-1,300)", "Contact"),
    ("Stahlwirbel", P, 30, 950, "Row", "Multi(2,2)", "Contact"),
    ("Magnetpuls", S, 60, 1000, "Single", "Status(Erschuettert,200)", ""),
    ("Schmiedeschlag", P, 100, 850, "Single", "Status(Gebrochen,200)", "Contact"),
    ("Spiegelstahl", St, 0, 0, "Self", "Counter(Special,1000)", ""),
    ("Konterhieb", St, 0, 0, "Self", "Counter(Physical,1500)", ""),
    ("Panzerplatten", St, 0, 0, "Self", "Stage(Self,Defense,+2)", ""),
    ("Rüstwerk", St, 0, 0, "AllyRow", "Stage(AllyRow,Defense,+1);Shield(AllyRow,10)", ""),
    ("Schrapnell", S, 70, 900, "Enemies", "", ""),
    ("Stahlsturm", P, 85, 950, "Single", "Shield(Self,15)", "Contact"),
],
"Spirit": [
    ("Geisterhauch", S, 40, 1000, "Single", "IgnoreFormation()", ""),
    ("Spukgriff", P, 40, 1000, "Single", "Stage(Target,Attack,-1,200)", "Contact"),
    ("Schreckensschrei", S, 60, 950, "Single", "Status(Furcht,300)", "Sound"),
    ("Seelenpfeil", S, 70, 1000, "Single", "IgnoreFormation();SureHit()", ""),
    ("Phantomklaue", P, 80, 950, "Single", "IgnoreFormation();Crit(1)", "Contact"),
    ("Totenklage", S, 95, 900, "Row", "Status(Furcht,200)", "Sound"),
    ("Doppelgänger", St, 0, 0, "Self", "Decoy()", ""),
    ("Albdruck", St, 0, 900, "Single", "Status(Furcht,1000)", ""),
    ("Ahnenwacht", St, 0, 0, "Allies", "Stage(Allies,SpDefense,+1)", ""),
    ("Seelenband", St, 0, 0, "Ally", "Heal(Ally,30);Stage(Ally,Evasion,+1)", ""),
    ("Verschwinden", St, 0, 0, "Self", "Stage(Self,Evasion,+2);MoveSelf()", ""),
    ("Geisterzug", S, 110, 850, "Single", "Charge();IgnoreFormation()", ""),
],
"Crystal": [
    ("Kristallsplitter", P, 40, 1000, "Single", "Crit(1)", ""),
    ("Glitzerstrahl", S, 40, 1000, "Single", "", ""),
    ("Facettenschnitt", P, 65, 950, "Single", "Status(Gebrochen,200)", "Contact"),
    ("Resonanzprisma", S, 70, 1000, "Single", "Charged()", ""),
    ("Kristallregen", S, 55, 900, "Row", "", ""),
    ("Diamantlanze", S, 120, 900, "Single", "Charge()", ""),
    ("Spiegelwand", St, 0, 0, "Self", "Reflect(Special)", ""),
    ("Prismenpanzer", St, 0, 0, "Self", "Reflect(Physical);Stage(Self,Defense,+1)", ""),
    ("Aufladen", St, 0, 0, "Self", "Charged();Stage(Self,SpAttack,+1)", ""),
    ("Drusenfeld", St, 0, 0, "Field", "Terrain(Kristallfeld,4)", ""),
    ("Prismenfächer", S, 65, 950, "Enemies", "", ""),
    ("Klirrschlag", P, 90, 900, "Single", "Status(Gebrochen,300)", "Contact"),
],
"Sound": [
    ("Summton", S, 40, 1000, "Single", "Harmony(5)", "Sound"),
    ("Klangschlag", P, 40, 1000, "Single", "Delay(Target,20)", "Contact|Sound"),
    ("Trommelschlag", P, 30, 1000, "Single", "Multi(2,2)", "Contact|Sound"),
    ("Dissonanz", S, 70, 950, "Single", "Status(Verstummt,200)", "Sound"),
    ("Taktbruch", S, 60, 1000, "Single", "Delay(Target,50)", "Sound"),
    ("Schallwand", St, 0, 0, "AllyRow", "Shield(AllyRow,15);Harmony(10)", "Sound"),
    ("Donnerhall", S, 100, 850, "Enemies", "Exhaust()", "Sound"),
    ("Kampflied", St, 0, 0, "Allies", "Stage(Allies,Attack,+1);Harmony(10)", "Sound"),
    ("Taktgeber", St, 0, 0, "Ally", "Haste(Ally,60)", "Sound"),
    ("Wiegenlied", St, 0, 850, "Single", "Delay(Target,80);Stage(Target,Speed,-1)", "Sound"),
    ("Resonanzkreis", St, 0, 0, "Field", "Terrain(Klangfeld,4)", "Sound"),
    ("Fortissimo", S, 90, 950, "Single", "Harmony(10)", "Sound"),
],
"Gravity": [
    ("Schwerefaust", P, 40, 1000, "Single", "", "Contact"),
    ("Massezug", S, 45, 1000, "Single", "Pull(Target)", ""),
    ("Gravistoß", S, 60, 1000, "Single", "Push(Target)", ""),
    ("Erdanziehung", P, 70, 950, "Single", "Bind(2)", "Contact"),
    ("Umkehrfeld", St, 0, 900, "Enemies", "SwapRows()", ""),
    ("Meteorsturz", P, 110, 850, "Single", "Charge()", ""),
    ("Schwerkraftfeld", St, 0, 0, "Field", "Terrain(Schwerefeld,4)", ""),
    ("Bahnbrecher", S, 85, 950, "Row", "Push(Target)", ""),
    ("Schwebe", St, 0, 0, "Self", "Stage(Self,Evasion,+1);MoveSelf()", ""),
    ("Gewichtslast", St, 0, 950, "Single", "Stage(Target,Speed,-2)", ""),
    ("Singularität", S, 95, 900, "Single", "Pull(Target);Stage(Target,Evasion,-1)", ""),
    ("Implosion", S, 70, 950, "Enemies", "Bind(1)", ""),
],
"Arcane": [
    ("Runenpfeil", S, 40, 1000, "Single", "SureHit()", ""),
    ("Glyphenschlag", P, 45, 1000, "Single", "", "Contact"),
    ("Bannzeichen", S, 60, 950, "Single", "Status(Verflucht,200)", ""),
    ("Spiegelformel", St, 0, 1000, "Single", "Copy()", ""),
    ("Wandlungsglyphe", St, 0, 1000, "Single", "TypeChange(Target,Arcane,2)", ""),
    ("Umkehrrune", St, 0, 0, "Field", "InvertChart(1)", ""),
    ("Siegelbruch", P, 80, 950, "Single", "Dispel(Target)", "Contact"),
    ("Formelraub", St, 0, 900, "Single", "StealBuffs()", ""),
    ("Arkansturm", S, 100, 850, "Row", "", ""),
    ("Glyphenkreis", St, 0, 0, "Field", "Terrain(Glyphenfeld,3)", ""),
    ("Mantra", St, 0, 0, "Self", "Stage(Self,SpAttack,+1);Stage(Self,SpDefense,+1)", ""),
    ("Fluchwort", St, 0, 900, "Single", "Status(Verflucht,1000)", ""),
],
}

if __name__ == "__main__":
    rows = []
    for t, lst in A.items():
        for (name, cat, pw, acc, tgt, eff, tags) in lst:
            rows.append(dict(Type=t, DisplayName=name, Category=cat, Power=pw, Accuracy=acc, Target=tgt,
                             Effects=eff, Tags=tags))
    write_kind("Active", rows)
