#!/usr/bin/env python3
"""K20 – Kreaturenkatalog 1: Verdanthain (R01), Kodex #001–#032."""
from catalog_lib import Catalog

c = Catalog(start_kodex=1, start_line=1, region="R01")
UH = ["R01_Z06"]  # Uralthain

# ---------------------------------------------------------------- L001 Starter Blüte
c.line_of("Three", "Pteridolis", [
    dict(name="Fernlit", epithet="cantans", cat="Farnkitz-Echo", arch="A01", size="S", h=0.45, w=6.2, types=("Bloom",),
         habitat="Farnunterholz an Waldrändern und Bachläufen", zones=UH, rarity="VeryRare",
         conds=["Story.AfterActOne", "Weather.Rain", "TimeOfDay.Dawn"], act="Crepuscular",
         traits=["Shy", "Singer", "FamilyGroup"], niches=["Combat", "Field"], role="Support", growth="Steady",
         polish="SpDefense:1", stats=(48, 42, 50, 55, 58, 47), acc=(100, 105), evo="Level>=16", bond=45,
         lure="ITM_FOOD_LINDHONEY", sig="Glockenblüte: heilt Verbündeten in der Reihe und läutet (Harmonie+)",
         mark="Spiralmuster aus Lindgold auf Stirn und Flanken; 52 BPM in Ruhe",
         lore=["Ein Oberton Sylv'anors, entstanden dort, wo Farn und Glockenblume im Morgenwind gemeinsam schwingen.",
               "Lebt in kleinen Familien im Farnunterholz; trinkt Tau und Nektar, läutet bei Freude leise mit den Halsknospen und erstarrt bei Gefahr zwischen den Wedeln.",
               "Im Lauscherglauben läutet ein Fernlit über jeder Wiege, deren Kind einmal Wärter wird.",
               "Gilt in Verdanthain als Glücksbringer; Imker sehen es gern, weil es Blüten bestäubt. Es zu erschrecken, bringt nach altem Glauben ein Jahr Stille.",
               "Die Halsknospen öffnen sich vollständig, wenn das Echo dem Wärter tief vertraut. Ab Level 16 wechselt es die Tonart; ab Level 34 folgt die zweite Wandlung."]),
    dict(name="Fernwyn", epithet="alata", cat="Blattschwingen-Echo", arch="A01", size="M", h=0.95, types=("Bloom", "Storm"),
         habitat="Lichtungen und Waldränder mit Aufwind", zones=[], rarity="Rare", conds=["Spawn.None"], act="Crepuscular",
         traits=["Singer", "Curious", "Playful"], niches=["Combat", "Field"], role="Support", growth="Steady",
         polish="SpDefense:2", stats=("Support", 430), evo="Level>=34", bond=40, lure="ITM_FOOD_LINDHONEY",
         sig="Wedelwind: Heilung über Zeit für die ganze Reihe, Fernwyn verschiebt sich auf der Zeitleiste nach vorn",
         mark="Lindgold-Spiralen auf den Blattschwingen, pulsieren beim Gleiten schneller",
         lore=["Der zweite Ton der Farnlinie: Wenn Wind durch die Wedel fährt, werden sie zu Schwingen.",
               "Gleitet in kurzen Sprüngen von Ast zu Ast und verteilt dabei Samen; spielt gern mit fallenden Blättern.",
               "Man sagt, ein Fernwyn weise Verirrten den Weg aus dem Lindwald, wenn sie leise genug sind.",
               "Förster pflanzen dort, wo Fernwyns rasten – an diesen Stellen wächst der Wald am schnellsten nach.",
               "Die Schwingen tragen es nicht wirklich, sie verlängern nur Sprünge. Ab Level 34 öffnet sich die Endform."]),
    dict(name="Verdrath", epithet="regalis", cat="Haingeweih-Echo", arch="A03", size="L", h=2.2, types=("Bloom", "Sound"),
         habitat="Alte Haine und Steinkreise im Uralthain", zones=[], rarity="Rare", conds=["Spawn.None"], act="Crepuscular",
         traits=["Singer", "Guardian", "Solitary"], niches=["Combat", "Mount"], role="Support", mount="Ground", growth="Steady",
         polish="SpDefense:3", stats=("Support", 530, (0, 0.05, 0, 0.05, 0, -0.05)), bond=35, lure="ITM_FOOD_LINDHONEY",
         sig="Hainchor: Crescendo – heilt alle Verbündeten und lässt für 3 Züge Überwuchs wachsen",
         mark="Geweih aus Ästen mit Glockenblüten; Klangmal als goldenes Rankenmuster, 44 BPM",
         lore=["Die volle Tonart der Farnlinie, ein kleiner Widerhall Sylv'anors selbst.",
               "Wandert langsam durch alte Haine; wo sein Geweih läutet, schließen sich Wunden in der Rinde der Bäume.",
               "Der Lauscherglaube hält Verdrath für den Boten der schlafenden Stimme des Waldes.",
               "Wer auf einem Verdrath reitet, gilt in Eichenhall als Freund des Waldes; der Bundesrat ehrt solche Wärter.",
               "Verdrath trägt Reiter, nachdem es ihnen vertraut. Sein Klangmal synchronisiert sich mit dem des Wärters."])],
)

# ---------------------------------------------------------------- L002 Starter Stein
c.line_of("Three", "Calculocanis", [
    dict(name="Brokk", epithet="minimus", cat="Kieselwelpen-Echo", arch="A01", size="S", h=0.4, w=9.5, types=("Stone",),
         habitat="Felsige Bachufer und Geröllhalden", zones=UH, rarity="VeryRare",
         conds=["Story.AfterActOne", "Weather.Clear", "TimeOfDay.Day"], act="Cathemeral",
         traits=["Curious", "Burrower", "Playful"], niches=["Combat", "Field"], role="Tank", growth="Steady",
         polish="Defense:1", stats=(52, 50, 62, 36, 54, 56), evo="Level>=16", bond=45, lure="ITM_FOOD_ORECRUMBS",
         sig="Kieselwall: errichtet einen Schild vor der eigenen Reihe",
         mark="Graue Ringe auf dem Rücken wie Jahresringe eines Steins; 60 BPM",
         lore=["Ein Oberton von Stein und Geduld, geformt dort, wo die Linn Kiesel rund schleift.",
               "Gräbt Mulden in Uferkies und sammelt glatte Steine; rollt sich bei Gefahr zu einer Kugel zusammen.",
               "Kinder werfen einem Brokk einen Kiesel zu – bringt es ihn zurück, steht eine gute Ernte bevor.",
               "Bauern lassen Brokks Felder entsteinen; als Starter gilt es als verlässlichster Gefährte für neue Wärter.",
               "Der Panzer wächst mit jeder Schicht, die Brokk aufnimmt. Ab Level 16 und Level 34 entwickelt es sich."]),
    dict(name="Brokkar", epithet="robustus", cat="Felsrücken-Echo", arch="A02", size="M", h=1.1, types=("Stone",),
         habitat="Steinbrüche und Felshänge", zones=[], rarity="Rare", conds=["Spawn.None"], act="Cathemeral",
         traits=["Guardian", "Burrower", "Territorial"], niches=["Combat", "Field"], role="Tank", growth="Steady",
         polish="Defense:2", stats=("Tank", 435), evo="Level>=34", bond=40, lure="ITM_FOOD_ORECRUMBS",
         sig="Felsprall: Angriff, der den Gegner eine Reihe zurückstößt (Rückstoß)",
         mark="Ringe ziehen sich über die Schulterplatten; bei Wut beschleunigt auf 90 BPM",
         lore=["Wenn Brokk genug Kiesel getragen hat, wachsen die Steine zu einem Rückenpanzer zusammen.",
               "Verteidigt seinen Ruheplatz mit Schulterstößen; frisst Erzkrümel und Flechten.",
               "In Kharsgrat heißt es, ein Brokkar habe einst einen Bergrutsch mit dem eigenen Rücken aufgehalten.",
               "Steinmetze lieben Brokkar – es spaltet Blöcke entlang natürlicher Linien.",
               "Die Rückenplatten werden mit jedem Kampf dichter. Ab Level 34 vollendet sich die Linie."]),
    dict(name="Torgrath", epithet="montanus", cat="Bergbollwerk-Echo", arch="A02", size="XL", h=3.2, types=("Stone", "Gravity"),
         habitat="Felsplateaus und Bergflanken", zones=[], rarity="Rare", conds=["Spawn.None"], act="Cathemeral",
         traits=["Guardian", "Solitary", "Territorial"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Steady", polish="Defense:3", stats=("Tank", 530, (0, 0.1, 0, 0, 0, 0)), bond=35, lure="ITM_FOOD_ORECRUMBS",
         sig="Bergherz: Crescendo – zieht alle Gegner in die Vorderreihe und senkt ihre Geschwindigkeit",
         mark="Schwebende Steinsplitter kreisen um das Klangmal am Nacken; 40 BPM",
         lore=["Die Endform der Kieselwelpen trägt einen Hauch Orh'gruuns in sich: Kleine Steine schweben um sie.",
               "Bewegt sich bedächtig; wo es lagert, sinkt der Boden leicht ein.",
               "Bergvölker erzählen, Torgrath seien die Wächter der Pässe, bevor es Menschen gab.",
               "Reiter auf Torgrath gelten als unaufhaltsam; Lawinen weichen ihnen der Sage nach aus.",
               "Das Klangmal erzeugt ein schwaches Schwerefeld – deshalb schweben Splitter. Trägt Reiter."])],
)

# ---------------------------------------------------------------- L003 Starter Sturm
c.line_of("Three", "Zephyrops", [
    dict(name="Wisplet", epithet="sibilans", cat="Pfeifwind-Echo", arch="A05", size="XS", h=0.25, types=("Storm",),
         habitat="Baumwipfel und offene Kronendächer", zones=UH, rarity="VeryRare",
         conds=["Story.AfterActOne", "Weather.Thunderstorm"], act="Diurnal",
         traits=["Curious", "Flier", "Singer"], niches=["Combat", "Field"], role="Speed", growth="Steady",
         polish="Speed:1", stats=(42, 50, 40, 52, 44, 77), evo="Level>=16", bond=50, lure="ITM_LURE_WHISTLE",
         sig="Böenpfiff: schneller Angriff, eigene nächste Aktion kostet weniger Zeit",
         mark="Weiße Wirbel auf den Flügeln; schnellster Puls aller Starter, 96 BPM",
         lore=["Ein Oberton aus Wind in den Kronen – entstanden, wo der Wald pfeift.",
               "Jagt Insekten im Flug und pfeift in kurzen Tonfolgen; badet in Pfützen nach Gewittern.",
               "Wer ein Wisplet im Gewitter singen hört, dem dreht sich bald der Wind des Glücks.",
               "Seeleute aus Saltrand bringen Wisplets als Wetterboten mit: Sie werden vor Stürmen unruhig.",
               "Die Wirbel auf den Flügeln drehen sich vor Wetterwechseln. Entwickelt sich ab Level 16 und Level 34."]),
    dict(name="Galewix", epithet="velox", cat="Böenflügel-Echo", arch="A05", size="S", h=0.7, types=("Storm",),
         habitat="Lichtungen, Felskanten mit Aufwind", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Flier", "Hunter", "Playful"], niches=["Combat", "Field"], role="Speed", growth="Steady",
         polish="Speed:2", stats=("Speed", 430), evo="Level>=34", bond=45, lure="ITM_LURE_WHISTLE",
         sig="Doppelböe: trifft zweimal, Treffer 2 nur bei Aufwind/Gewitter mit voller Kraft",
         mark="Wirbelmuster wandert vom Kopf zur Schwanzspitze; 104 BPM im Flug",
         lore=["Der zweite Ton der Pfeifwindlinie: der Ruf wird zur Böe.",
               "Stürzt sich aus großer Höhe auf Beute und reitet Aufwinde stundenlang.",
               "In Eichenhall sagt man: Wo ein Galewix kreist, zieht bald ein Gewitter auf.",
               "Galewix-Flugstaffeln liefern Botschaften der Wildwacht schneller als jeder Reiter.",
               "Seine Flügelspitzen erzeugen kleine Wirbel – im Kampf zweimal treffend. Ab Level 34 folgt die Endform."]),
    dict(name="Zephyrion", epithet="imperator", cat="Himmelsfalken-Echo", arch="A05", size="L", h=1.9, types=("Storm", "Light"),
         habitat="Höchste Baumriesen, Gipfel und Wolkenränder", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Flier", "Hunter", "Solitary"], niches=["Combat", "Mount"], role="Speed", mount="Fly", growth="Steady",
         polish="Speed:3", stats=("Speed", 530), bond=35, lure="ITM_LURE_WHISTLE",
         sig="Himmelssturz: Crescendo – trifft alle Gegner und verschiebt sie auf der Zeitleiste nach hinten",
         mark="Klangmal wie ein Kranz aus Windlinien um die Augen, leuchtet im Sonnenlicht; 88 BPM",
         lore=["Die volle Tonart des Pfeifwinds, verwandt mit den Winden, die einst Nimbara umspielten.",
               "Kreist hoch über dem Wald, sieht Bewegungen auf zwei Kilometer und landet nur, um zu ruhen.",
               "Man sagt, Zephyrion sei als einziges Echo den Himmelinseln je nahe gekommen.",
               "Ein Zephyrion als Flugreittier ist der Traum jedes jungen Wärters in Verdanthain.",
               "Trägt Reiter durch die Luft, sobald die Wildwacht das Flugreiten freigegeben hat."])],
)

# ---------------------------------------------------------------- L004 Klang-Primat + Zweig (Geist)
c.line_of("Three", "Tintinnapes", [
    dict(name="Chimkin", epithet="furax", cat="Glöckchenaffen-Echo", arch="A18", size="S", h=0.5, types=("Sound",),
         habitat="Obstwiesen, Dorfränder, Lindwald", zones=["R01_Z01", "R01_Z02", "R01_Z03"], rarity="Common",
         act="Diurnal", traits=["Curious", "Playful", "Hoarder"], niches=["Combat", "Field"], role="Control",
         growth="Wave", polish="Speed:1", stats=("Control", 310), evo="Level>=18", bond=60, lure="ITM_LURE_BELLCHIME",
         sig="Bimmelstreich: verzögert das Ziel auf der Zeitleiste (Klang-Kernmechanik)",
         mark="Drei kleine Glockenringe am Schwanz leuchten im Takt; 76 BPM",
         lore=["Ein Oberton aus Lachen und Glöckchenklang, häufig an Orten, wo Menschen musizieren.",
               "Stiehlt Brot, Knöpfe und Glöckchen, versteckt sie in Baumhöhlen und klingelt beim Davonlaufen.",
               "Ein Chimkin im Dachgebälk gilt als Zeichen, dass im Haus bald gefeiert wird.",
               "Der Brotdieb von Lindwiesen ist fast immer ein Chimkin – und meist verzeiht man ihm.",
               "Lernt durch Nachahmung. Ab Level 18 und Level 32 (zur Abenddämmerung) entwickelt es sich; bei Nebel in der Nacht kann ein anderer Ton entstehen."]),
    dict(name="Chimbal", epithet="tympanicus", cat="Zimbelaffen-Echo", arch="A18", size="M", h=1.0, types=("Sound",),
         habitat="Waldränder und Farnschlucht", zones=["R01_Z05", "R01_Z06"], rarity="Uncommon", act="Diurnal",
         traits=["Playful", "Climber", "Singer"], niches=["Combat"], role="Control", growth="Wave", polish="Speed:2",
         stats=("Control", 425), evo="Level>=32 & TimeOfDay=Dusk", bond=50, lure="ITM_LURE_BELLCHIME",
         sig="Zimbelschlag: verzögert alle Gegner einer Reihe leicht",
         mark="Handflächen tragen runde Klangmale, die beim Klatschen aufblitzen",
         lore=["Wenn Chimkins Glöckchen zu Zimbeln werden, wird aus dem Streich ein Rhythmus.",
               "Gruppen schlagen abends gemeinsam den Takt auf hohlen Ästen; der Wald antwortet mit Echo.",
               "Wanderer, die im Takt eines Chimbal-Konzerts mitklatschen, sollen nie den Weg verlieren.",
               "Musiker aus Eichenhall lauschen Chimbals, um neue Rhythmen zu lernen.",
               "Zur Abenddämmerung ab Level 32 wird es zum Dirigenten. Bei Nebel in der Nacht entsteht stattdessen eine geisterhafte Form."]),
    dict(name="Cantaroth", epithet="maestro", cat="Dirigentenaffen-Echo", arch="A18", size="L", h=1.8, types=("Sound", "Bloom"),
         habitat="Uralthain, Lichtungen mit Steinkreisen", zones=["R01_Z06"], rarity="Rare", conds=["TimeOfDay.Dusk"],
         act="Crepuscular", traits=["Singer", "Guardian", "Climber"], niches=["Combat", "Mount"], role="Control",
         mount="Climb", growth="Wave", polish="SpAttack:3", stats=("Control", 520), bond=40, lure="ITM_LURE_BELLCHIME",
         sig="Waldkonzert: Crescendo – synchronisiert alle Verbündeten auf der Zeitleiste (handeln direkt nacheinander)",
         mark="Lange Arme mit Ringmustern; das Klangmal am Brustkorb dirigiert den Puls der Gruppe",
         lore=["Die Endform der Glöckchenaffen dirigiert den Wald – ein Echo, das andere Echos im Takt hält.",
               "Führt Gruppen von Chimkins und Chimbals; abends ertönen von ihren Lichtungen ganze Konzerte.",
               "Der Lauscherglaube hält Cantaroths Abendlied für ein Wiegenlied Sylv'anors.",
               "Wärter berichten, dass ihr Chor nach dem Training mit einem Cantaroth harmonischer kämpft.",
               "Trägt Reiter an Baumriesen empor (Kletterreiten). Erscheint wild nur zur Abenddämmerung."])],
    branch=dict(name="Lorncant", epithet="nebulosa", cat="Nebelklang-Echo", arch="A18", size="L", h=1.7,
                types=("Spirit", "Sound"), habitat="Nebliger Uralthain bei Nacht", zones=[], rarity="VeryRare",
                conds=["Spawn.None"], act="Nocturnal", traits=["Mimic", "Solitary", "Singer"], niches=["Combat", "Research"],
                role="Control", growth="Wave", polish="SpAttack:3", stats=("Control", 520, (0, -0.1, 0, 0.1, 0, 0)), bond=30,
                lure="ITM_LURE_LANTERN", evo_from_prev="Level>=32 & Weather=Fog & TimeOfDay=Night",
                sig="Echoschleier: Gegner greifen 2 Züge lang ein zufälliges anderes Ziel an (Geist-Täuschung)",
                mark="Ringe verblassen zu Nebelbändern; das Klangmal flackert wie ein fernes Echo",
                lore=["Ein Chimbal, das im nächtlichen Nebel weiterwuchs, nimmt die Klangfarbe der Erinnerung an.",
                      "Singt Melodien, die es vor Jahren gehört hat; Wanderer hören darin Stimmen Verstorbener.",
                      "Im Lauscherglauben bewahrt ein Lorncant die letzten Lieder derer, die im Wald verstummt sind.",
                      "Die Akademie studiert Lorncants, weil sie Klänge über Jahrzehnte unverändert wiedergeben.",
                      "Entsteht nur, wenn sich ein Chimbal ab Level 32 nachts im Nebel weiterentwickelt."]),
)

# ---------------------------------------------------------------- L005 Blüte-Hirsch + Zweig (Arkan)
c.line_of("Three", "Muscocervus", [
    dict(name="Mossling", epithet="tenellus", cat="Mooskitz-Echo", arch="A01", size="S", h=0.55, types=("Bloom",),
         habitat="Moosige Lichtungen, Lindwald und Auen", zones=["R01_Z01", "R01_Z02"], rarity="Common", act="Diurnal",
         traits=["Shy", "Grazer", "Herd"], niches=["Combat", "Breeding"], role="Tank", growth="Steady", polish="HP:1",
         stats=("Tank", 315), evo="Level>=18", bond=55, lure="ITM_FOOD_MOSSCAKE",
         sig="Moospolster: Schild + kleine Heilung für sich selbst",
         mark="Grüne Punktreihen auf dem Rücken wie Moosflecken; 58 BPM",
         lore=["Ein häufiger Oberton des Waldbodens: Moos, das zu laufen gelernt hat.",
               "Weidet in kleinen Herden auf Lichtungen; Jungtiere verstecken sich unter Farnen.",
               "Ein Mossling, das ins Haus kommt, bringt nach altem Glauben einen milden Winter.",
               "Wird in Moosgrund gehalten, um Wiesen kurz zu halten; sehr friedlich.",
               "Bildet mit Artgenossen Herden mit Alphatier. Ab Level 18 wird es zum Reittier."]),
    dict(name="Myrthorn", epithet="vectorius", cat="Myrtenhirsch-Echo", arch="A03", size="L", h=1.7, types=("Bloom",),
         habitat="Eichenhall-Forst und Moosgrund-Hügel", zones=["R01_Z03", "R01_Z04"], rarity="Uncommon", act="Diurnal",
         traits=["Herd", "Grazer", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Ground", growth="Steady",
         polish="HP:2", stats=("Tank", 430), evo="BondTier>=4", bond=45, lure="ITM_FOOD_MOSSCAKE",
         sig="Myrtenstoß: Angriff mit Geweih, heilt um 30 % des Schadens",
         mark="Blühende Myrtenranken im Geweih leuchten zart; 54 BPM",
         lore=["Wenn ein Mossling erwachsen wird, wachsen ihm Myrtenranken als Geweih.",
               "Führt Herden zu Wasserstellen; Alphatiere tragen die prächtigsten Geweihe.",
               "Myrthorn-Geweihe, die im Herbst abfallen, gelten als Hochzeitsgeschenk.",
               "Das verbreitetste Reittier Verdanthains; Wildwacht-Ranger patrouillieren auf ihm.",
               "Erstes Bodenreittier vieler Wärter. Entwickelt sich bei tiefer Bindung (Stufe 4); bei Vollmond im Uralthain auch anders."]),
    dict(name="Vernaune", epithet="sacra", cat="Frühlingshirsch-Echo", arch="A03", size="XL", h=3.1, types=("Bloom", "Light"),
         habitat="Uralthain-Lichtungen", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Guardian", "Herd", "Glowing"], niches=["Combat", "Mount"], role="Tank", mount="Ground", growth="Late",
         polish="HP:3", stats=("Tank", 520, (0.05, 0, 0, 0.05, 0, -0.1)), bond=35, lure="ITM_FOOD_MOSSCAKE",
         sig="Frühlingserwachen: Crescendo – entfernt alle Status der eigenen Seite und heilt 25 %",
         mark="Geweih trägt leuchtende Blütenknospen, die sich im Sonnenlicht öffnen",
         lore=["Die Endform der Mooslinie entsteht nur aus tiefem Vertrauen – ein Oberton des Frühlings.",
               "Lebt im Uralthain; wo es grast, blühen am nächsten Morgen Wildblumen.",
               "Ein Vernaune soll den ersten Frühling nach der Großen Stille gebracht haben.",
               "Es zu reiten ist eine Ehre; Eichenhall verleiht Reitern eines Vernaune das Lindenabzeichen.",
               "Entwickelt sich aus einem Myrthorn mit Bindungsstufe 4."])],
    branch=dict(name="Glyphaune", epithet="runica", cat="Mondgeweih-Echo", arch="A03", size="XL", h=3.0,
                types=("Arcane", "Bloom"), habitat="Steinkreise des Uralthains bei Vollmond", zones=[], rarity="VeryRare",
                conds=["Spawn.None"], act="Nocturnal", traits=["Solitary", "Glowing", "Stargazer"],
                niches=["Combat", "Mount", "Research"], role="Control", mount="Ground", growth="Late", polish="SpAttack:3",
                stats=("Control", 520), bond=30, lure="ITM_LURE_BELLCHIME",
                evo_from_prev="BondTier>=4 & Moon=FullMoon & Zone=R01_Z06",
                sig="Mondglyphe: kehrt für den nächsten Zug die Typtabelle für ein Ziel um",
                mark="Glyphen ersetzen die Blütenknospen; sie ordnen sich zu wechselnden Mustern",
                lore=["Ein Myrthorn, das bei Vollmond im Steinkreis seinen Tonartwechsel erlebt, nimmt Arkanes in sich auf.",
                      "Steht nachts reglos in Steinkreisen; die Glyphen im Geweih zeigen Sternbilder.",
                      "Die Akademie vermutet, dass die Steinkreise des Uralthains dorunische Messinstrumente sind.",
                      "Nur wenige Wärter haben je ein Glyphaune gesehen; Gelehrte zahlen für Skizzen.",
                      "Entsteht aus Myrthorn mit Bindungsstufe 4 bei Vollmond im Uralthain."]),
)

# ---------------------------------------------------------------- L006 Lichtmotte (Licht → Geist)
c.line_of("Three", "Lucinocta", [
    dict(name="Lumpip", epithet="larvalis", cat="Glimmraupen-Echo", arch="A10", size="XS", h=0.15, types=("Light",),
         habitat="Lindenblätter in den Auen", zones=["R01_Z02", "R01_Z03"], rarity="Common", act="Nocturnal",
         traits=["Glowing", "Grazer", "Sleepy"], niches=["Combat", "Research"], role="Caster", growth="Swift",
         polish="SpAttack:1", stats=("Caster", 300), evo="Level>=15", bond=65, lure="ITM_FOOD_LINDHONEY",
         sig="Glimmfunke: kleiner Lichtangriff, der Ausweichen ignoriert",
         mark="Leuchtpunkte entlang des Körpers blinken in Wellen",
         lore=["Ein winziger Oberton des Abendlichts, der sich an Lindenblättern satt frisst.",
               "Leuchtet nachts schwach, um Fressfeinde zu verwirren; schläft tagsüber zusammengerollt.",
               "Kinder legen Lumpips in Gläser, um nachts zu lesen – und lassen sie morgens frei.",
               "Imker mögen Lumpips nicht, weil sie Lindenblätter fressen, verzeihen aber ihr Licht.",
               "Verpuppt sich ab Level 15; die Endform erscheint ab Level 30 nur nachts."]),
    dict(name="Lumow", epithet="velata", cat="Lichtfalter-Echo", arch="A10", size="S", h=0.4, types=("Light", "Spirit"),
         habitat="Nachtwiesen und Waldränder", zones=["R01_Z04", "R01_Z05"], rarity="Uncommon", act="Nocturnal",
         traits=["Glowing", "Flier", "Pollinator"], niches=["Combat", "Research"], role="Caster", growth="Swift",
         polish="SpAttack:2", stats=("Caster", 420), evo="Level>=30 & TimeOfDay=Night", bond=50, lure="ITM_LURE_LANTERN",
         sig="Schleierlicht: blendet ein Ziel (Präzision −1) und reinigt einen Verbündeten",
         mark="Augenflecken auf den Flügeln sind Klangmale – sie leuchten im Herzschlag",
         lore=["Aus der Puppe schlüpft ein Falter, dessen Flügel halb Licht, halb Schatten sind.",
               "Bestäubt nachts Blüten; Schwärme tanzen über Wiesen und folgen Laternen.",
               "Wer einem Lumow-Schwarm folgt, findet entweder einen Schatz oder einen Sumpf, sagt man.",
               "Nachtwanderer schätzen Lumows als lebende Laternen; Wildwacht nutzt sie für Nachtsuchen.",
               "Ab Level 30 entwickelt es sich nur nachts zur Endform."]),
    dict(name="Phantalume", epithet="spectralis", cat="Seelenfalter-Echo", arch="A12", size="M", h=1.2, types=("Spirit", "Light"),
         habitat="Uralthain im Nebel", zones=["R01_Z06"], rarity="Rare", conds=["Weather.Fog", "TimeOfDay.Night"],
         act="Nocturnal", traits=["Glowing", "Drifter", "Solitary"], niches=["Combat", "Research"], role="Caster",
         growth="Swift", polish="SpAttack:3", stats=("Caster", 515), bond=40, lure="ITM_LURE_LANTERN",
         sig="Seelenleuchten: Crescendo – trifft alle Gegner, Geist-Ziele doppelt geblendet",
         mark="Der ganze Körper ist ein Klangmal aus Licht; im Nebel verschwimmt er",
         lore=["Ein Falter, der so viel Licht gesammelt hat, dass sein Körper durchscheinend wurde.",
               "Treibt nachts im Nebel; berührt es Blätter, glühen diese kurz nach.",
               "Im Lauscherglauben trägt ein Phantalume Seelen sicher durch die Nacht.",
               "Die Wildwacht verbietet, Phantalumes einzufangen, um sie zu verkaufen – zu viele verschwanden einst.",
               "Wild nur bei Nebel in der Nacht im Uralthain."])],
)

# ---------------------------------------------------------------- L007 Flut-Frosch (2)
c.line_of("Two", "Rivulana", [
    dict(name="Rillo", epithet="cantrix", cat="Bachsänger-Echo", arch="A09", size="XS", h=0.2, types=("Tide",),
         habitat="Bachläufe und Tümpel im Lindwald", zones=["R01_Z01", "R01_Z02"], rarity="Common", act="Crepuscular",
         traits=["Singer", "Swimmer", "FamilyGroup"], niches=["Combat", "Field"], role="Caster", growth="Swift",
         polish="SpAttack:1", stats=("Caster", 335), evo="Level>=22", bond=60, lure="ITM_FOOD_BERRYMIX",
         sig="Bachlied: Flut-Angriff, heilt Verbündete in Reihe leicht über 2 Züge",
         mark="Blaue Ringe auf der Kehle blähen sich beim Singen",
         lore=["Ein kleiner Oberton fließenden Wassers, häufig an jedem Bach Verdanthains.",
               "Singt bei Regen im Chor; legt Laich in ruhige Buchten.",
               "Wenn die Rillos schweigen, kommt eine Dürre – so sagen die Bauern.",
               "Wird als Wetterfrosch gehalten; Rillo-Gesang ist Teil des Lindwiesen-Festes.",
               "Ab Level 22 wird es zum Wächter der Bäche."]),
    dict(name="Rillward", epithet="custos", cat="Quellwächter-Echo", arch="A09", size="M", h=0.9, types=("Tide", "Bloom"),
         habitat="Quellen und Wasserfälle der Farnschlucht", zones=["R01_Z05"], rarity="Uncommon", act="Crepuscular",
         traits=["Guardian", "Swimmer", "Singer"], niches=["Combat", "Field"], role="Caster", growth="Swift",
         polish="SpAttack:2", stats=("Caster", 490), bond=45, lure="ITM_FOOD_BERRYMIX",
         sig="Quellstrom: spült ein Ziel in die andere Reihe (Flut-Positionsverschiebung)",
         mark="Seerosenblätter auf dem Rücken tragen das Klangmal",
         lore=["Ein ausgewachsener Rillo wird zum Hüter seiner Quelle – Seerosen wachsen auf seinem Rücken.",
               "Verteidigt Quellen gegen Eindringlinge und hält das Wasser klar.",
               "An Quellen mit Rillward-Hütern werden Wünsche erhört, sagt der Volksglaube.",
               "Dörfer bitten Rillwards, an ihren Brunnen zu leben – klares Wasser garantiert.",
               "Entsteht ab Level 22 aus Rillo."])],
)

# ---------------------------------------------------------------- L008 Gift-Pilz (2)
c.line_of("Two", "Sporifungus", [
    dict(name="Sporlet", epithet="pusillus", cat="Sporenwicht-Echo", arch="A14", size="XS", h=0.25, types=("Venom",),
         habitat="Moosgrund-Senken, alte Baumstümpfe", zones=["R01_Z04"], rarity="Common", act="Nocturnal",
         traits=["Camouflaged", "Sleepy", "Symbiont"], niches=["Combat", "Breeding"], role="Control", growth="Steady",
         polish="Defense:1", stats=("Control", 340), evo="Level>=24 & Weather=Fog", bond=55, lure="ITM_FOOD_MOSSCAKE",
         sig="Sporenwolke: Gift-Stapel auf alle Gegner einer Reihe",
         mark="Lamellen unter dem Hut glimmen violett, wenn es atmet",
         lore=["Ein Oberton der Zersetzung, der totes Holz zurück in Erde verwandelt.",
               "Schläft auf Baumstümpfen; stößt bei Berührung Sporen aus.",
               "Köhler sagen, wo Sporlets wachsen, brenne die Kohle besonders gleichmäßig.",
               "Die Köhler von Moosgrund pflegen Sporlet-Gärten; die Sporen düngen ihre Felder.",
               "Entwickelt sich ab Level 24 nur bei Nebel."]),
    dict(name="Sporix", epithet="nebularis", cat="Nebelpilz-Echo", arch="A14", size="S", h=0.7, types=("Venom", "Spirit"),
         habitat="Neblige Senken, Uralthain-Ränder", zones=["R01_Z04", "R01_Z06"], rarity="Rare", conds=["Weather.Fog"],
         act="Nocturnal", traits=["Camouflaged", "Glowing", "Symbiont"], niches=["Combat", "Breeding"], role="Control",
         growth="Steady", polish="Defense:2", stats=("Control", 490), bond=40, lure="ITM_FOOD_MOSSCAKE",
         sig="Trugsporen: Gift + Täuschung (Ziel greift 1 Zug lang einen Verbündeten an)",
         mark="Hut leuchtet in Ringen; im Nebel wirft er Schatten von Gesichtern",
         lore=["Ein Sporlet, das im Nebel reifte, wächst über sich hinaus und beginnt zu leuchten.",
               "Lockt Insekten mit Licht und Duft; lebt in Symbiose mit alten Bäumen.",
               "Wer im Nebel Gesichter in Pilzschatten sieht, hat ein Sporix getroffen.",
               "Moorweise kaufen Sporix-Sporen für Heiltränke gegen Dunst – in kleiner Dosis heilsam.",
               "Wild nur bei Nebel."])],
)

# ---------------------------------------------------------------- L009 Sturm-Schwarm (2)
c.line_of("Two", "Ventimota", [
    dict(name="Skirmote", epithet="volitans", cat="Windfunken-Echo", arch="A16", size="XS", h=0.05, w=0.02,
         types=("Storm",), habitat="Auen und Waldwiesen", zones=["R01_Z02", "R01_Z03"], rarity="Common", act="Diurnal",
         traits=["Swarm", "Flier", "Playful"], niches=["Combat", "Field"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 340), evo="Level>=22", bond=60, lure="ITM_LURE_WHISTLE",
         sig="Funkenschwarm: drei kleine Treffer auf zufällige Gegner",
         mark="Jeder Funke trägt einen Lichtpunkt; der Schwarm pulsiert gemeinsam",
         lore=["Ein Schwarm winziger Windfunken, der als ein Echo zählt – ein Oberton aus vielen Stimmen.",
               "Tanzt über Wiesen, fängt Pollen aus der Luft und folgt Laufenden spielerisch.",
               "Kinder glauben, Skirmotes trügen kleine Wünsche zum Wind.",
               "Lindwiesens Müller schätzen Skirmotes, die bei Flaute die Mühlenflügel anschieben.",
               "Verdichtet sich ab Level 22 zu einem größeren Schwarm."]),
    dict(name="Skirrow", epithet="tempestas", cat="Böenschwarm-Echo", arch="A16", size="S", h=0.6, w=0.4,
         types=("Storm", "Sound"), habitat="Farnschlucht, Grate mit Wind", zones=["R01_Z05"], rarity="Uncommon",
         act="Diurnal", traits=["Swarm", "Flier", "Singer"], niches=["Combat", "Field"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 485), bond=45, lure="ITM_LURE_WHISTLE",
         sig="Sirrender Sturm: Mehrfachtreffer, verzögert getroffene Gegner leicht",
         mark="Schwarm formt im Flug ein pulsierendes Wirbelmuster",
         lore=["Ein gewachsener Funkenschwarm, der summend wie ein Lied durch Schluchten zieht.",
               "Folgt Gewitterfronten; der Schwarm summt in einer einzigen Tonhöhe.",
               "Wenn die Farnschlucht summt, so heißt es, singt der Wald gegen den Sturm an.",
               "Bei Gewittern meiden Wanderer die Schlucht – Skirrows werden dann wild.",
               "Entsteht ab Level 22 aus Skirmote."])],
)

# ---------------------------------------------------------------- L010 Blüte-Rankenschlange (2)
c.line_of("Two", "Spinoserpens", [
    dict(name="Thornkin", epithet="hamatus", cat="Rankenlings-Echo", arch="A07", size="S", h=0.6, types=("Bloom",),
         habitat="Hecken, Brombeerdickicht", zones=["R01_Z03", "R01_Z05"], rarity="Uncommon", act="Diurnal",
         traits=["Ambusher", "Camouflaged", "Solitary"], niches=["Combat"], role="Striker", growth="Steady",
         polish="Attack:1", stats=("Striker", 345), evo="Item=ITM_EVO_BLOOM", bond=45, lure="ITM_FOOD_BERRYMIX",
         sig="Dornenschlinge: Angriff, Ziel verliert 1 Stufe Geschwindigkeit",
         mark="Dornenreihe entlang des Rückens; Spitzen glühen grün beim Angriff",
         lore=["Ein Oberton der Hecke, der sich wie eine Ranke bewegt.",
               "Lauert im Dickicht auf Kleintiere, verteidigt Beerensträucher gegen Fresser.",
               "Ein Thornkin um den Gartenzaun schützt das Haus vor bösen Absichten, sagt man.",
               "Gärtner ziehen Thornkins als Heckenwächter; ihre Bisse sind schmerzhaft, aber harmlos.",
               "Entwickelt sich mit einem Obertonkristall (Blüte)."]),
    dict(name="Thorncoil", epithet="rosaceus", cat="Rosenwürger-Echo", arch="A07", size="M", h=1.4, types=("Bloom", "Venom"),
         habitat="Dichte Hecken der Farnschlucht", zones=["R01_Z05"], rarity="Rare", conds=["Weather.Rain"], act="Diurnal",
         traits=["Ambusher", "Territorial", "Camouflaged"], niches=["Combat"], role="Striker", growth="Steady",
         polish="Attack:2", stats=("Striker", 495), bond=35, lure="ITM_FOOD_BERRYMIX",
         sig="Rosenwürgegriff: hält ein Ziel 1 Zug fest (Zeitleiste +), Gift-Stapel",
         mark="Rosenblüten entlang des Körpers öffnen sich im Takt des Klangmals",
         lore=["Wenn eine Ranke Blütenkraft aufnimmt, wird aus ihr ein Würger mit Rosenduft.",
               "Umschlingt Beute und verteidigt Reviere hartnäckig; bei Regen besonders aktiv.",
               "Ein Thorncoil, das rot blüht, soll Liebende zusammenführen.",
               "Eichenhalls Rosengärten werden von Thorncoils bewacht – Diebe meiden sie.",
               "Wild nur bei Regen."])],
)

# ---------------------------------------------------------------- L011 Stein → Schwerkraft (2)
c.line_of("Two", "Lapidorbis", [
    dict(name="Pebi", epithet="rotundus", cat="Kugelpanzer-Echo", arch="A11", size="S", h=0.35, w=12.0, types=("Stone",),
         habitat="Lindwald-Bäche und Farnschlucht", zones=["R01_Z01", "R01_Z05"], rarity="Common", act="Cathemeral",
         traits=["Sleepy", "Burrower", "Shy"], niches=["Combat", "Breeding"], role="Tank", growth="Steady",
         polish="Defense:1", stats=("Tank", 330), evo="Stat:Defense>Attack & Level>=24", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Einigeln: Verteidigung +2 Stufen, kostet wenig Zeit",
         mark="Ein einziges Kreismuster auf dem Panzer; leuchtet nur beim Einigeln",
         lore=["Ein runder Oberton aus Bachstein, oft mit einem Kiesel verwechselt.",
               "Schläft viel, rollt bachabwärts, wenn es aufgeschreckt wird.",
               "Ein Pebi im Fundament gilt als Schutz vor Einsturz.",
               "Im Prolog ist Pebi oft das erste wilde Echo, das neue Wärter treffen.",
               "Entwickelt sich ab Level 24, wenn seine Verteidigung höher ist als sein Angriff."]),
    dict(name="Orbeloth", epithet="levitans", cat="Schwebefels-Echo", arch="A13", size="M", h=1.1, types=("Gravity", "Stone"),
         habitat="Farnschlucht, Schwebesteine", zones=[], rarity="Rare", conds=["Spawn.None"], act="Cathemeral",
         traits=["Guardian", "Drifter", "Sleepy"], niches=["Combat", "Research"], role="Tank", growth="Steady",
         polish="Defense:2", stats=("Tank", 490), bond=40, lure="ITM_FOOD_ORECRUMBS",
         sig="Schwerpunkt: zieht einen Gegner in die Vorderreihe und schützt die eigene Hinterreihe",
         mark="Klangmal kreist als Orbit aus Lichtpunkten um den Körper",
         lore=["Ein Pebi, das genug Ruhe gefunden hat, beginnt zu schweben – ein ferner Ton Orh'gruuns.",
               "Schwebt eine Handbreit über dem Boden und hält kleine Steine in seiner Umlaufbahn.",
               "Manche glauben, Orbeloths wiesen den Weg zu den schwebenden Felsen von Kharsgrat.",
               "Die Akademie misst an Orbeloths Schwerefelder – Hinweise auf die Hebung Nimbaras.",
               "Entsteht aus Pebi mit höherer Verteidigung als Angriff ab Level 24."])],
)

# ---------------------------------------------------------------- Einzelarten
c.line_of("Single", "Cuprocoleus", [
    dict(name="Rivetkin", epithet="faber", cat="Kupferkäfer-Echo", arch="A10", size="S", h=0.35, w=4.0, types=("Metal",),
         habitat="Werkstätten, Mühlen, Kupferadern", zones=["R01_Z03"], rarity="Uncommon", act="Cathemeral",
         traits=["Collector", "Hoarder", "Curious"], niches=["Combat", "Field"], role="Tank", growth="Steady",
         polish="Defense:2", stats=("Tank", 460, (0, 0.1, 0, 0, 0, 0)), bond=50, lure="ITM_FOOD_ORECRUMBS",
         sig="Nietpanzer: Rüstung (flache Schadensreduktion) für 3 Züge, kontert Kontaktangriffe",
         mark="Grünspan-Muster auf dem Panzer leuchtet bei Arbeit",
         lore=["Ein Oberton aus Kupfer und Fleiß, der sich in der Nähe von Menschen am wohlsten fühlt.",
               "Sammelt Nägel und Nieten, ordnet sie zu Mustern; repariert kleine Mechanismen.",
               "Ein Rivetkin in der Werkstatt bedeutet, dass nichts verloren geht.",
               "Eichenhalls Handwerker halten Rivetkins als Gehilfen – sie finden jede verlorene Schraube.",
               "Entwickelt sich nicht. Seine Panzerung wird mit dem Alter dicker."])],
)
c.line_of("Single", "Carbonimp", [
    dict(name="Cindrel", epithet="focarius", cat="Herdwicht-Echo", arch="A04", size="S", h=0.5, types=("Ember",),
         habitat="Köhlermeiler und Herdstellen in Moosgrund", zones=["R01_Z04"], rarity="Rare", conds=["TimeOfDay.Night"],
         act="Nocturnal", traits=["Thermal", "Curious", "ToolUser"], niches=["Combat", "Field"], role="Caster",
         growth="Steady", polish="SpAttack:2", stats=("Caster", 470), bond=45, lure="ITM_FOOD_CHARCOAL",
         sig="Herdglut: Glut-Angriff, legt Glutboden auf die Zielreihe",
         mark="Augen und Fingerspitzen glimmen wie Kohle; das Klangmal flackert beim Sprechen der Köhler",
         lore=["Ein seltener Glut-Oberton im Wald – geboren in Köhlermeilern, wo Feuer und Holz einander zuhören.",
               "Hält Meiler nachts am Glimmen, stibitzt Essen und wärmt sich an Herdstellen.",
               "Köhler lassen nachts eine Schale Kohle für den Herdwicht stehen.",
               "Ohne Cindrels, sagen die Köhler von Moosgrund, gäbe es keine gute Holzkohle.",
               "Einzige Glut-Art Verdanthains. Wild nur nachts bei den Meilern von Moosgrund."])],
)

c.write()
