#!/usr/bin/env python3
"""K21 – Kreaturenkatalog 2a: Kharsgrat (R02), Kodex #033–#058."""
from catalog_lib import Catalog

c = Catalog(start_kodex=33, start_line=14, region="R02")
Z = lambda *n: [f"R02_Z{i:02d}" for i in n]

# L014 Felskrabbe (Stein) + Zweig (Schwerkraft) – Kletterreittier
c.line_of("Three", "Cragocancer", [
    dict(name="Craglet", epithet="saxicola", cat="Felskrabben-Echo", arch="A10", size="XS", h=0.25, w=1.8, types=("Stone",),
         habitat="Geröllhalden und Felsspalten", zones=Z(1, 2), rarity="Common", act="Cathemeral",
         traits=["Climber", "Shy", "Hoarder"], niches=["Combat", "Breeding"], role="Tank", growth="Steady",
         polish="Defense:1", stats=("Tank", 305), evo="Level>=18", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Spaltenschutz: Schild für sich selbst, kontert den nächsten Kontaktangriff",
         mark="Kantige Rillen auf den Scheren glimmen beim Festklammern",
         lore=["Ein Oberton der Steilwand, der lernte, sich überall festzuhalten.",
               "Lebt in Spalten, sammelt glänzende Splitter und klettert senkrechte Wände hinauf.",
               "Bergleute sagen, wo Craglets wohnen, ist das Gestein fest und sicher.",
               "Kinder in Brakkfels halten Craglets wie Haustiere; sie zwicken nur bei grobem Umgang.",
               "Wird ab Level 18 groß genug, um Reiter an Wänden zu tragen."]),
    dict(name="Cragar", epithet="scandens", cat="Wandläufer-Echo", arch="A10", size="L", h=1.7, w=180, types=("Stone",),
         habitat="Steilwände und Schluchten", zones=Z(3, 4), rarity="Uncommon", act="Cathemeral",
         traits=["Climber", "Territorial", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Climb",
         growth="Steady", polish="Defense:2", stats=("Tank", 430), evo="Level>=34", bond=45, lure="ITM_FOOD_ORECRUMBS",
         sig="Klammergriff: hält ein Ziel fest (Zeitleiste +) und erhält Verteidigung +1",
         mark="Rückenschild trägt ein Felsmosaik als Klangmal; 62 BPM",
         lore=["Wenn ein Craglet seine Schale oft genug gewechselt hat, wird es zum Wandläufer.",
               "Klettert mit acht Beinen senkrecht und quer; verteidigt Nistwände gegen Greifvögel.",
               "Klans erzählen, die ersten Brücken über den Grollschlund hätten Cragars gespannt.",
               "Das Kletterreittier Kharsgrats: Wärter erreichen damit Horste und Erzadern.",
               "Trägt Reiter an Wänden. Ab Level 34 wird es zum Bergkoloss; an Schwebefelsen kann ein anderer Ton entstehen."]),
    dict(name="Kraggoth", epithet="titanicus", cat="Bergkrabben-Echo", arch="A10", size="L", h=2.8, w=420, types=("Stone", "Metal"),
         habitat="Grollschlund und Erzgrat", zones=[], rarity="Rare", conds=["Spawn.None"], act="Cathemeral",
         traits=["Climber", "Guardian", "Solitary"], niches=["Combat", "Mount"], role="Tank", mount="Climb",
         growth="Steady", polish="Defense:3", stats=("Tank", 525), bond=35, lure="ITM_FOOD_ORECRUMBS",
         sig="Bergpanzer: Crescendo – Schild für die ganze Seite, Gegner in der Vorderreihe werden zurückgestoßen",
         mark="Erzadern durchziehen den Panzer und pulsieren rot im Takt",
         lore=["Die Endform der Felskrabben hat Erz in ihren Panzer aufgenommen.",
               "Ruht oft wochenlang in derselben Spalte; Erzadern wachsen ihm aus dem Rücken.",
               "Ein Kraggoth soll einst einen Minengang so lange gehalten haben, bis alle Bergleute draußen waren.",
               "Klans verehren Kraggoths als Beschützer der Minen; ihn zu stören gilt als Frevel.",
               "Entsteht aus Cragar ab Level 34."])],
    branch=dict(name="Anchrex", epithet="gravis", cat="Schwerkrabben-Echo", arch="A10", size="L", h=2.6, w=900,
                types=("Gravity", "Stone"), habitat="Schwebende Ahnenfelsen", zones=[], rarity="VeryRare",
                conds=["Spawn.None"], act="Cathemeral", traits=["Climber", "Solitary", "Drifter"],
                niches=["Combat", "Mount", "Research"], role="Control", mount="Climb", growth="Steady", polish="Defense:3",
                stats=("Control", 525), bond=30, lure="ITM_FOOD_ORECRUMBS",
                evo_from_prev="Level>=34 & Zone=R02_Z02 & Moon=FullMoon",
                sig="Ankerfeld: tauscht die Reihen der Gegner und hält sie 1 Zug fest",
                mark="Schwebende Steinsplitter ordnen sich um die Scheren zu Kreisbahnen",
                lore=["Ein Cragar, das unter Schwebefelsen bei Vollmond wächst, nimmt die Schwere Orh'gruuns an.",
                      "Klettert an Felsen, die selbst schweben; kleine Steine kreisen um seine Scheren.",
                      "Ahnenfelsen sollen von Anchrex gehalten werden, damit sie nicht davonschweben.",
                      "Die Akademie zahlt hohe Prämien für Messungen an Anchrex-Schwerefeldern.",
                      "Entsteht aus Cragar ab Level 34 bei Vollmond auf den Kharsholm-Terrassen."]),
)

# L015 Schwebekonstrukt (Schwerkraft)
c.line_of("Three", "Tetralithus", [
    dict(name="Tetri", epithet="cubicus", cat="Würfelstein-Echo", arch="A13", size="S", h=0.35, w=14, types=("Gravity",),
         habitat="Schwebefelsen-Felder", zones=Z(2), rarity="Uncommon", act="Cathemeral",
         traits=["Drifter", "Collector", "Sleepy"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpDefense:1", stats=("Control", 310), evo="Level>=20", bond=50, lure="ITM_LURE_BELLCHIME",
         sig="Schwerepuls: zieht ein Ziel eine Reihe nach vorn",
         mark="Leuchtende Kanten eines Würfels; dreht sich langsam um sich selbst",
         lore=["Ein Oberton aus geordneter Schwere – vier Steinwürfel, die einander umkreisen.",
               "Schwebt über Feldern von Schwebefelsen und ordnet Kiesel zu Gittern.",
               "Klans halten Tetris für Zählsteine der Ahnen, die das Alter der Berge messen.",
               "Steinmetze nutzen sie als Wasserwaage: Ein Tetri liegt immer exakt waagrecht.",
               "Ab Level 20 fügen sich die Würfel zu einem größeren Körper."]),
    dict(name="Tetrel", epithet="ordinatus", cat="Gitterstein-Echo", arch="A13", size="M", h=1.0, w=90, types=("Gravity", "Stone"),
         habitat="Kharsholm-Terrassen, Ahnenfelsen", zones=Z(2, 3), rarity="Rare", conds=["TimeOfDay.Night"],
         act="Nocturnal", traits=["Drifter", "Collector", "Guardian"], niches=["Combat", "Research"], role="Control",
         growth="Wave", polish="SpDefense:2", stats=("Control", 430), evo="Level>=36", bond=40, lure="ITM_LURE_BELLCHIME",
         sig="Gitterbann: tauscht die Position zweier Gegner",
         mark="Leuchtgitter verbindet die schwebenden Blöcke",
         lore=["Aus vielen Würfeln wird ein schwebendes Gitter, das den Raum um sich ordnet.",
               "Nachts aktiv; richtet Steine in geometrischen Mustern auf Plateaus aus.",
               "Die Muster der Tetrels gelten als Karten – nur weiß niemand, wohin sie führen.",
               "Akademie-Kartografen kopieren ihre Muster; manche decken sich mit dorunischen Plänen.",
               "Ab Level 36 erreicht es die Endform."]),
    dict(name="Ponderath", epithet="maiestas", cat="Schwerkern-Echo", arch="A13", size="L", h=2.4, w=2200,
         types=("Gravity",), habitat="Grollhorn-Gipfel", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Guardian", "Solitary", "Stargazer"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:3", stats=("Control", 530, (0, -0.1, 0.05, 0.1, 0, -0.05)), bond=30, lure="ITM_LURE_BELLCHIME",
         sig="Gravitationskern: Crescendo – alle Gegner verlieren 2 GES-Stufen und werden in die Vorderreihe gezogen",
         mark="Ein dunkler Kern im Inneren, um den Lichtlinien kreisen",
         lore=["Ein Gitter, das sich so dicht zusammenzog, dass es zu einem Kern der Schwere wurde.",
               "Ruht auf dem Gipfel und blickt nachts zu den Himmelinseln, als würde es sie halten.",
               "Man sagt, die Ponderaths hielten Nimbara noch heute am Himmel – ein Echo von Orh'gruuns Werk.",
               "Bergführer meiden Gipfelnächte, wenn Ponderaths wach sind: Kompasse spielen verrückt.",
               "Entsteht aus Tetrel ab Level 36."])],
)

# L016 Erzdachs (Metall) – Bodenreittier
c.line_of("Three", "Ferromeles", [
    dict(name="Ferrkin", epithet="fossor", cat="Erzdachs-Echo", arch="A01", size="S", h=0.45, w=11, types=("Metal",),
         habitat="Stollen und Erzadern", zones=Z(1, 4), rarity="Common", act="Nocturnal",
         traits=["Burrower", "Lithophage", "Curious"], niches=["Combat", "Field"], role="Striker", growth="Steady",
         polish="Attack:1", stats=("Striker", 315), evo="Level>=20", bond=50, lure="ITM_FOOD_ORECRUMBS",
         sig="Grabkralle: Metall-Angriff, ignoriert Schilde zur Hälfte",
         mark="Eisenstreifen über den Augen glimmen in der Dunkelheit",
         lore=["Ein Oberton aus Erz und Neugier, geboren in den Adern des Berges.",
               "Gräbt Gänge, frisst Erz und hustet glänzende Klümpchen aus.",
               "Ein Ferrkin, der in eine Mine einzieht, verrät eine reiche Ader.",
               "Bergleute folgen Ferrkins zu neuen Adern; dafür lassen sie ihnen Erzkrümel liegen.",
               "Ab Level 20 wächst ihm ein Eisenkamm."]),
    dict(name="Ferrow", epithet="cristatus", cat="Eisenkamm-Echo", arch="A02", size="M", h=1.0, types=("Metal", "Stone"),
         habitat="Erzgrat und alte Minen", zones=Z(4), rarity="Uncommon", act="Nocturnal",
         traits=["Burrower", "Territorial", "Lithophage"], niches=["Combat", "Field"], role="Striker", growth="Steady",
         polish="Attack:2", stats=("Striker", 435), evo="Level>=34", bond=40, lure="ITM_FOOD_ORECRUMBS",
         sig="Kammramme: Angriff mit Rückstoß, stärker gegen Kristall",
         mark="Eisenkamm vom Kopf bis zum Schwanz mit pulsierenden Nieten",
         lore=["Aus dem Erzdachs wird ein Gräber mit einem Kamm aus Eisen.",
               "Verteidigt Erzadern gegen andere Gräber; schläft tagsüber in kühlen Stollen.",
               "In Schmiedeliedern ist der Ferrow der Lehrling Pyr'thagons.",
               "Schmiede kaufen Ferrow-Kammschuppen als Rohstoff; sie fallen beim Wachstum ab.",
               "Ab Level 34 vollendet sich die Linie zum Reittier."]),
    dict(name="Forgoth", epithet="incudis", cat="Ambossdachs-Echo", arch="A02", size="L", h=1.8, types=("Metal", "Stone"),
         habitat="Tiefe Minen des Erzgrats", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Burrower", "Solitary", "Guardian"], niches=["Combat", "Mount"], role="Striker", mount="Ground",
         growth="Steady", polish="Attack:3", stats=("Striker", 535), bond=35, lure="ITM_FOOD_ORECRUMBS",
         sig="Ambossschlag: Crescendo – massiver Metall-Angriff, Ziel erhält 2 Züge Erschüttert",
         mark="Rücken wie ein Amboss; Klangmal schlägt Funken bei jedem Schritt",
         lore=["Die Endform der Erzdachse trägt einen Rücken, auf dem man schmieden könnte.",
               "Gräbt sich durch Fels wie durch Erde; sein Schritt klingt wie Hammerschläge.",
               "Klans schwören auf einen Forgoth-Rücken, wenn sie ein Bündnis schmieden.",
               "Reiter auf Forgoth durchqueren Geröllfelder, die für andere unpassierbar sind.",
               "Trägt Reiter (Bodenreiten). Entsteht aus Ferrow ab Level 34."])],
)

# L017 Gratadler (Sturm) – Flugreittier
c.line_of("Three", "Cristaquila", [
    dict(name="Gratkin", epithet="pullus", cat="Gratfalken-Echo", arch="A05", size="XS", h=0.28, types=("Storm",),
         habitat="Horste an Felskanten", zones=Z(1, 3), rarity="Common", act="Diurnal",
         traits=["Flier", "Nester", "Curious"], niches=["Combat"], role="Speed", growth="Steady", polish="Speed:1",
         stats=("Speed", 310), evo="Level>=20", bond=50, lure="ITM_LURE_WHISTLE",
         sig="Gratschnitt: schneller Angriff aus der Höhe",
         mark="Streifen über den Flügeln leuchten beim Sturzflug",
         lore=["Ein Oberton der Grate, wo der Wind ununterbrochen über die Kanten fegt.",
               "Nistet in Felsspalten, lernt das Fliegen in den Böen über dem Grollschlund.",
               "Junge Klanskrieger mussten einst ein Gratkin-Federchen vom Horst holen.",
               "Heute ist das verboten; die Wildwacht beringt stattdessen Jungvögel.",
               "Ab Level 20 wächst es zum Gratjäger heran."]),
    dict(name="Gratwyn", epithet="venator", cat="Gratjäger-Echo", arch="A05", size="M", h=1.0, types=("Storm",),
         habitat="Grollhorn und offene Grate", zones=Z(4, 5), rarity="Uncommon", act="Diurnal",
         traits=["Flier", "Hunter", "Territorial"], niches=["Combat"], role="Speed", growth="Steady", polish="Speed:2",
         stats=("Speed", 435), evo="Level>=36 & Weather=Thunderstorm", bond=40, lure="ITM_LURE_WHISTLE",
         sig="Sturzböe: kritische Trefferchance erhöht, eigene Zeitkosten −",
         mark="Klangmal zeichnet Blitzlinien unter die Flügel",
         lore=["Ein ausgewachsener Gratfalke jagt im Sturzflug zwischen den Felsnadeln.",
               "Verteidigt ganze Grate als Revier; jagt Bergziegen-Jungtiere und Schwärme.",
               "Ein kreisender Gratwyn über einem Pass gilt als Warnung vor Steinschlag.",
               "Kharsholms Wachen nutzen Gratwyns, um Wanderer in Not aufzuspüren.",
               "Entwickelt sich ab Level 36 nur während eines Gewitters."]),
    dict(name="Gratrex", epithet="fulminans", cat="Donneradler-Echo", arch="A05", size="L", h=2.1, types=("Storm", "Metal"),
         habitat="Gipfel bei Gewitter", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Flier", "Hunter", "Solitary"], niches=["Combat", "Mount"], role="Striker", mount="Fly", growth="Steady",
         polish="Attack:3", stats=("Striker", 535), bond=30, lure="ITM_LURE_WHISTLE",
         sig="Donnersturz: Crescendo – trifft alle Gegner, Metall-Ziele erleiden Blitzschlag-Bonus",
         mark="Metallisch glänzende Schwungfedern leiten Blitze; das Klangmal knistert",
         lore=["Ein Gratwyn, das im Gewitter wächst, fängt den Blitz in seinen Federn.",
               "Kreist bei Gewittern über den Gipfeln und lenkt Blitze in Erzgrate.",
               "Kharsk-Sagen nennen den Donner das Flügelschlagen eines Gratrex.",
               "Ein Gratrex als Flugreittier gilt als Krönung jeder Wärterlaufbahn in Kharsgrat.",
               "Trägt Reiter durch die Luft. Entsteht nur bei Gewitter ab Level 36."])],
)

# L018 Murmeltier (Stein, 2)
c.line_of("Two", "Glareomys", [
    dict(name="Kiesi", epithet="vigilans", cat="Pfeifkiesel-Echo", arch="A01", size="S", h=0.4, types=("Stone",),
         habitat="Almwiesen und Geröll", zones=Z(1, 2), rarity="Common", act="Diurnal",
         traits=["Herd", "Singer", "Burrower"], niches=["Combat", "Field"], role="AllRound", growth="Swift",
         polish="Defense:1", stats=("AllRound", 335), evo="Level>=24", bond=60, lure="ITM_FOOD_ALPINECHEESE",
         sig="Warnpfiff: alle Verbündeten erhalten Ausweichen +1 für 1 Zug",
         mark="Weiße Kiesel-Punkte auf der Brust blinken beim Pfeifen",
         lore=["Ein häufiger Oberton der Almwiesen, der zwischen Steinen wohnt.",
               "Lebt in Kolonien; Wächter pfeifen bei Gefahr, alle verschwinden in Bauen.",
               "Hirten sagen, wenn die Kiesis pfeifen, kommt Wetter über den Grat.",
               "In Hrallsted begrüßen Kiesis jeden Morgen die Hirten – und betteln um Käse.",
               "Ab Level 24 wird es zum Wächter der Kolonie."]),
    dict(name="Kiesward", epithet="custos", cat="Almwächter-Echo", arch="A02", size="M", h=0.9, types=("Stone", "Sound"),
         habitat="Almen von Hrallsted", zones=Z(2, 3), rarity="Uncommon", act="Diurnal",
         traits=["Guardian", "Singer", "Herd"], niches=["Combat", "Field"], role="AllRound", growth="Swift",
         polish="Defense:2", stats=("AllRound", 495), bond=45, lure="ITM_FOOD_ALPINECHEESE",
         sig="Grat-Echo: Klang-Angriff, verzögert Ziel und gibt Verbündeten Harmonie",
         mark="Felsplatten am Hals vibrieren sichtbar beim Rufen",
         lore=["Ein ausgewachsener Kiesi, dessen Pfiff von den Gipfeln widerhallt.",
               "Bewacht Kolonien und warnt mit weithin tragenden Rufen.",
               "Die Rufe der Kieswards sollen Lawinen auslösen können – deshalb grüßt man sie leise.",
               "Hirten halten Kieswards als Herdenwächter; sie hören Raubtiere auf Kilometer.",
               "Entsteht aus Kiesi ab Level 24."])],
)

# L019 Ammonit (Stein, 2) – Bodenreittier
c.line_of("Two", "Spirolithus", [
    dict(name="Lithi", epithet="spiralis", cat="Spiralstein-Echo", arch="A11", size="S", h=0.4, w=13, types=("Stone",),
         habitat="Linn-Quelle, Schmelzwasserbäche", zones=Z(1, 3), rarity="Uncommon", act="Crepuscular",
         traits=["Sleepy", "Swimmer", "Collector"], niches=["Combat", "Breeding"], role="Tank", growth="Late",
         polish="SpDefense:1", stats=("Tank", 340), evo="Level>=26", bond=50, lure="ITM_FOOD_ORECRUMBS",
         sig="Spiralpanzer: Spezialverteidigung +2",
         mark="Spirale auf dem Gehäuse dreht sich leuchtend beim Atmen",
         lore=["Ein uralter Oberton – Fossilien in Kharsgrat zeigen dieselbe Spirale.",
               "Kriecht durch Schmelzwasser, sammelt Mineralien und schläft in Strudeln.",
               "Ein Lithi im Brunnen hält das Wasser rein, sagen die Kharsk.",
               "Fossiliensammler verwechseln lebende Lithis oft mit Versteinerungen.",
               "Ab Level 26 wächst das Gehäuse zu tragbarer Größe."]),
    dict(name="Lithshell", epithet="gigas", cat="Spiralberg-Echo", arch="A11", size="L", h=1.8, w=600, types=("Stone", "Tide"),
         habitat="Bergseen und Quellbecken", zones=Z(3), rarity="Rare", conds=["TimeOfDay.Dusk"], act="Crepuscular",
         traits=["Sleepy", "Swimmer", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Ground", growth="Late",
         polish="SpDefense:2", stats=("Tank", 500), bond=40, lure="ITM_FOOD_ORECRUMBS",
         sig="Strudelschild: Schild für die Reihe, reflektiert einen Teil des Flut-Schadens",
         mark="Die Spirale hat sieben Windungen, jede leuchtet in eigenem Takt",
         lore=["Ein Lithi, das genug Mineralien gesammelt hat, wird zu einem wandernden Spiralberg.",
               "Steigt bei Abenddämmerung aus Bergseen und weidet Flechten.",
               "Die sieben Windungen sollen sieben Jahrhunderte bedeuten.",
               "Langsam, aber trittsicher – beliebt bei Säumern als Lastenträger.",
               "Trägt Reiter (Bodenreiten). Wild nur zur Abenddämmerung."])],
)

# L020 Schneehase (Frost, 2)
c.line_of("Two", "Pruinalepus", [
    dict(name="Rimlet", epithet="nivalis", cat="Reifhasen-Echo", arch="A01", size="S", h=0.4, types=("Frost",),
         habitat="Schneefelder am Grollhorn", zones=Z(5), rarity="Common", act="Crepuscular",
         traits=["Shy", "Camouflaged", "FamilyGroup"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 340), evo="Level>=24 & Weather=Snow", bond=55, lure="ITM_FOOD_ALPINECHEESE",
         sig="Reifsprung: Frost-Angriff, Ziel wird verlangsamt (Zeitkosten +)",
         mark="Eiskristallmuster im Fell, unsichtbar bis es leuchtet",
         lore=["Ein Oberton des Reifs, der auf den Gipfeln in Familien lebt.",
               "Im Schnee nahezu unsichtbar; flieht in Sprüngen und hinterlässt Spuren aus Eiskristallen.",
               "Wer einem Rimlet folgt, findet den Weg vom Gipfel herunter.",
               "Bergführer erkennen an Rimlet-Spuren, wo der Schnee trägt.",
               "Entwickelt sich ab Level 24 nur bei Schneefall."]),
    dict(name="Rimpaw", epithet="glacialis", cat="Frostläufer-Echo", arch="A01", size="M", h=0.85, types=("Frost", "Storm"),
         habitat="Gipfelgrate im Schneesturm", zones=Z(5), rarity="Rare", conds=["Weather.Snow"], act="Crepuscular",
         traits=["Hunter", "Camouflaged", "Solitary"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 500), bond=40, lure="ITM_FOOD_ALPINECHEESE",
         sig="Schneegestöber: trifft alle Gegner, senkt Präzision",
         mark="Pfoten hinterlassen leuchtende Eisabdrücke",
         lore=["Ein Rimlet, das im Schneesturm wächst, wird schneller als der Wind über dem Grat.",
               "Jagt im Schneegestöber; seine Spuren gefrieren zu kleinen Kristallen.",
               "Hirten glauben, ein Rimpaw bringe Schnee mit, wo es läuft.",
               "Selten gesehen; Fotografien sind in der Akademie heiß begehrt.",
               "Wild nur bei Schneefall am Grollhorn."])],
)

# L021 Quarzwurm (Kristall, 2)
c.line_of("Two", "Quarzovermis", [
    dict(name="Quarling", epithet="lucidus", cat="Quarzwurm-Echo", arch="A07", size="S", h=0.6, w=6, types=("Crystal",),
         habitat="Quarzadern in Höhlen und Stollen", zones=Z(3, 4), rarity="Uncommon", act="Nocturnal",
         traits=["Burrower", "Lithophage", "Glowing"], niches=["Combat", "Field"], role="Caster", growth="Steady",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=26", bond=50, lure="ITM_FOOD_CRYSTALSALT",
         sig="Prismasplitter: Kristall-Angriff, lädt sich bei Nichtnutzung auf",
         mark="Durchscheinender Körper mit wanderndem Lichtpunkt",
         lore=["Ein Oberton des Quarzes, der sich durch Kristalladern frisst.",
               "Leuchtet in dunklen Stollen; hinterlässt glatte, gläserne Gänge.",
               "Bergleute folgen dem Licht eines Quarlings zu reinen Quarzadern.",
               "In Prismara gilt ein Quarling als Bote aus den Tiefen.",
               "Ab Level 26 wird der Körper zu einem Gewinde aus Kristall."]),
    dict(name="Quarcoil", epithet="prismaticus", cat="Prismaschlangen-Echo", arch="A07", size="M", h=1.5, w=60,
         types=("Crystal", "Stone"), habitat="Grollschlund-Höhlen", zones=Z(3), rarity="Rare", conds=["TimeOfDay.Night"],
         act="Nocturnal", traits=["Burrower", "Glowing", "Territorial"], niches=["Combat", "Field"], role="Caster",
         growth="Steady", polish="SpAttack:2", stats=("Caster", 495), bond=40, lure="ITM_FOOD_CRYSTALSALT",
         sig="Brechstrahl: Kristall-Strahl, der zu 25 % auf ein zweites Ziel bricht",
         mark="Prismenschuppen zerlegen das Klangmal-Licht in Regenbogenfarben",
         lore=["Ein ausgewachsener Quarzwurm, dessen Schuppen Licht in Farben zerlegen.",
               "Ringelt sich nachts um Quarzsäulen und lässt Höhlen in Regenbogenlicht erstrahlen.",
               "Das Farbenspiel eines Quarcoil soll den Weg nach Prismara weisen.",
               "Kristallstimmer aus Prismara besuchen Kharsgrat, um Quarcoils zu studieren.",
               "Wild nur nachts im Grollschlund."])],
)

# L022 Salamander (Glut → Licht, 2)
c.line_of("Two", "Aurorasalamandra", [
    dict(name="Emblit", epithet="ignitus", cat="Glutmolch-Echo", arch="A09", size="XS", h=0.2, types=("Ember",),
         habitat="Warme Quellen und Schmiedeabwärme", zones=Z(2), rarity="Uncommon", act="Midday",
         traits=["Thermal", "Sunbather", "Curious"], niches=["Combat", "Field"], role="Caster", growth="Steady",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=26 & TimeOfDay=Dawn", bond=55, lure="ITM_FOOD_CHARCOAL",
         sig="Glutfunke: Glut-Angriff mit Brand-Chance",
         mark="Orange Punkte auf dem Rücken glimmen wie Kohlen",
         lore=["Ein seltener Glut-Oberton in den Bergen, der an Schmieden und warmen Quellen lebt.",
               "Sonnt sich auf heißen Steinen und schläft in Schmiedeessen.",
               "Ein Emblit in der Esse gilt als Segen für gutes Schmiedewerk.",
               "Kharsholms Schmiede füttern Emblits mit Kohle und lassen sie im Feuer baden.",
               "Entwickelt sich ab Level 26 nur bei Morgendämmerung."]),
    dict(name="Dawnix", epithet="aurorae", cat="Morgenglut-Echo", arch="A09", size="M", h=0.9, types=("Light", "Ember"),
         habitat="Ostgrate im ersten Sonnenlicht", zones=Z(4, 5), rarity="Rare", conds=["TimeOfDay.Dawn"],
         act="Diurnal", traits=["Sunbather", "Glowing", "Solitary"], niches=["Combat"], role="Caster", growth="Steady",
         polish="SpAttack:2", stats=("Caster", 500), bond=40, lure="ITM_FOOD_CHARCOAL",
         sig="Morgenröte: Licht-Angriff, der Ausweichen ignoriert und Glutboden legt",
         mark="Kamm aus Licht entlang des Rückens, hell wie die aufgehende Sonne",
         lore=["Ein Emblit, das im ersten Morgenlicht wächst, trägt die Sonne auf dem Rücken.",
               "Klettert vor der Morgendämmerung auf Ostgrate und wartet auf die Sonne.",
               "Die Kharsk grüßen den Morgen mit einem Lied für die Dawnix.",
               "Bergwanderer brechen früh auf, um Dawnix im Sonnenaufgang zu fotografieren.",
               "Wild nur zur Morgendämmerung."])],
)

# Einzelarten
c.line_of("Single", "Memorumbra", [
    dict(name="Memoro", epithet="avitus", cat="Ahnenhauch-Echo", arch="A12", size="M", h=1.2, types=("Spirit",),
         habitat="Schwebende Ahnenfelsen", zones=Z(2), rarity="Rare", conds=["Weather.Fog"], act="Nocturnal",
         traits=["Mimic", "Guardian", "Drifter"], niches=["Combat", "Research"], role="Support", growth="Wave",
         polish="SpDefense:2", stats=("Support", 470), bond=35, lure="ITM_LURE_LANTERN",
         sig="Ahnenruf: heilt einen Verbündeten und gibt ihm Furcht-Immunität",
         mark="Klanszeichen erscheinen als leuchtende Gravuren in der Nebelgestalt",
         lore=["Ein Geist-Oberton, der an den Ahnenfelsen entsteht, wo Klans ihre Schwüre leisten.",
               "Schwebt im Nebel um die Felsen und wiederholt geflüsterte Worte vergangener Schwüre.",
               "Die Kharsk glauben, im Memoro sprächen ihre Ahnen.",
               "Bei Schwurnacht-Festen erscheinen besonders viele Memoros – niemand stört sie.",
               "Wild nur bei Nebel an den Ahnenfelsen. Entwickelt sich nicht."])],
)
c.line_of("Single", "Resovespa", [
    dict(name="Resonix", epithet="echolocans", cat="Echoflatter-Echo", arch="A05", size="S", h=0.35, types=("Sound",),
         habitat="Höhlen im Grollschlund", zones=Z(3), rarity="Uncommon", act="Nocturnal",
         traits=["Echolocator", "Flier", "Swarm"], niches=["Combat", "Field"], role="Speed", growth="Wave",
         polish="Speed:2", stats=("Speed", 460), bond=45, lure="ITM_LURE_BELLCHIME",
         sig="Ortungsruf: Klang-Angriff, enthüllt Ziele (Ausweichen ignorieren) für 1 Zug",
         mark="Riesige Ohren mit Ringmustern, die bei jedem Ruf aufleuchten",
         lore=["Ein Klang-Oberton, der die Welt durch Echos sieht.",
               "Lebt in Höhlenkolonien; orientiert sich mit Klicklauten, die Steine leise singen lassen.",
               "Die Klicks der Resonix sollen Geister aus Stollen vertreiben.",
               "Minenarbeiter lauschen Resonix, um Hohlräume im Gestein zu finden.",
               "Entwickelt sich nicht. Seine Rufe zeigen im Resonanzsinn Höhlenstrukturen."])],
)
c.line_of("Single", "Runosaxum", [
    dict(name="Runkar", epithet="inscriptus", cat="Runenstein-Echo", arch="A13", size="M", h=1.3, w=300, types=("Arcane", "Stone"),
         habitat="Alte Pässe mit Grenzsteinen", zones=Z(4, 5), rarity="Rare", conds=["Moon.NewMoon"], act="Nocturnal",
         traits=["Guardian", "Solitary", "Glowing"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:2", stats=("Control", 480), bond=30, lure="ITM_LURE_BELLCHIME",
         sig="Runenwechsel: ändert den Typ eines Gegners für 2 Züge in Stein",
         mark="Runen auf dem Körper ordnen sich bei jedem Atemzug neu",
         lore=["Ein Arkan-Oberton, der in uralten Grenzsteinen dorunischer Zeit erwachte.",
               "Steht reglos an Pässen; bei Neumond wandert es und schreibt Runen in den Schnee.",
               "Die Kharsk halten Runkars für Wächter alter Grenzen, die niemand mehr kennt.",
               "Akademie-Forschende versuchen seit Jahrzehnten, seine Runen zu entziffern.",
               "Wild nur bei Neumond. Entwickelt sich nicht."])],
)

c.write()
