#!/usr/bin/env python3
"""K25/K26 – Kreaturenkatalog: Ael'Dorun (R08), Kodex #179–#198."""
from catalog_lib import Catalog

c = Catalog(start_kodex=179, start_line=80, region="R08")
Z = lambda *n: [f"R08_Z{i:02d}" for i in n]

# L080 Schreiberling (Arkan, 3)
c.line_of("Three", "Scriptorius", [
    dict(name="Skriv", epithet="minimus", cat="Federkiel-Echo", arch="A04", size="S", h=0.4, types=("Arcane",),
         habitat="Archive und Lesesäle von Dorunsruh", zones=Z(1, 3), rarity="Common", act="Nocturnal",
         traits=["Collector", "Curious", "ToolUser"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:1", stats=("Caster", 305), evo="Level>=20", bond=55, lure="ITM_LURE_GLYPHTOKEN",
         sig="Glyphenkritzel: Arkan-Angriff, der eine zufällige Schwäche des Ziels enthüllt",
         mark="Ein Federkiel als Schopf, der beim Denken Tintenzeichen in die Luft schreibt",
         lore=["Ein Arkan-Oberton, der aus verblassten Schriftzeichen der Dorun-Archive entstand.",
               "Huscht nachts zwischen Regalen, ordnet Schriftrollen und kritzelt eigene Zeichen an die Wände.",
               "Ein Skriv, der eine Seite umblättert, zeigt dir, was du lesen sollst – sagen die Studenten.",
               "Die Akademie der Resonanz duldet Skrivs in den Archiven, obwohl sie manchmal Texte ‚verbessern‘.",
               "Ab Level 20 und Level 38 wächst er zum Glyphenmeister."]),
    dict(name="Skrivar", epithet="doctus", cat="Archivar-Echo", arch="A04", size="M", h=1.2, types=("Arcane",),
         habitat="Säulenfeld Thae'Luun", zones=Z(2, 3), rarity="Uncommon", act="Nocturnal",
         traits=["Collector", "ToolUser", "Solitary"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:2", stats=("Caster", 430), evo="Level>=38", bond=45, lure="ITM_LURE_GLYPHTOKEN",
         sig="Bannschrift: schreibt ein Zeichen auf das Ziel, das dessen nächste Fähigkeit verzögert",
         mark="Schwebende Glyphen umkreisen seine Hände wie Buchstaben auf einer Seite",
         lore=["Der heranwachsende Schreiber liest Säulen, die seit tausend Jahren niemand verstand.",
               "Wandert durch das Säulenfeld und kopiert Inschriften in Luftzeichen, die bis zum Morgen bleiben.",
               "Studenten folgen Skrivars heimlich, weil sie glauben, die Echos könnten die alte Schrift lesen.",
               "Rektorin Venn ließ Skrivar-Zeichen sammeln – ein Drittel davon entspricht echten Dorun-Glyphen.",
               "Ab Level 38 erreicht er die Endform."]),
    dict(name="Skriveth", epithet="magister", cat="Glyphenmeister-Echo", arch="A04", size="L", h=2.0, types=("Arcane", "Light"),
         habitat="Archontenviertel", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Collector", "Guardian", "Glowing"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:3", stats=("Caster", 525), bond=30, lure="ITM_LURE_GLYPHTOKEN",
         sig="Weltschrift: Crescendo – schreibt ein Feldzeichen: Arkan-Fähigkeiten aller Verbündeten +1 Stufe",
         mark="Ein Mantel aus leuchtenden Zeilen, die sich ständig neu schreiben",
         lore=["Die Endform der Schreiber trägt einen Mantel aus lebender Schrift.",
               "Steht in verlassenen Hörsälen und liest laut aus Büchern, die nicht mehr existieren.",
               "Man sagt, ein Skriveth kenne den letzten Satz, der vor der Großen Stille geschrieben wurde.",
               "Die Akademie verleiht den Titel ‚Glyphenleser‘ nur Wärtern mit einem Skriveth.",
               "Entsteht aus Skrivar ab Level 38."])],
)

# L081 Säulenwächter (Arkan → Geist, 3)
c.line_of("Three", "Columnaspectrum", [
    dict(name="Thaelit", epithet="lapideus", cat="Säulenfunke-Echo", arch="A13", size="S", h=0.5, types=("Arcane",),
         habitat="Säulenfeld Thae'Luun", zones=Z(2), rarity="Common", act="Diurnal",
         traits=["Guardian", "Glowing", "Sleepy"], niches=["Combat", "Research"], role="Tank", growth="Late",
         polish="SpDefense:1", stats=("Tank", 310), evo="Level>=20", bond=55, lure="ITM_LURE_TUNINGFORK",
         sig="Säulenschein: Barriere, die einen Arkan-Angriff absorbiert",
         mark="Ein Säulenkapitell als Kopf, in dessen Riefen Licht läuft",
         lore=["Ein Arkan-Oberton, der in einem abgebrochenen Säulenstück erwachte.",
               "Steht reglos zwischen den Säulen und leuchtet auf, wenn jemand eine Inschrift berührt.",
               "Pilger stellen Kerzen vor Thaelits, damit die Säulen ihre Gebete weitertragen.",
               "Akademie-Vermesser nutzen Thaelits als lebende Markierungspunkte im Säulenfeld.",
               "Ab Level 20 und Level 40 wächst er zum Säulenarchonten."]),
    dict(name="Thaelon", epithet="vigil", cat="Säulenwächter-Echo", arch="A13", size="M", h=1.5, types=("Spirit", "Arcane"),
         habitat="Säulenfeld und Archontenviertel", zones=Z(2, 3), rarity="Uncommon", act="Diurnal",
         traits=["Guardian", "Glowing", "Territorial"], niches=["Combat", "Research"], role="Tank", growth="Late",
         polish="SpDefense:2", stats=("Tank", 440), evo="Level>=40", bond=45, lure="ITM_LURE_TUNINGFORK",
         sig="Wächterpflicht: fängt Angriffe gegen Verbündete der Hinterreihe ab",
         mark="Eine geisterhafte Rüstung um einen Säulenkern",
         lore=["Der heranwachsende Wächter trägt die Erinnerung eines Dorun-Soldaten in sich.",
               "Patrouilliert festgelegte Wege zwischen den Säulen, als folge er einem alten Befehl.",
               "Die Dorunsruher sagen, Thaelons würden noch immer auf den Befehl warten, der sie entlässt.",
               "Die Akademie versucht, den alten Befehl in den Säuleninschriften zu finden.",
               "Ab Level 40 erreicht er die Endform."]),
    dict(name="Thaelarch", epithet="custos", cat="Säulenarchonten-Echo", arch="A13", size="L", h=2.8, types=("Spirit", "Metal"),
         habitat="Thronstadt", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Guardian", "Solitary", "Glowing"], niches=["Combat", "Research"], role="Tank", growth="Late",
         polish="SpDefense:3", stats=("Tank", 540), bond=30, lure="ITM_LURE_TUNINGFORK",
         sig="Archontenwall: Crescendo – die eigene Reihe ist 1 Zug unverwundbar gegen Geist und Arkan",
         mark="Eine Rüstung aus Bronze und Licht mit einem leeren Helm, aus dem ein Chor tönt",
         lore=["Die Endform der Säulenwächter trägt die Rüstung eines Archonten.",
               "Steht vor dem Thron von Ael'Dorun und lässt niemanden ohne Losung vorbei.",
               "Man sagt, ein Thaelarch habe vor tausend Jahren den letzten König beschützt – und versagt.",
               "Aevrin Thal erhielt seinen Thaelarch, nachdem er die Losung im Archiv fand.",
               "Entsteht aus Thaelon ab Level 40."])],
)

# L082 Uhrwerkkäfer (Metall, 3)
c.line_of("Three", "Horologidus", [
    dict(name="Tikkel", epithet="parvulus", cat="Zahnradkäfer-Echo", arch="A10", size="XS", h=0.15, types=("Metal",),
         habitat="Werkstätten der Vorstadt", zones=Z(1), rarity="Common", act="Diurnal",
         traits=["Collector", "ToolUser", "Curious"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="Speed:1", stats=("Control", 305), evo="Level>=18", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Taktschlag: verschiebt das Ziel auf der Zeitleiste um 50 nach hinten",
         mark="Ein Panzer mit sichtbaren Zahnrädern, die im Takt ticken",
         lore=["Ein Metall-Oberton aus dem Ticken alter Dorun-Uhrwerke.",
               "Sammelt Schräubchen und baut sie in den eigenen Panzer ein.",
               "Ein tickender Tikkel unter dem Kissen hilft beim Einschlafen, glauben die Kinder.",
               "Uhrmacher in Dorunsruh lassen Tikkels in ihre Werke kriechen, um sie zu reinigen.",
               "Ab Level 18 und Level 36 wächst er zum Zeitwerk."]),
    dict(name="Tikkar", epithet="mechanicus", cat="Uhrwerk-Echo", arch="A10", size="S", h=0.6, types=("Metal", "Arcane"),
         habitat="Ruinen des Archontenviertels", zones=Z(1, 3), rarity="Uncommon", act="Diurnal",
         traits=["ToolUser", "Collector", "Territorial"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="Speed:2", stats=("Control", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_ORECRUMBS",
         sig="Aufziehen: eigener nächster Zug kommt sofort",
         mark="Ein Schlüssel auf dem Rücken, der sich von selbst dreht",
         lore=["Der heranwachsende Käfer zieht sich selbst auf – und manchmal andere.",
               "Repariert verfallene Mechanismen in den Ruinen, ohne zu wissen, wozu sie dienen.",
               "Wenn eine Ruine plötzlich tickt, hat ein Tikkar sie repariert.",
               "Die Akademie fand Türen, die Tikkars nach tausend Jahren wieder öffneten.",
               "Ab Level 36 erreicht er die Endform."]),
    dict(name="Tikkoran", epithet="temporalis", cat="Zeitwerk-Echo", arch="A10", size="M", h=1.3, types=("Metal", "Gravity"),
         habitat="Thronstadt", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["ToolUser", "Guardian", "Solitary"], niches=["Combat", "Research"], role="Control", growth="Steady",
         polish="Speed:3", stats=("Control", 525), bond=30, lure="ITM_FOOD_ORECRUMBS",
         sig="Zeitbremse: Crescendo – alle Gegner rücken auf der Zeitleiste um 300 nach hinten",
         mark="Ein Pendel unter dem Körper, das die Luft um sich verlangsamt",
         lore=["Die Endform der Uhrwerkkäfer lässt die Zeit um sich langsamer ticken.",
               "Bewacht die große Uhr der Thronstadt, die seit der Großen Stille stillsteht.",
               "Die Dorunsruher sagen: Wenn ein Tikkoran die große Uhr wieder in Gang setzt, endet die Stille.",
               "Die Akademie erforscht, ob Tikkorans Schwerkraft nutzen, um Bewegungen zu verlangsamen.",
               "Entsteht aus Tikkar ab Level 36."])],
)

# L083 Grabwächter (Geist, 3) – Bodenreittier
c.line_of("Three", "Sarcophagion", [
    dict(name="Sarkel", epithet="catulus", cat="Grabjunges-Echo", arch="A02", size="M", h=0.9, types=("Spirit",),
         habitat="Grabkammern unter dem Archontenviertel", zones=Z(3), rarity="Uncommon", act="Nocturnal",
         traits=["Guardian", "Shy", "Glowing"], niches=["Combat", "Mount"], role="Striker", growth="Late",
         polish="Attack:1", stats=("Striker", 310), evo="Level>=24", bond=50, lure="ITM_LURE_LANTERN",
         sig="Grabesbiss: Geist-Angriff, heilt den Anwender um 25 % des Schadens",
         mark="Eine Steinmaske vor dem Gesicht, hinter der zwei Lichtpunkte glühen",
         lore=["Ein Geist-Oberton, der in den Grabkammern der Dorun-Fürsten erwachte.",
               "Wacht über Sarkophage und folgt Lichtquellen neugierig, aber vorsichtig.",
               "Wer einem Sarkel ein Licht schenkt, darf ein Grab betreten, sagen Grabräuber – und lügen oft.",
               "Die Akademie heuert Wärter mit Sarkels an, um Grabkammern sicher zu erforschen.",
               "Ab Level 24 trägt er Reiter, ab Level 42 bei Neumond wird er zum Grabfürsten."]),
    dict(name="Sarkon", epithet="vigilans", cat="Grabwächter-Echo", arch="A02", size="L", h=2.0, types=("Spirit", "Stone"),
         habitat="Grabkammern und Säulenfeld", zones=Z(2, 3), rarity="Rare", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Guardian", "Territorial", "Glowing"], niches=["Combat", "Mount"], role="Striker", mount="Ground",
         growth="Late", polish="Attack:2", stats=("Striker", 440), evo="Level>=42 & Moon=NewMoon", bond=40,
         lure="ITM_LURE_LANTERN", sig="Grabwacht: greift jeden Gegner an, der einen Verbündeten trifft",
         mark="Ein steinerner Löwenkörper mit Geisterflammen als Mähne",
         lore=["Der ausgewachsene Grabwächter trägt einen steinernen Leib und eine Mähne aus Geisterlicht.",
               "Wandert nachts zwischen den Säulen und vertreibt alle, die Gräber stören.",
               "Die alten Lieder sagen, die Fürsten von Ael'Dorun ritten Sarkons in die Schlacht.",
               "Ein Sarkon als Reittier ist in Dorunsruh ein Zeichen, dass die Ahnen dich akzeptieren.",
               "Trägt Reiter. Wild nur nachts. Entwickelt sich ab Level 42 bei Neumond."]),
    dict(name="Sarkothar", epithet="princeps", cat="Grabfürsten-Echo", arch="A02", size="XL", h=3.4, types=("Spirit", "Arcane"),
         habitat="Fürstengruft der Thronstadt", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Guardian", "Solitary", "Glowing"], niches=["Combat", "Mount"], role="Striker", mount="Ground",
         growth="Late", polish="Attack:3", stats=("Striker", 540), bond=30, lure="ITM_LURE_LANTERN",
         sig="Fürstenurteil: Crescendo – trifft den stärksten Gegner, Schaden steigt mit dessen Basiswerten",
         mark="Eine Krone aus Geisterflammen und ein Siegel auf der Stirn",
         lore=["Die Endform der Grabwächter trägt die Krone eines vergessenen Fürsten.",
               "Schläft in der Fürstengruft und erwacht nur bei Neumond, um seine Wache abzuschreiten.",
               "Man sagt, Sarkothar kenne die Namen aller, die in Ael'Dorun begraben liegen.",
               "Die Akademie hält das Siegel auf Sarkothars Stirn für das Wappen des letzten Königshauses.",
               "Trägt Reiter. Entsteht aus Sarkon ab Level 42 bei Neumond."])],
)

# L084 Tintenfresser (Leere, 2)
c.line_of("Two", "Atramentivorus", [
    dict(name="Tilgel", epithet="edax", cat="Tintenfresser-Echo", arch="A17", size="S", h=0.4, types=("Void",),
         habitat="Verfallene Archive", zones=Z(1, 3), rarity="Uncommon", act="Nocturnal",
         traits=["Scavenger", "Camouflaged", "Shy"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:1", stats=("Control", 345), evo="Level>=30", bond=45, lure="ITM_LURE_GLYPHTOKEN",
         sig="Tilgung: löscht eine erlernte Fähigkeit des Ziels für 2 Züge",
         mark="Saugnäpfe, die Tinte aus Papier ziehen und blasse Seiten zurücklassen",
         lore=["Ein Leere-Oberton, der sich von verblassenden Worten ernährt.",
               "Kriecht durch Archive und saugt Tinte aus Schriftrollen; lässt leere Seiten zurück.",
               "Archivare sagen: Was ein Tilgel gefressen hat, hat die Welt vergessen.",
               "Die Akademie bekämpft Tilgels in den Archiven – der Orden der Stille züchtet sie heimlich.",
               "Ab Level 30 wächst er."]),
    dict(name="Tilgrath", epithet="oblivionis", cat="Vergessens-Echo", arch="A17", size="M", h=1.4, types=("Void", "Arcane"),
         habitat="Versiegelte Bibliothek der Thronstadt", zones=Z(4), rarity="Rare", conds=["TimeOfDay.Night"],
         act="Nocturnal", traits=["Scavenger", "Solitary", "Camouflaged"], niches=["Combat", "Research"],
         role="Control", growth="Wave", polish="SpAttack:2", stats=("Control", 500), bond=30,
         lure="ITM_LURE_GLYPHTOKEN", sig="Großes Vergessen: alle Gegner verlieren ihre Werteveränderungen",
         mark="Tentakel aus schwarzer Leere, über die blasse Buchstaben laufen und verschwinden",
         lore=["Ein Tintenfresser, der genug Worte verschlang, kann Erinnerungen löschen.",
               "Lebt in der versiegelten Bibliothek und frisst Bücher, deren Inhalt zu gefährlich ist.",
               "Manche glauben, Tilgraths hätten die Geschichte der Großen Stille absichtlich gelöscht.",
               "Sereth Vaun nennt Tilgraths ‚die Gnädigen‘ – sie nehmen, was niemand wissen sollte.",
               "Wild nur nachts. Entwickelt sich nicht weiter."])],
)

# L085 Säulenlilie (Klang, 2)
c.line_of("Two", "Hymnolilium", [
    dict(name="Hymlit", epithet="cantans", cat="Säulenlilien-Echo", arch="A14", size="XS", h=0.25, types=("Sound",),
         habitat="Ritzen im Säulenfeld", zones=Z(2), rarity="Common", act="Diurnal",
         traits=["Singer", "Pollinator", "Sunbather"], niches=["Combat", "Research"], role="Support", growth="Swift",
         polish="SpDefense:1", stats=("Support", 345), evo="Level>=26 & BondTier>=3", bond=60, lure="ITM_LURE_TUNINGFORK",
         sig="Morgenhymne: Verbündete erhalten Harmonie +5 und heilen leicht",
         mark="Glockenförmige Blüten, die beim Öffnen einen reinen Ton erzeugen",
         lore=["Ein Klang-Oberton, der zwischen alten Säulen zu blühen gelernt hat.",
               "Öffnet bei Sonnenaufgang seine Blüten und singt einen einzelnen, reinen Ton.",
               "Die Dorunsruher sagen, die Säulen hätten einst gesungen – jetzt singen die Hymlits für sie.",
               "Musikstudenten der Akademie stimmen ihre Instrumente nach dem Ton der Hymlits.",
               "Ab Level 26 bei hoher Bindung wächst sie."]),
    dict(name="Hymnora", epithet="chorialis", cat="Chorlilien-Echo", arch="A14", size="S", h=0.75, types=("Sound", "Spirit"),
         habitat="Säulenfeld Thae'Luun bei Sonnenaufgang", zones=Z(2), rarity="Uncommon", act="Diurnal",
         traits=["Singer", "Pollinator", "Guardian"], niches=["Combat", "Research"], role="Support", growth="Swift",
         polish="SpDefense:2", stats=("Support", 495), bond=45, lure="ITM_LURE_TUNINGFORK",
         sig="Chorblüte: heilt alle Verbündeten, entfernt einen negativen Status",
         mark="Ein Kranz aus Blüten, die mehrstimmig singen",
         lore=["Eine Säulenlilie, die die Bindung ihres Wärters spürt, singt mit vielen Stimmen.",
               "Bildet Kränze um Säulenbasen; ihr Chor ist bei Sonnenaufgang im ganzen Feld zu hören.",
               "Hochzeiten in Dorunsruh finden bei Sonnenaufgang im Säulenfeld statt – wegen der Hymnoras.",
               "Die Akademie hat die Hymnora-Akkorde als Grundlage für Resonanzstimmgabeln übernommen.",
               "Entwickelt sich nicht weiter."])],
)

# L086 Lichtlinse (Licht → Schwerkraft, 2)
c.line_of("Two", "Gravilens", [
    dict(name="Optil", epithet="vitreus", cat="Linsen-Echo", arch="A13", size="S", h=0.4, types=("Light",),
         habitat="Sternwartenruinen der Vorstadt", zones=Z(1), rarity="Uncommon", act="Nocturnal",
         traits=["Stargazer", "Curious", "Glowing"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=32 & TimeOfDay=Night", bond=50, lure="ITM_LURE_STARCHIME",
         sig="Brennglas: Licht-Angriff, kritisch bei Sonnenwetter",
         mark="Ein Körper aus geschliffener Linse, der Sternenlicht bündelt",
         lore=["Ein Licht-Oberton aus den Linsen alter Dorun-Teleskope.",
               "Starrt nachts in den Himmel und wandert tagsüber Sonnenflecken nach.",
               "Kinder halten Optils hoch, um durch sie die Sterne näher zu sehen.",
               "Die Akademie restauriert ihr Observatorium mit Optil-Hilfe.",
               "Ab Level 32 nachts wächst es zur Schwerelinse."]),
    dict(name="Optikor", epithet="curvans", cat="Schwerelinsen-Echo", arch="A13", size="M", h=1.3, types=("Gravity", "Light"),
         habitat="Observatorium der Thronstadt", zones=Z(4), rarity="Rare", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Stargazer", "Solitary", "Glowing"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:2", stats=("Caster", 495), bond=35, lure="ITM_LURE_STARCHIME",
         sig="Lichtbeugung: lenkt den nächsten Licht- oder Schwerkraft-Angriff auf ein beliebiges Ziel",
         mark="Eine Linse, um die Licht sichtbar gebogen wird",
         lore=["Eine Linse, die zu viele Sterne sah, beugt das Licht mit eigener Schwere.",
               "Schwebt nachts im Observatorium; Sterne erscheinen in ihr verzerrt und vervielfacht.",
               "Die Alten sagen, Optikors können zeigen, wo die Stimmen der Sterne wohnen.",
               "Die Akademie benutzt Optikor-Beobachtungen zur Bestimmung der Mondphasen-Resonanz.",
               "Wild nur nachts. Entwickelt sich nicht weiter."])],
)

# Einzelarten
c.line_of("Single", "Menhirion", [
    dict(name="Menhirok", epithet="erectus", cat="Menhir-Echo", arch="A13", size="L", h=2.6, types=("Stone", "Arcane"),
         habitat="Steinkreise der Vorstadt", zones=Z(1, 2), rarity="Rare", conds=["Moon.FullMoon"], act="Nocturnal",
         traits=["Guardian", "Sleepy", "Stargazer"], niches=["Combat", "Research"], role="Tank", growth="Late",
         polish="Defense:2", stats=("Tank", 490), bond=30, lure="ITM_LURE_TUNINGFORK",
         sig="Steinkreis: Verbündete in Formation erhalten +1 VER und SVE",
         mark="Ein Monolith mit Rillen, in denen bei Vollmond Licht fließt",
         lore=["Ein Stein-Oberton, der aus einem der alten Steinkreise erwachte.",
               "Steht monatelang still und wandert nur bei Vollmond zu einem anderen Kreis.",
               "Wer einen Menhirok wandern sieht, soll sich nicht umdrehen – sonst bleibt er stehen.",
               "Die Akademie kartiert die Wanderungen der Menhiroks als Hinweis auf alte Kraftlinien.",
               "Wild nur bei Vollmond. Entwickelt sich nicht."])],
)
c.line_of("Single", "Regalisvox", [
    dict(name="Kronvaal", epithet="rex", cat="Thronhüter-Echo", arch="A04", size="L", h=2.2, types=("Arcane", "Metal"),
         habitat="Thronsaal von Ael'Dorun", zones=Z(4), rarity="VeryRare", conds=["Moon.NewMoon", "TimeOfDay.Night"],
         act="Nocturnal", traits=["Guardian", "Solitary", "Singer"], niches=["Combat", "Research"], role="Caster",
         growth="Late", polish="SpAttack:2", stats=("Caster", 500), bond=20, lure="ITM_LURE_GLYPHTOKEN",
         sig="Königsdekret: Gegner können 1 Zug lang nur angreifen, nicht unterstützen",
         mark="Ein Gewand aus Bronzeplatten und eine leere Krone, die über dem Kopf schwebt",
         lore=["Ein Arkan-Oberton, der aus dem letzten Befehl des letzten Königs von Ael'Dorun entstand.",
               "Sitzt in Neumondnächten auf dem leeren Thron und spricht Dekrete in einer toten Sprache.",
               "Die Dorunsruher glauben, Kronvaal warte auf einen würdigen Erben.",
               "Rektorin Venn hält den Kronvaal für den Schlüssel zur Frage, warum Ael'Dorun fiel.",
               "Wild nur in Neumondnächten. Entwickelt sich nicht."])],
)

c.write()
