#!/usr/bin/env python3
"""K22/K23 – Kreaturenkatalog: Saltrand (R06), Kodex #085–#110."""
from catalog_lib import Catalog

c = Catalog(start_kodex=85, start_line=38, region="R06")
Z = lambda *n: [f"R06_Z{i:02d}" for i in n]

# L038 Mantarochen (Flut → Flut/Sturm) – Schwimm- und Flugreittier
c.line_of("Three", "Marimanta", [
    dict(name="Marlit", epithet="planus", cat="Rochenkind-Echo", arch="A06", size="M", h=0.85, w=20, types=("Tide",),
         habitat="Flache Buchten und Tangwälder", zones=Z(2, 5), rarity="Common", act="Diurnal",
         traits=["Swimmer", "Playful", "Filterer"], niches=["Combat", "Mount"], role="Speed", growth="Steady",
         polish="Speed:1", stats=("Speed", 310), evo="Level>=20", bond=55, lure="ITM_FOOD_KELPSNACK",
         sig="Wellenschlag: Flut-Angriff, eigene nächste Aktion schneller",
         mark="Zwei Leuchtbögen auf den Flossen, die beim Gleiten wellenförmig blinken",
         lore=["Ein Oberton der Brandung, ein Hauch von Thal'assyrs Atem in kleiner Gestalt.",
               "Gleitet durch Tangwälder, filtert Plankton und springt bei Freude aus dem Wasser.",
               "Ein springender Marlit vor dem Bug verspricht gute Fahrt.",
               "Fischerkinder in Tangwerft schwimmen mit Marlits um die Wette.",
               "Ab Level 20 groß genug, um Schwimmer zu ziehen."]),
    dict(name="Marwyn", epithet="velifer", cat="Segelrochen-Echo", arch="A06", size="M", h=1.5, w=120, types=("Tide",),
         habitat="Offene Bucht und Riffgrund", zones=Z(5), rarity="Uncommon", act="Diurnal",
         traits=["Swimmer", "Migratory", "Playful"], niches=["Combat", "Mount"], role="Speed", mount="Swim",
         growth="Steady", polish="Speed:2", stats=("Speed", 430), evo="Level>=36 & Weather=Thunderstorm", bond=45,
         lure="ITM_FOOD_KELPSNACK", sig="Gischtsprung: Angriff aus dem Sprung, ignoriert Formation",
         mark="Flossenränder leuchten wie Segelsäume",
         lore=["Der heranwachsende Rochen trägt Flossen wie Segel.",
               "Zieht mit den Gezeiten; bei Sturm springt er meterhoch über die Wellen.",
               "Seeleute nennen springende Marwyns die Segel der Stimme.",
               "Schnellstes Schwimmreittier der Küste; Kontor-Boten nutzen es zwischen den Dörfern.",
               "Trägt Schwimmer. Entwickelt sich ab Level 36 nur im Gewitter."]),
    dict(name="Maraune", epithet="caelestis", cat="Himmelsrochen-Echo", arch="A06", size="XL", h=4.5, w=1500,
         types=("Tide", "Storm"), habitat="Über dem Meer bei Sturm", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Diurnal", traits=["Flier", "Swimmer", "Migratory"], niches=["Combat", "Mount"], role="Speed", mount="Fly",
         growth="Steady", polish="Speed:3", stats=("Speed", 530), bond=30, lure="ITM_FOOD_KELPSNACK",
         sig="Sturmflut: Crescendo – trifft alle Gegner und spült die Hinterreihe nach vorn",
         mark="Riesige Flossen mit Wellenlinien aus Licht, die im Flug pulsieren",
         lore=["Die Endform der Rochenlinie fliegt durch Stürme, als wären sie Wasser.",
               "Gleitet über Gewitterwolken und taucht ins Meer, wenn der Sturm vorbei ist.",
               "Der Gezeitenkult sieht im Maraune ein Kind Thal'assyrs.",
               "Wer auf einem Maraune reitet, kann Meer und Himmel gleichermaßen bereisen.",
               "Trägt Reiter durch die Luft. Entsteht aus Marwyn im Gewitter ab Level 36."])],
)

# L039 Krake (Flut, 3) – Schwimmreittier
c.line_of("Three", "Tideoctopus", [
    dict(name="Tidling", epithet="curiosus", cat="Gezeitenkraken-Echo", arch="A17", size="S", h=0.4, types=("Tide",),
         habitat="Gezeitenbecken", zones=Z(1, 2), rarity="Common", act="Crepuscular",
         traits=["Curious", "ToolUser", "Camouflaged"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="SpDefense:1", stats=("Control", 305), evo="Level>=18", bond=55, lure="ITM_FOOD_SHELLMEAT",
         sig="Tintenstoß: Flut-Angriff, Präzision des Ziels −1",
         mark="Farbwechselnde Haut; das Klangmal erscheint als Punktmuster bei Aufregung",
         lore=["Ein neugieriger Oberton der Gezeitenbecken.",
               "Erkundet Becken bei Ebbe, öffnet Muscheln mit Steinen, wechselt die Farbe.",
               "Ein Tidling, der dir eine Muschel bringt, möchte Freundschaft schließen.",
               "Kinder in Möwenhuk bringen Tidlingen Rätsel aus Muscheln bei.",
               "Ab Level 18 und Level 34 wächst es heran."]),
    dict(name="Tidel", epithet="sagax", cat="Riffkraken-Echo", arch="A17", size="M", h=1.2, types=("Tide",),
         habitat="Riffgrund und Hafenbecken", zones=Z(5), rarity="Uncommon", act="Crepuscular",
         traits=["ToolUser", "Collector", "Camouflaged"], niches=["Combat", "Mount"], role="Control", mount="Swim",
         growth="Steady", polish="SpDefense:2", stats=("Control", 430), evo="Level>=34", bond=45, lure="ITM_FOOD_SHELLMEAT",
         sig="Riffgriff: hält ein Ziel fest und spült es in die andere Reihe",
         mark="Saugnäpfe leuchten nacheinander auf wie Lauflichter",
         lore=["Ein heranwachsender Krake, der Riffe mit gesammelten Schätzen schmückt.",
               "Baut Höhlen aus Muscheln und Wrackteilen; versteht einfache Zeichen.",
               "Taucher erzählen, Tidels hätten ihnen verlorene Werkzeuge zurückgebracht.",
               "Hauke, der Taucher, arbeitet mit einem Tidel – angeblich klüger als seine Lehrlinge.",
               "Trägt Schwimmer. Ab Level 34 erreicht es die Endform."]),
    dict(name="Tidrex", epithet="abyssalis", cat="Tiefenkraken-Echo", arch="A17", size="L", h=2.8, types=("Tide", "Arcane"),
         habitat="Tiefe vor Saltrand-Hafen", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["ToolUser", "Solitary", "Guardian"], niches=["Combat", "Mount"], role="Control", mount="Swim",
         growth="Steady", polish="SpAttack:3", stats=("Control", 525), bond=30, lure="ITM_FOOD_SHELLMEAT",
         sig="Tiefsog: Crescendo – zieht alle Gegner in die Vorderreihe und verlangsamt sie",
         mark="Arme mit Mustern, die an dorunische Glyphen erinnern",
         lore=["Die Endform der Kraken lebt in der Tiefe, nahe der Grotte Thal'assyrs.",
               "Bewacht Wracks; seine Armmuster ähneln Zeichen, die niemand mehr lesen kann.",
               "Seeleute glauben, ein Tidrex bewache den Schlaf der Meeresstimme.",
               "Die Akademie versucht, Tidrex-Muster mit Glyphen aus Ael'Dorun zu vergleichen.",
               "Trägt Schwimmer. Entsteht aus Tidel ab Level 34."])],
)

# L040 Seevogel (Sturm, 3) – Flugreittier
c.line_of("Three", "Pelagornis", [
    dict(name="Brikin", epithet="clamans", cat="Möwenkind-Echo", arch="A05", size="XS", h=0.28, types=("Storm",),
         habitat="Klippen, Häfen, Dünen", zones=Z(1, 3, 4), rarity="Common", act="Diurnal",
         traits=["Flier", "Scavenger", "Curious"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 305), evo="Level>=18", bond=55, lure="ITM_FOOD_SMOKEDFISH",
         sig="Sturzschrei: Angriff, der Harmonie +5 erzeugt",
         mark="Weiße Schwungfedern mit leuchtendem Band",
         lore=["Ein lauter Oberton des Hafenwinds.",
               "Bettelt an Kais, klaut Fisch, segelt mit den Böen über Klippen.",
               "Ein Brikin auf dem Mast bringt gutes Wetter, einer auf dem Deck Ärger.",
               "Saltrand-Hafen ist voller Brikins; Händler schützen ihre Stände mit Netzen.",
               "Ab Level 18 und 36 wächst er zum Sturmsegler."]),
    dict(name="Brisel", epithet="procellarius", cat="Sturmsegler-Echo", arch="A05", size="S", h=0.75, types=("Storm", "Tide"),
         habitat="Leuchtfelsen, offene See", zones=Z(3, 4), rarity="Uncommon", act="Diurnal",
         traits=["Flier", "Migratory", "Hunter"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_SMOKEDFISH",
         sig="Gischtpfeil: Mehrfachtreffer bei Regen und Gewitter stärker",
         mark="Flügelbänder ziehen leuchtende Linien in die Luft",
         lore=["Der heranwachsende Seevogel liebt Stürme.",
               "Segelt tagelang ohne Flügelschlag über Wellenkämmen.",
               "Erscheinen viele Brisels an Land, zieht ein schwerer Sturm auf.",
               "Leuchtturmwärterin Gesa zählt Brisels, um Stürme vorherzusagen.",
               "Ab Level 36 erreicht er die Endform."]),
    dict(name="Brision", epithet="regalis", cat="Albatros-Echo", arch="A05", size="L", h=2.0, types=("Storm", "Tide"),
         habitat="Über dem offenen Meer", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Flier", "Migratory", "Solitary"], niches=["Combat", "Mount"], role="Speed", mount="Fly", growth="Swift",
         polish="Speed:3", stats=("Speed", 530), bond=30, lure="ITM_FOOD_SMOKEDFISH",
         sig="Weltumsegler: Crescendo – alle Verbündeten handeln sofort hintereinander (Zeitleiste)",
         mark="Spannweite mit Klangmal-Bändern, die im Gegenwind singen",
         lore=["Die Endform der Seevögel umsegelt ganz Aethris.",
               "Landet selten; schläft im Gleitflug über den Wellen.",
               "Der Albatros-Echo gilt als Seele treuer Seeleute.",
               "Ein Brision als Reittier ist der Stolz jedes Kontor-Kuriers.",
               "Trägt Reiter durch die Luft. Entsteht aus Brisel ab Level 36."])],
)

# L041 Laternenfisch (Flut, 3) + Zweig (Arkan)
c.line_of("Three", "Lanternichthys", [
    dict(name="Aquapip", epithet="lucens", cat="Leuchtfischchen-Echo", arch="A08", size="XS", h=0.15, types=("Tide",),
         habitat="Riff und Hafenbecken nachts", zones=Z(2, 5), rarity="Common", act="Nocturnal",
         traits=["Swarm", "Glowing", "Swimmer"], niches=["Combat", "Research"], role="Caster", growth="Swift",
         polish="SpAttack:1", stats=("Caster", 300), evo="Level>=16", bond=60, lure="ITM_FOOD_KELPSNACK",
         sig="Leuchtschwarm: Flut-Angriff, blendet",
         mark="Leuchtorgan am Kopf, Schwärme pulsieren synchron",
         lore=["Ein winziger Oberton, der nachts das Riff erleuchtet.",
               "Lebt in Schwärmen; die Lichter blinken im Gleichtakt.",
               "Nachts im Hafen sagen Leute, die Sterne seien ins Wasser gefallen.",
               "Taucher folgen Aquapip-Schwärmen zu Muschelbänken.",
               "Ab Level 16 und Level 32 wächst er heran; in der Tiefe bei Neumond entsteht eine andere Form."]),
    dict(name="Aquafin", epithet="lanterna", cat="Laternenfisch-Echo", arch="A08", size="S", h=0.6, types=("Tide", "Light"),
         habitat="Riffgrund", zones=Z(5), rarity="Uncommon", act="Nocturnal",
         traits=["Glowing", "Ambusher", "Swimmer"], niches=["Combat", "Research"], role="Caster", growth="Swift",
         polish="SpAttack:2", stats=("Caster", 425), evo="Level>=32", bond=45, lure="ITM_FOOD_KELPSNACK",
         sig="Köderlicht: lockt einen Gegner in die Vorderreihe",
         mark="Lange Angel mit Leuchtkugel, die das Klangmal trägt",
         lore=["Der heranwachsende Fisch trägt eine Laterne an einer Angel.",
               "Lockt Beute mit seinem Licht und schnappt zu.",
               "Die Laterne eines Aquafin zeigt Ertrinkenden den Weg nach oben, sagt der Gezeitenkult.",
               "Taucher nutzen gezähmte Aquafins als lebende Lampen.",
               "Ab Level 32 Endform; in der Tiefe bei Neumond Zweigform."]),
    dict(name="Aquadral", epithet="profundus", cat="Tiefenlaternen-Echo", arch="A08", size="L", h=2.0, types=("Tide", "Light"),
         habitat="Tiefe Grotten", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Glowing", "Solitary", "Ambusher"], niches=["Combat", "Mount"], role="Caster", mount="Swim", growth="Swift",
         polish="SpAttack:3", stats=("Caster", 520), bond=30, lure="ITM_FOOD_KELPSNACK",
         sig="Tiefenleuchten: Crescendo – trifft alle Gegner, enthüllt sie (Ausweichen ignoriert) 2 Züge",
         mark="Dutzende Leuchtpunkte wie ein Sternbild auf dem Körper",
         lore=["Die Endform der Laternenfische leuchtet wie ein versunkenes Sternbild.",
               "Lebt in Grotten, in denen nie Licht fiel – außer seinem eigenen.",
               "Die Grotte Thal'assyrs soll von Aquadrals beleuchtet werden.",
               "Taucher-Legenden erzählen von einem Riesenfisch, der ihnen den Weg aus der Tiefe wies.",
               "Trägt Schwimmer. Entsteht aus Aquafin ab Level 32."])],
    branch=dict(name="Mystdral", epithet="arcanus", cat="Glyphenfisch-Echo", arch="A08", size="L", h=1.9,
                types=("Arcane", "Tide"), habitat="Tiefseegrotte bei Neumond", zones=[], rarity="VeryRare",
                conds=["Spawn.None"], act="Nocturnal", traits=["Glowing", "Solitary", "Collector"],
                niches=["Combat", "Research"], role="Control", growth="Swift", polish="SpAttack:3",
                stats=("Control", 520), bond=25, lure="ITM_LURE_GLYPHTOKEN",
                evo_from_prev="Level>=32 & Moon=NewMoon & Zone=R06_Z05",
                sig="Glyphenlicht: ändert den Typ eines Gegners für 2 Züge in Flut",
                mark="Leuchtpunkte formen dorunische Zeichen, die sich verschieben",
                lore=["Ein Aquafin, das in Neumondnächten in der Tiefe wächst, nimmt fremde Muster an.",
                      "Seine Lichter schreiben Zeichen ins Wasser, die sich wie Sätze aneinanderreihen.",
                      "Der Gezeitenkult nennt es den Schreiber der Tiefe.",
                      "Die Akademie zahlt jedem Taucher, der einen Mystdral fotografiert.",
                      "Entsteht aus Aquafin ab Level 32 bei Neumond im Riffgrund."]),
)

# L042 Windqualle (Sturm, 2)
c.line_of("Two", "Aeromedusa", [
    dict(name="Aerlet", epithet="vagans", cat="Windquallen-Echo", arch="A12", size="XS", h=0.25, w=0.1, types=("Storm",),
         habitat="Über Dünen und Wellen", zones=Z(1, 3), rarity="Common", act="Diurnal",
         traits=["Drifter", "Flier", "Glowing"], niches=["Combat"], role="Control", growth="Swift",
         polish="SpDefense:1", stats=("Control", 340), evo="Level>=24", bond=55, lure="ITM_LURE_WINDCHIME",
         sig="Nesselwind: Sturm-Angriff mit Chance auf Verlangsamung",
         mark="Durchsichtiger Schirm mit pulsierendem Ring",
         lore=["Ein Oberton, der zwischen Luft und Wasser nicht unterscheidet.",
               "Treibt im Wind wie eine Qualle im Meer; landet bei Flaute auf dem Sand.",
               "Kinder lassen Aerlets wie Drachen steigen – an einem Faden aus Tang.",
               "Fischer lesen an Aerlet-Schwärmen die Windrichtung ab.",
               "Ab Level 24 wächst der Schirm."]),
    dict(name="Aerluna", epithet="tempestiva", cat="Sturmquallen-Echo", arch="A12", size="S", h=0.75, w=0.8, types=("Storm", "Light"),
         habitat="Klippen bei Gewitter", zones=Z(3, 4), rarity="Rare", conds=["Weather.Thunderstorm"], act="Diurnal",
         traits=["Drifter", "Flier", "Glowing"], niches=["Combat"], role="Control", growth="Swift",
         polish="SpDefense:2", stats=("Control", 490), bond=40, lure="ITM_LURE_WINDCHIME",
         sig="Blitzschirm: lädt sich im Gewitter auf, entlädt auf alle Gegner",
         mark="Tentakel aus Licht, die bei Blitzen aufleuchten",
         lore=["Eine Windqualle, die im Gewitter wuchs, trägt Blitze in ihren Fäden.",
               "Erscheint nur bei Gewittern über den Klippen; leuchtet im Takt der Blitze.",
               "Seeleute glauben, Aerlunas leiten Blitze vom Schiff weg.",
               "Leuchtturmwärter berichten, Aerlunas schwebten bei Sturm um ihr Licht.",
               "Wild nur bei Gewitter."])],
)

# L043 Strandschildkröte (Stein, 2) – Bodenreittier
c.line_of("Two", "Litorochelys", [
    dict(name="Stonlet", epithet="arenaria", cat="Sandpanzer-Echo", arch="A11", size="S", h=0.35, w=10, types=("Stone",),
         habitat="Dünenküste", zones=Z(1), rarity="Common", act="Diurnal",
         traits=["Burrower", "Sunbather", "Migratory"], niches=["Combat", "Breeding"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 340), evo="Level>=26", bond=55, lure="ITM_FOOD_KELPSNACK",
         sig="Sandgrube: gräbt sich ein (Verteidigung +2, nächster Angriff stärker)",
         mark="Panzer mit Muster aus Sandkörnern, das bei Sonne glitzert",
         lore=["Ein Oberton von Stein und Sand, der an den Stränden schlüpft.",
               "Vergräbt sich im Sand; Jungtiere wandern bei Vollmond ins Meer.",
               "Wer schlüpfenden Stonlets ans Meer hilft, hat ein Jahr lang Glück.",
               "Die Wildwacht schützt Nistplätze an der Dünenküste.",
               "Ab Level 26 wird der Panzer tragfähig."]),
    dict(name="Stonshell", epithet="vectrix", cat="Strandpanzer-Echo", arch="A11", size="L", h=1.7, w=550, types=("Stone", "Tide"),
         habitat="Strände und Watt", zones=Z(1, 2), rarity="Uncommon", act="Diurnal",
         traits=["Migratory", "Sunbather", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Late", polish="Defense:2", stats=("Tank", 500), bond=45, lure="ITM_FOOD_KELPSNACK",
         sig="Wattpanzer: Schild für die Reihe, Flut-Schaden halbiert",
         mark="Riesiger Panzer mit Muscheln, die das Klangmal säumen",
         lore=["Eine ausgewachsene Strandschildkröte trägt Muscheln und Seepocken auf dem Rücken.",
               "Wandert zwischen Stränden, schwimmt lange Strecken und legt Eier in Dünen.",
               "Fischer sagen, Stonshells kennen jeden Strand Aethris'.",
               "Beliebtes Reittier im Watt – trittsicher bei Ebbe.",
               "Trägt Reiter (Bodenreiten). Entsteht aus Stonlet ab Level 26."])],
)

# L044 Leuchtgarnele (Licht, 2)
c.line_of("Two", "Glimmacaris", [
    dict(name="Glimkin", epithet="saliens", cat="Leuchtgarnelen-Echo", arch="A10", size="XS", h=0.12, types=("Light",),
         habitat="Gezeitenbecken und Algen", zones=Z(1, 2), rarity="Common", act="Nocturnal",
         traits=["Glowing", "Swarm", "Filterer"], niches=["Combat", "Research"], role="Support", growth="Swift",
         polish="SpDefense:1", stats=("Support", 335), evo="Level>=22", bond=60, lure="ITM_FOOD_KELPSNACK",
         sig="Lichtpuls: reinigt einen Verbündeten und heilt leicht",
         mark="Der ganze Körper glimmt in Wellen",
         lore=["Ein kleiner Licht-Oberton, der die Gezeitenbecken nachts erhellt.",
               "Lebt in Schwärmen in Becken; springt bei Berührung leuchtend davon.",
               "Wenn die Becken leuchten, sagen die Alten, lacht das Meer.",
               "Kinder fangen Glimkins zum Spielen; die Wildwacht bittet, sie zurückzusetzen.",
               "Ab Level 22 wächst sie heran."]),
    dict(name="Glimar", epithet="radiosa", cat="Lichtkrebs-Echo", arch="A10", size="S", h=0.55, types=("Light", "Tide"),
         habitat="Leuchtfelsen-Becken", zones=Z(4), rarity="Uncommon", act="Nocturnal",
         traits=["Glowing", "Guardian", "Filterer"], niches=["Combat", "Research"], role="Support", growth="Swift",
         polish="SpDefense:2", stats=("Support", 485), bond=45, lure="ITM_FOOD_KELPSNACK",
         sig="Lichtschild: Schild auf einen Verbündeten, reflektiert Licht-Schaden",
         mark="Scherenpanzer leuchtet wie eine kleine Laterne",
         lore=["Eine erwachsene Leuchtgarnele trägt einen leuchtenden Panzer.",
               "Bewacht ihren Schwarm und leuchtet Angreifer an.",
               "Leuchtturmwärter halten Glimars als Notlicht, falls das Feuer erlischt.",
               "Die Leuchtfelsen-Wacht hat seit Generationen einen Glimar im Becken.",
               "Entsteht aus Glimkin ab Level 22."])],
)

# L045 Singwal (Klang, 2) – Schwimmreittier
c.line_of("Two", "Ariacetus", [
    dict(name="Ariette", epithet="cantans", cat="Walkalb-Echo", arch="A06", size="M", h=1.5, w=300, types=("Sound",),
         habitat="Offene Bucht", zones=Z(2), rarity="Uncommon", act="Crepuscular",
         traits=["Singer", "Swimmer", "Playful"], niches=["Combat", "Research"], role="Support", growth="Late",
         polish="HP:1", stats=("Support", 350), evo="Level>=28 & TimeOfDay=Dusk", bond=50, lure="ITM_LURE_WINDCHIME",
         sig="Walgesang: Klang-Angriff, Verbündete erhalten Harmonie",
         mark="Rillen am Bauch leuchten im Takt des Gesangs",
         lore=["Ein Klang-Oberton der See, dessen Gesang durch die ganze Bucht trägt.",
               "Singt in der Dämmerung, folgt Booten und spielt mit Wellen.",
               "Die Lieder der Ariettes sollen die Gezeiten im Takt halten.",
               "Kontor-Seeleute pfeifen Ariettes zu – manchmal antworten sie.",
               "Entwickelt sich ab Level 28 zur Abenddämmerung."]),
    dict(name="Ariuna", epithet="magna", cat="Singwal-Echo", arch="A06", size="XL", h=7.5, w=14000, types=("Sound", "Tide"),
         habitat="Tiefe Bucht und offenes Meer", zones=[], rarity="Rare", conds=["Spawn.None"], act="Crepuscular",
         traits=["Singer", "Migratory", "Guardian"], niches=["Combat", "Mount"], role="Support", mount="Swim", growth="Late",
         polish="HP:2", stats=("Support", 505), bond=35, lure="ITM_LURE_WINDCHIME",
         sig="Tiefgesang: heilt die ganze Seite und verzögert alle Gegner",
         mark="Riesige Rillen, in denen das Klangmal wie ein Lied wandert",
         lore=["Ein ausgewachsener Singwal, dessen Lied man an Land in den Knochen spürt.",
               "Zieht zwischen Bucht und Hochsee; singt Lieder, die Stunden dauern.",
               "Der Gezeitenkult nennt das Ariuna-Lied ein Fragment des Weltlieds.",
               "Auf einem Ariuna durchquert man die Bucht so ruhig wie auf einem Schiff.",
               "Trägt Schwimmer. Entsteht aus Ariette ab Level 28 zur Abenddämmerung."])],
)

# L046 Seetang (Blüte → Gift, 2)
c.line_of("Two", "Laminaria", [
    dict(name="Tangi", epithet="fluitans", cat="Tangsprössling-Echo", arch="A14", size="XS", h=0.28, types=("Bloom",),
         habitat="Tangwälder in der Bucht", zones=Z(2), rarity="Common", act="Diurnal",
         traits=["Drifter", "Symbiont", "Camouflaged"], niches=["Combat", "Breeding"], role="Support", growth="Steady",
         polish="SpDefense:1", stats=("Support", 340), evo="Level>=24 & Weather=Rain", bond=55, lure="ITM_FOOD_KELPSNACK",
         sig="Tangwickel: heilt sich und hält ein Ziel leicht fest",
         mark="Blasen an den Wedeln leuchten grün",
         lore=["Ein Oberton des Tangwalds, den die Strömung hin und her wiegt.",
               "Treibt in Tangwäldern; Fischchen verstecken sich zwischen seinen Wedeln.",
               "In Tangwerft knotet man Tangis Glücksbänder an.",
               "Seilerinnen nutzen abgeworfene Wedel als Rohstoff.",
               "Entwickelt sich ab Level 24 nur bei Regen."]),
    dict(name="Tangix", epithet="nociva", cat="Nesseltang-Echo", arch="A14", size="M", h=1.2, w=48, types=("Venom", "Bloom"),
         habitat="Tangwald-Ränder bei Regen", zones=Z(2, 5), rarity="Uncommon", act="Diurnal",
         traits=["Ambusher", "Camouflaged", "Territorial"], niches=["Combat", "Breeding"], role="Control", growth="Steady",
         polish="SpDefense:2", stats=("Control", 490), bond=40, lure="ITM_FOOD_KELPSNACK",
         sig="Nesselwald: Gift-Stapel auf alle Gegner, Terrain Sumpf",
         mark="Nesselfäden leuchten violett entlang der Wedel",
         lore=["Ein Tangi, das im Regen wuchs, bildet Nesselfäden.",
               "Verteidigt Tangwälder gegen Fresser; brennt bei Berührung.",
               "Schwimmer meiden violett leuchtenden Tang – das Zeichen eines Tangix.",
               "Moorweise kaufen getrocknete Tangix-Fäden für Salben.",
               "Entsteht aus Tangi bei Regen ab Level 24."])],
)

# Einzelarten
c.line_of("Single", "Orichalcobius", [
    dict(name="Brassel", epithet="faber", cat="Werftgnom-Echo", arch="A04", size="S", h=0.6, w=25, types=("Metal", "Tide"),
         habitat="Werften und Wracks", zones=Z(2, 3), rarity="Uncommon", act="Diurnal",
         traits=["ToolUser", "Collector", "Curious"], niches=["Combat", "Field"], role="AllRound", growth="Steady",
         polish="Defense:2", stats=("AllRound", 470), bond=50, lure="ITM_FOOD_SHELLMEAT",
         sig="Nietflickwerk: repariert Schild eines Verbündeten und gibt Rüstung",
         mark="Messingplatten auf Brust und Armen glänzen im Takt",
         lore=["Ein Metall-Oberton aus Messing und Salz, geboren in Schiffswerften.",
               "Klettert über Rümpfe, sammelt Nieten, flickt Lecks mit Kupferblech.",
               "Ein Brassel an Bord bedeutet, dass das Schiff nie sinkt.",
               "Werftmeister Klaas schwört, sein Brassel habe mehr Schiffe gebaut als er.",
               "Entwickelt sich nicht."])],
)
c.line_of("Single", "Naufragium", [
    dict(name="Sheamast", epithet="perditus", cat="Wrackgeist-Echo", arch="A12", size="M", h=1.4, types=("Spirit", "Tide"),
         habitat="Wracks vor dem Leuchtfelsen", zones=Z(4, 5), rarity="Rare", conds=["Weather.Fog", "TimeOfDay.Night"],
         act="Nocturnal", traits=["Drifter", "Mimic", "Solitary"], niches=["Combat", "Research"], role="Caster",
         growth="Wave", polish="SpAttack:2", stats=("Caster", 480), bond=30, lure="ITM_LURE_LANTERN",
         sig="Nebelhorn: Geist-Angriff auf alle Gegner, Furcht-Chance",
         mark="Zerfetzte Segel aus Licht flattern um eine Mastgestalt",
         lore=["Ein Geist-Oberton, der um gesunkene Schiffe kreist.",
               "Erscheint bei Nebel, ahmt Glocken und Rufe nach, die einst an Bord erklangen.",
               "Der Gezeitenkult sagt, ein Sheamast hüte die Erinnerung an jede Mannschaft.",
               "Seeleute läuten bei Nebel die Glocke dreimal – für die Sheamasts.",
               "Wild nur nachts bei Nebel. Entwickelt sich nicht."])],
)
c.line_of("Single", "Margaritifera", [
    dict(name="Opalisk", epithet="nacrea", cat="Perlmuschel-Echo", arch="A11", size="S", h=0.5, w=20, types=("Crystal", "Tide"),
         habitat="Riffgrund", zones=Z(5), rarity="Rare", conds=["Moon.FullMoon"], act="Nocturnal",
         traits=["Sleepy", "Collector", "Glowing"], niches=["Combat", "Breeding"], role="Tank", growth="Late",
         polish="SpDefense:2", stats=("Tank", 480, (0, -0.1, 0, 0.1, 0.1, 0)), bond=35, lure="ITM_FOOD_SHELLMEAT",
         sig="Perlmuttspiegel: reflektiert den nächsten Spezialangriff",
         mark="Eine Perle im Inneren trägt das Klangmal und leuchtet bei Vollmond",
         lore=["Ein Kristall-Oberton, der um ein Sandkorn ein Lied aus Perlmutt wachsen ließ.",
               "Öffnet sich nur bei Vollmond; die Perle leuchtet dann durchs Wasser.",
               "Eine Opalisk-Perle zu sehen bringt Glück – sie zu nehmen, Unglück.",
               "Der Bund verbietet das Ernten von Opalisk-Perlen seit den Siegelkriegen.",
               "Wild nur bei Vollmond. Entwickelt sich nicht."])],
)

c.write()
