#!/usr/bin/env python3
"""K26/K27 – Kreaturenkatalog: Nimbara (R10), Kodex #219–#240."""
from catalog_lib import Catalog

c = Catalog(start_kodex=219, start_line=98, region="R10")
Z = lambda *n: [f"R10_Z{i:02d}" for i in n]

# L098 Himmelswal (Sturm, 3) – Flugreittier
c.line_of("Three", "Nubicetus", [
    dict(name="Nimbel", epithet="infans", cat="Wolkenkalb-Echo", arch="A06", size="M", h=1.0, w=40, types=("Storm",),
         habitat="Windstufen", zones=Z(1, 2), rarity="Common", act="Diurnal",
         traits=["Drifter", "FamilyGroup", "Playful"], niches=["Combat", "Mount"], role="Tank", growth="Late",
         polish="HP:1", stats=("Tank", 315), evo="Level>=26", bond=60, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Wolkenpolster: verringert den nächsten erlittenen Schaden stark",
         mark="Ein weicher Körper aus Wolke, durch den der Wind summt",
         lore=["Ein sanfter Sturm-Oberton, der zwischen den Inseln Nimbaras schwimmt wie ein Kalb im Meer.",
               "Folgt seiner Mutter durch die Windstufen und spielt in Aufwinden.",
               "Ein Nimbel, der unter deinem Balkon schläft, bringt einen ruhigen Sommer, sagen die Aerioner.",
               "Kinder in Aerion lernen auf geduldigen Nimbels das Gleichgewicht für das Reiten.",
               "Ab Level 26 und Level 44 wächst es zum Himmelswal."]),
    dict(name="Nimbor", epithet="cantor", cat="Wolkenwal-Echo", arch="A06", size="XL", h=4.0, w=2000, types=("Storm", "Sound"),
         habitat="Zwischen den Lumeya-Inseln", zones=Z(2), rarity="Uncommon", act="Diurnal",
         traits=["Drifter", "Singer", "Migratory"], niches=["Combat", "Mount"], role="Tank", mount="Fly",
         growth="Late", polish="HP:2", stats=("Tank", 440), evo="Level>=44", bond=45, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Walgesang: Verbündete erhalten Harmonie und Schutz vor Verwirrung",
         mark="Ein Rücken aus Kumuluswolken, aus dem tiefe Gesänge steigen",
         lore=["Der heranwachsende Himmelswal singt zwischen den Inseln.",
               "Zieht in Herden durch die Höhenwinde; ihre Lieder tragen kilometerweit.",
               "Die Aerioner glauben, der Gesang der Nimbors halte die Inseln in der Luft.",
               "Nimbors sind die großen Fähren Nimbaras – sie tragen Reisende zwischen den Inseln.",
               "Trägt Reiter durch die Luft. Ab Level 44 erreicht er die Endform."]),
    dict(name="Nimbaroth", epithet="magnus", cat="Himmelswal-Echo", arch="A06", size="XXL", h=12.0, w=60000,
         types=("Storm", "Gravity"), habitat="Über der Kronenwerft", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Diurnal", traits=["Drifter", "Guardian", "Migratory"], niches=["Combat", "Mount"], role="Tank",
         mount="Fly", growth="Late", polish="HP:3", stats=("Tank", 540), bond=30, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Himmelslast: Crescendo – senkt die Schwerkraft des Feldes, Verbündete +2 GES",
         mark="Ein Körper so groß wie eine Insel, auf dessen Rücken Gärten wachsen",
         lore=["Die Endform der Himmelswale ist so groß, dass auf ihrem Rücken Gärten wachsen.",
               "Trägt die Schwerkraft um sich wie einen Mantel; kleine Inseln folgen ihr.",
               "Die Aerioner erzählen, die ersten Inseln Nimbaras seien Nimbaroth-Rücken gewesen.",
               "Ein Nimbaroth als Reittier ist ein fliegendes Haus – Oruma Siyel lebt auf einem.",
               "Trägt Reiter durch die Luft. Entsteht aus Nimbor ab Level 44."])],
)

# L099 Sturmsegler (Sturm, 3) – Flugreittier
c.line_of("Three", "Cirrhirundo", [
    dict(name="Cirrel", epithet="velox", cat="Windschwalben-Echo", arch="A05", size="XS", h=0.2, types=("Storm",),
         habitat="Windstufen und Klippen", zones=Z(1), rarity="Common", act="Diurnal",
         traits=["Flier", "Swarm", "Migratory"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 305), evo="Level>=20", bond=55, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Böenstoß: Sturm-Angriff, Priorität +1 bei Wind",
         mark="Gabelschwanz, dessen Spitzen kleine Blitze ziehen",
         lore=["Ein flinker Sturm-Oberton, der in den Aufwinden der Windstufen tanzt.",
               "Jagt in Schwärmen nach Insekten und nistet unter Brückenbögen.",
               "Fliegen Cirrels tief, wird es Sturm geben – fliegen sie hoch, einen schönen Tag.",
               "Aerions Wetterwächter lesen das Wetter an Cirrel-Schwärmen ab.",
               "Ab Level 20 und Level 38 wächst er zum Sturmfalken."]),
    dict(name="Cirrhawk", epithet="fulgens", cat="Blitzsegler-Echo", arch="A05", size="S", h=0.7, types=("Storm", "Light"),
         habitat="Lumeya-Inseln", zones=Z(1, 2), rarity="Uncommon", act="Diurnal",
         traits=["Flier", "Hunter", "Territorial"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 430), evo="Level>=38", bond=45, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Blitzsturz: Sturzflug-Angriff, trifft die Hinterreihe",
         mark="Leuchtende Flügelkanten, die wie Wetterleuchten flackern",
         lore=["Der heranwachsende Segler stürzt sich wie ein Blitz auf Beute.",
               "Verteidigt seine Insel gegen alle Eindringlinge – auch gegen Wärter.",
               "Ein Cirrhawk-Federkiel bringt Kurierreitern Glück.",
               "Die Kuriere Aerions halten Cirrhawks für Eilbotschaften zwischen den Inseln.",
               "Ab Level 38 erreicht er die Endform."]),
    dict(name="Cirrhaven", epithet="dominus", cat="Sturmfalken-Echo", arch="A05", size="L", h=1.9, types=("Storm", "Light"),
         habitat="Über der Sternenarena", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Flier", "Hunter", "Solitary"], niches=["Combat", "Mount"], role="Speed", mount="Fly", growth="Swift",
         polish="Speed:3", stats=("Speed", 535), bond=30, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Himmelsschnitt: Crescendo – drei Sturzflüge auf zufällige Gegner, jeder kritisch bei Gewitter",
         mark="Schwingen, die Lichtbahnen in die Wolken schneiden",
         lore=["Die Endform der Sturmsegler ist der schnellste Flieger des Himmels.",
               "Reitet Gewitterfronten und schläft in den Wolken.",
               "Man sagt, ein Cirrhaven könne einen Blitz überholen.",
               "Die Rennreiter Aerions streiten jedes Jahr darum, wer den schnellsten Cirrhaven reitet.",
               "Trägt Reiter durch die Luft. Entsteht aus Cirrhawk ab Level 38."])],
)

# L100 Wolkenschaf (Licht, 3) + Zweig (Leere)
c.line_of("Three", "Nubiovis", [
    dict(name="Nubi", epithet="lanata", cat="Wölkchen-Echo", arch="A12", size="XS", h=0.28, w=0.6, types=("Light",),
         habitat="Gärten von Aerion", zones=Z(2, 3), rarity="Common", act="Diurnal",
         traits=["Drifter", "Playful", "Sunbather"], niches=["Combat", "Breeding"], role="Support", growth="Swift",
         polish="SpDefense:1", stats=("Support", 305), evo="Level>=18", bond=65, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Sonnenflaum: heilt Verbündete in Sonnenwetter jede Runde",
         mark="Ein Wollknäuel aus Wolke, das in der Sonne golden leuchtet",
         lore=["Ein Licht-Oberton, so weich wie die erste Wolke nach einem Sturm.",
               "Treibt durch Gärten und sonnt sich auf Dächern; folgt jedem, der summt.",
               "Ein Nubi im Haus hält schlechte Träume fern, sagen die Aerioner.",
               "Die Gärtner Aerions scheren Nubis für Kissen – die Wolle wächst in einer Nacht nach.",
               "Ab Level 18 und Level 34 wächst es; auf den Inseln bei Neumond zu einer anderen Form."]),
    dict(name="Nubilo", epithet="serena", cat="Wolkenschaf-Echo", arch="A12", size="S", h=0.75, w=8, types=("Light", "Storm"),
         habitat="Lumeya-Inseln", zones=Z(2), rarity="Uncommon", act="Diurnal",
         traits=["Drifter", "Herd", "Glowing"], niches=["Combat", "Breeding"], role="Support", growth="Swift",
         polish="SpDefense:2", stats=("Support", 430), evo="Level>=34", bond=50, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Regenbogenwolle: Verbündete erhalten Schutz gegen den nächsten Status",
         mark="Wolle, die Regenbögen wirft, wenn Licht durch sie fällt",
         lore=["Das heranwachsende Wolkenschaf zieht in Herden über die Inseln.",
               "Weidet Morgentau von Gräsern und schwebt bei Wind höher.",
               "Hirten auf den Lumeya-Inseln binden ihre Nubilos mit Bändern, damit sie nicht davonfliegen.",
               "Nubilo-Wolle ist die wertvollste Handelsware Nimbaras.",
               "Ab Level 34 Endform; bei Neumond auf den Inseln Zweigform."]),
    dict(name="Nubiluna", epithet="cantrix", cat="Himmelsherden-Echo", arch="A12", size="M", h=1.5, w=90, types=("Light", "Sound"),
         habitat="Gärten von Aerion", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Drifter", "Herd", "Singer"], niches=["Combat", "Breeding"], role="Support", growth="Swift",
         polish="SpDefense:3", stats=("Support", 525), bond=35, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Wiegenlied der Wolken: Crescendo – volle Heilung aller Verbündeten, Gegner schläfrig",
         mark="Ein strahlender Wolkenleib, der ein Wiegenlied summt",
         lore=["Die Endform der Wolkenschafe singt Wiegenlieder, bei denen selbst Stürme einschlafen.",
               "Führt Herden durch die Gärten; ihr Gesang beruhigt jedes Tier in der Nähe.",
               "Die Aerioner singen Kindern Nubiluna-Lieder vor, damit sie ohne Angst vor dem Fallen schlafen.",
               "Heiler Aerions arbeiten mit Nubilunas in den Gärten der Genesung.",
               "Entsteht aus Nubilo ab Level 34."])],
    branch=dict(name="Nubisk", epithet="obscura", cat="Gewitterschaf-Echo", arch="A12", size="M", h=1.4, w=40,
                types=("Void", "Light"), habitat="Lumeya-Inseln in Neumondnächten", zones=[], rarity="VeryRare",
                conds=["Spawn.None"], act="Nocturnal", traits=["Drifter", "Solitary", "Glowing"],
                niches=["Combat", "Research"], role="Control", growth="Swift", polish="SpAttack:3",
                stats=("Control", 525), bond=25, lure="ITM_LURE_STARCHIME",
                evo_from_prev="Level>=34 & Moon=NewMoon & Zone=R10_Z02",
                sig="Dunkelwolle: hüllt das Feld in Dunkelheit – Licht-Angriffe 2 Züge geschwächt",
                mark="Schwarze Wolle mit Sternenpunkten, die kein Licht zurückwirft",
                lore=["Ein Nubilo, das in einer Neumondnacht wächst, wird zu einer Wolke ohne Licht.",
                      "Treibt nachts zwischen den Inseln; wo es vorbeizieht, verschwinden die Sterne.",
                      "Die Hirten sagen, ein Nubisk hüte die Träume, die zu dunkel für den Tag sind.",
                      "Der Orden der Stille schickte Gesandte nach Nimbara, um Nubisks zu studieren.",
                      "Entsteht aus Nubilo ab Level 34 bei Neumond auf den Lumeya-Inseln."]),
)

# L101 Windharfner (Klang, 2)
c.line_of("Two", "Aeolornis", [
    dict(name="Harfel", epithet="tenuis", cat="Harfenvogel-Echo", arch="A05", size="XS", h=0.25, types=("Sound",),
         habitat="Gärten von Aerion", zones=Z(3), rarity="Common", act="Diurnal",
         traits=["Flier", "Singer", "Nester"], niches=["Combat", "Research"], role="Support", growth="Steady",
         polish="SpDefense:1", stats=("Support", 345), evo="Level>=28", bond=60, lure="ITM_LURE_WINDCHIME",
         sig="Saitenlied: Verbündete erhalten +1 GES für 2 Züge",
         mark="Schwanzfedern wie Harfensaiten, die der Wind zum Klingen bringt",
         lore=["Ein Klang-Oberton, dessen Federn wie Saiten gespannt sind.",
               "Sitzt im Wind und lässt ihn auf den Federn spielen; baut Nester in Windspielen.",
               "Ein Harfel, der am Fenster singt, kündigt Liebe an.",
               "Aerions Musiker halten Harfels als Lehrer für reine Intervalle.",
               "Ab Level 28 wächst er zum Windharfner."]),
    dict(name="Harfion", epithet="aeolius", cat="Windharfner-Echo", arch="A05", size="M", h=1.0, types=("Sound", "Storm"),
         habitat="Windstufen", zones=Z(1, 3), rarity="Uncommon", act="Diurnal",
         traits=["Flier", "Singer", "Migratory"], niches=["Combat", "Research"], role="Support", growth="Steady",
         polish="SpDefense:2", stats=("Support", 495), bond=45, lure="ITM_LURE_WINDCHIME",
         sig="Äolsakkord: Verbündete erhalten Harmonie +10, Gegner −1 Präzision",
         mark="Ein Federfächer wie eine Windharfe, der im Sturm volle Akkorde spielt",
         lore=["Der ausgewachsene Harfner spielt im Sturm ganze Symphonien.",
               "Kreist in den Windstufen; bei Sturm hört man ihn über ganz Aerion.",
               "Die Aerioner nennen Stürme ‚Harfionkonzerte‘.",
               "Das Wahrzeichen von Aerion – die Windharfe am Hafen – wurde einem Harfion nachgebaut.",
               "Entwickelt sich nicht weiter."])],
)

# L102 Glockenqualle (Klang, 2)
c.line_of("Two", "Tintinnomedusa", [
    dict(name="Tintel", epithet="pendula", cat="Glöckchen-Echo", arch="A12", size="XS", h=0.25, w=0.5, types=("Sound",),
         habitat="Unter den Inseln", zones=Z(2, 4), rarity="Common", act="Crepuscular",
         traits=["Drifter", "Singer", "Glowing"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=30 & TimeOfDay=Dusk", bond=55, lure="ITM_LURE_BELLCHIME",
         sig="Klingelton: Klang-Angriff, der bei Treffer einen Echo-Zweittreffer erzeugt",
         mark="Ein glockenförmiger Schirm, der bei jeder Bewegung läutet",
         lore=["Ein Klang-Oberton, der wie eine kleine Glocke unter den Inseln hängt.",
               "Treibt in der Dämmerung aufwärts und läutet zum Abend.",
               "Wenn die Tintels läuten, ist es Zeit, nach Hause zu gehen.",
               "Die Kronenwerft nutzt Tintel-Läuten als Schichtsignal.",
               "Ab Level 30 in der Dämmerung wächst es."]),
    dict(name="Tintabul", epithet="sonans", cat="Glockenqualle-Echo", arch="A12", size="M", h=1.5, w=90, types=("Sound", "Light"),
         habitat="Unter der Kronenwerft", zones=Z(4), rarity="Rare", conds=["TimeOfDay.Dusk"], act="Crepuscular",
         traits=["Drifter", "Singer", "Solitary"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:2", stats=("Caster", 500), bond=35, lure="ITM_LURE_BELLCHIME",
         sig="Großes Geläut: Klang-Angriff auf alle Gegner, erweckt schlafende Verbündete",
         mark="Ein Glockenschirm aus Licht, dessen Läuten man im Brustkorb spürt",
         lore=["Eine Glockenqualle, die in der Dämmerung wuchs, läutet wie eine Kathedrale.",
               "Schwebt unter der Kronenwerft und läutet zum Sonnenuntergang.",
               "Die Aerioner sagen, das Geläut der Tintabuls rufe die Sterne herbei.",
               "Bei Festen in Aerion läuten Tintabuls statt Kirchenglocken.",
               "Wild nur in der Dämmerung. Entwickelt sich nicht weiter."])],
)

# L103 Inselschildkröte (Schwerkraft, 2) – Bodenreittier
c.line_of("Two", "Insulatestudo", [
    dict(name="Holmel", epithet="levis", cat="Schwebeschildkröten-Echo", arch="A11", size="M", h=0.9, types=("Gravity",),
         habitat="Ränder der Lumeya-Inseln", zones=Z(2), rarity="Uncommon", act="Diurnal",
         traits=["Sleepy", "Grazer", "Sunbather"], niches=["Combat", "Breeding"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 350), evo="Level>=34", bond=50, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Schwebepanzer: kann nicht verschoben werden; Boden-Angriffe verfehlen",
         mark="Ein Panzer, auf dem Moos und kleine Steine schweben",
         lore=["Ein Schwerkraft-Oberton, der vergessen hat, wo unten ist.",
               "Schwebt knapp über dem Boden und grast an Inselrändern.",
               "Kinder setzen sich auf Holmels und lassen sich über Gärten tragen.",
               "Aerions Gärtner nutzen Holmels, um Pflanzen an Inselunterseiten zu pflegen.",
               "Ab Level 34 wächst er zur Inselschildkröte."]),
    dict(name="Holmgard", epithet="insularis", cat="Inselschildkröten-Echo", arch="A11", size="XL", h=3.5, types=("Gravity", "Stone"),
         habitat="Zwischen den Inseln treibend", zones=Z(2, 4), rarity="Rare", conds=["Weather.Clear"], act="Diurnal",
         traits=["Sleepy", "Guardian", "Migratory"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Late", polish="Defense:2", stats=("Tank", 505), bond=35, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Inselgewicht: erhöht die Schwerkraft; Flug-Echos verlieren ihren Ausweichbonus",
         mark="Ein Panzer wie eine kleine Insel mit eigenem Baum",
         lore=["Die ausgewachsene Schildkröte trägt eine eigene kleine Insel.",
               "Treibt langsam zwischen den Inseln; Vögel nisten auf ihrem Rücken.",
               "Die Aerioner sagen, verirrte Holmgards wurden irgendwann zu richtigen Inseln.",
               "Holmgards tragen Reiter über schwebende Brücken, die zu schmal für Karren sind.",
               "Trägt Reiter. Wild nur bei klarem Wetter. Entwickelt sich nicht weiter."])],
)

# L104 Schwebekern (Schwerkraft → Arkan, 2)
c.line_of("Two", "Levitator", [
    dict(name="Levitel", epithet="minimus", cat="Schwebestein-Echo", arch="A13", size="S", h=0.4, types=("Gravity",),
         habitat="Kronenwerft", zones=Z(4), rarity="Common", act="Diurnal",
         traits=["Curious", "Collector", "Glowing"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="SpDefense:1", stats=("Control", 345), evo="Level>=32", bond=55, lure="ITM_LURE_TUNINGFORK",
         sig="Hebung: hebt das Ziel an – es verliert 1 Zug lang seinen Reihenvorteil",
         mark="Ein schwebender Stein mit leuchtenden Runenringen",
         lore=["Ein Schwerkraft-Oberton aus dem Gestein, das Nimbara in der Luft hält.",
               "Schwebt durch die Werft und hebt kleine Dinge an, um sie zu betrachten.",
               "Werftarbeiter sagen: Ein Levitel, der dein Werkzeug versteckt, will spielen.",
               "Die Kronenwerft nutzt Levitels, um schwere Bauteile anzuheben.",
               "Ab Level 32 wächst er."]),
    dict(name="Levithar", epithet="magister", cat="Schwebekern-Echo", arch="A13", size="M", h=1.4, types=("Arcane", "Gravity"),
         habitat="Herz der Kronenwerft", zones=Z(4), rarity="Uncommon", act="Diurnal",
         traits=["Guardian", "Glowing", "ToolUser"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="SpDefense:2", stats=("Control", 500), bond=40, lure="ITM_LURE_TUNINGFORK",
         sig="Schwebefeld: Verbündete schweben 2 Züge (Boden-Angriffe verfehlen, GES +1)",
         mark="Ein Kern aus Runenstein, um den drei Ringe kreisen",
         lore=["Der ausgewachsene Schwebekern trägt Runen, die Schwere in Ordnung bringen.",
               "Hält in der Kronenwerft ganze Schiffsrümpfe in der Schwebe.",
               "Die Aerioner glauben, die ersten Inseln wurden von Levithars angehoben.",
               "Ohne Levithars stünde die Kronenwerft still – sie sind ihr wertvollstes Gut.",
               "Entwickelt sich nicht weiter."])],
)

# L105 Graupelschwarm (Frost → Kristall, 2)
c.line_of("Two", "Grandonubes", [
    dict(name="Graupel", epithet="minuta", cat="Graupelkorn-Echo", arch="A16", size="XS", h=0.2, types=("Frost",),
         habitat="Höhenwinde über den Windstufen", zones=Z(1), rarity="Common", conds=["Weather.Snow"], act="Diurnal",
         traits=["Swarm", "Drifter", "Aggressive"], niches=["Combat"], role="Striker", growth="Swift",
         polish="Attack:1", stats=("Striker", 345), evo="Level>=30 & Weather=Thunderstorm", bond=50,
         lure="ITM_LURE_WINDCHIME", sig="Graupelschauer: mehrere kleine Treffer (2–4)",
         mark="Weiße Körner, die beim Aufprall klirren",
         lore=["Ein Frost-Oberton aus tausend kleinen Eiskörnern.",
               "Fällt in Schauern über die Windstufen und prallt von allem ab.",
               "Graupel auf dem Dach bedeutet Glück für die Ernte – zu viel davon nicht.",
               "Aerions Gärtner spannen Netze, um Graupel-Schwärme von jungen Pflanzen fernzuhalten.",
               "Wild nur bei Schneefall. Ab Level 30 im Gewitter wächst er."]),
    dict(name="Graupix", epithet="grandinis", cat="Hagelsturm-Echo", arch="A16", size="M", h=1.5, w=90, types=("Crystal", "Storm"),
         habitat="Gewitterzellen über Nimbara", zones=Z(1, 5), rarity="Rare", conds=["Weather.Thunderstorm"],
         act="Diurnal", traits=["Swarm", "Drifter", "Aggressive"], niches=["Combat"], role="Striker", growth="Swift",
         polish="Attack:2", stats=("Striker", 500), bond=30, lure="ITM_LURE_WINDCHIME",
         sig="Hagelschlag: Kristall-Angriff auf alle Gegner, bei Gewitter doppelt",
         mark="Ein Wirbel aus Hagelkristallen mit einem blitzenden Kern",
         lore=["Ein Graupelschwarm, der im Gewitter wuchs, wird zu einem Hagelsturm.",
               "Fällt aus Gewitterzellen und zerschlägt Gärten und Dächer.",
               "Die Aerioner läuten Glocken, um Graupix-Stürme zu vertreiben.",
               "Die Kronenwerft panzert ihre Schiffe gegen Graupix – mit mäßigem Erfolg.",
               "Wild nur bei Gewitter. Entwickelt sich nicht weiter."])],
)

# Einzelarten
c.line_of("Single", "Lumenavis", [
    dict(name="Lumaskiff", epithet="nauta", cat="Himmelsboot-Echo", arch="A06", size="XL", h=3.5, w=900, types=("Light", "Storm"),
         habitat="Über der Kronenwerft", zones=Z(4, 5), rarity="Rare", conds=["Weather.Clear"], act="Diurnal",
         traits=["Drifter", "Glowing", "Migratory"], niches=["Combat", "Mount"], role="AllRound", mount="Fly",
         growth="Steady", polish="SpDefense:2", stats=("AllRound", 490), bond=35, lure="ITM_FOOD_CLOUDFRUIT",
         sig="Segelschein: die eigene Reihe handelt diese Runde zuerst",
         mark="Ein Körper wie ein Bootsrumpf mit Segeln aus Licht",
         lore=["Ein Licht-Oberton, der die Form der ersten Himmelsschiffe annahm.",
               "Segelt durch klare Tage über der Werft; trägt Wolkenfetzen wie Fracht.",
               "Die Werftleute glauben, Lumaskiffs seien die Seelen fertiggestellter Schiffe.",
               "Die Kronenwerft baute ihre Schiffe nach Lumaskiff-Vorbild.",
               "Trägt Reiter durch die Luft. Wild nur bei klarem Wetter. Entwickelt sich nicht."])],
)
c.line_of("Single", "Astraiudex", [
    dict(name="Astraviel", epithet="iudex", cat="Sternrichter-Echo", arch="A04", size="L", h=2.2, types=("Arcane", "Light"),
         habitat="Sternenarena", zones=Z(5), rarity="VeryRare", conds=["TimeOfDay.Night", "Weather.Clear"],
         act="Nocturnal", traits=["Stargazer", "Guardian", "Solitary"], niches=["Combat", "Research"], role="Caster",
         growth="Late", polish="SpAttack:2", stats=("Caster", 500), bond=20, lure="ITM_LURE_STARCHIME",
         sig="Sternurteil: Arkan-Angriff, Schaden steigt mit der Zahl der Werteveränderungen auf dem Feld",
         mark="Ein Gewand aus Nachthimmel, in dem Sternbilder zu Waagen werden",
         lore=["Ein Arkan-Oberton, der über die Sternenarena wacht, seit es sie gibt.",
               "Erscheint in klaren Nächten auf den Rängen und beobachtet Kämpfe schweigend.",
               "Man sagt, Astraviel entscheide, wer würdig ist, das Weltlied zu hören.",
               "Oruma Siyel kämpft nur, wenn Astraviel auf den Rängen erscheint.",
               "Wild nur in klaren Nächten. Entwickelt sich nicht."])],
)

c.write()
