#!/usr/bin/env python3
"""K26 – Kreaturenkatalog: Prismtiefen (R09), Kodex #199–#218."""
from catalog_lib import Catalog

c = Catalog(start_kodex=199, start_line=89, region="R09")
Z = lambda *n: [f"R09_Z{i:02d}" for i in n]

# L089 Kristallfledermaus (Kristall, 3) + Zweig (Leere) – Flugreittier
c.line_of("Three", "Vitrochiropter", [
    dict(name="Klirrit", epithet="pusillus", cat="Klirrflatterer-Echo", arch="A05", size="XS", h=0.2, types=("Crystal",),
         habitat="Decken des Glanzschachts", zones=Z(1, 2), rarity="Common", act="Nocturnal",
         traits=["Flier", "Echolocator", "Swarm"], niches=["Combat", "Research"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 305), evo="Level>=20", bond=55, lure="ITM_FOOD_CRYSTALSALT",
         sig="Klirrschrei: Kristall-Angriff, der Ausweichen des Ziels senkt",
         mark="Flügelhäute mit Kristallsplittern, die beim Flug wie Glas klirren",
         lore=["Ein Kristall-Oberton, der die Dunkelheit der Tiefen mit Echos ausmisst.",
               "Hängt in Trauben an Schachtdecken; ein einzelnes Klirren weckt den ganzen Schwarm.",
               "Bergleute sagen: Solange die Klirrits klirren, hält die Decke.",
               "In Prismara warnen Klirrit-Schwärme vor Gaseinbrüchen – sie verstummen, bevor die Luft schlecht wird.",
               "Ab Level 20 und Level 38 wächst er; in den Missklang-Adern zu einer anderen Form."]),
    dict(name="Klirrflug", epithet="vitreus", cat="Glasflatterer-Echo", arch="A05", size="S", h=0.7, types=("Crystal", "Sound"),
         habitat="Quarzgrund und Kavernen", zones=Z(2, 3), rarity="Uncommon", act="Nocturnal",
         traits=["Flier", "Echolocator", "Hunter"], niches=["Combat", "Research"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 430), evo="Level>=38", bond=45, lure="ITM_FOOD_CRYSTALSALT",
         sig="Resonanzflug: trifft zweimal, der zweite Treffer gegen Kristall-Echos verdoppelt",
         mark="Kristallohren, die Töne sichtbar als Lichtringe aussenden",
         lore=["Der heranwachsende Flatterer sieht mit den Ohren und spricht mit Licht.",
               "Jagt Kristallmotten in völliger Dunkelheit; seine Rufe lassen Quarzadern leuchten.",
               "Wenn eine Höhle aufleuchtet, ohne dass jemand eine Lampe trägt, jagt ein Klirrflug.",
               "Die Prismara-Kartografen nutzen Klirrflug-Rufe, um unbekannte Kavernen zu vermessen.",
               "Ab Level 38 Endform; in den Missklang-Adern Zweigform."]),
    dict(name="Klirrathan", epithet="regius", cat="Kristallschwingen-Echo", arch="A05", size="L", h=1.8, types=("Crystal", "Sound"),
         habitat="Große Prismara-Kaverne", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Flier", "Echolocator", "Solitary"], niches=["Combat", "Mount"], role="Speed", mount="Fly",
         growth="Swift", polish="Speed:3", stats=("Speed", 530), bond=30, lure="ITM_FOOD_CRYSTALSALT",
         sig="Prismenschrei: Crescendo – Klang-Kristall-Welle, alle Gegner −1 Präzision und Ausweichen",
         mark="Schwingen aus Kristallplatten, die wie eine Orgel klingen",
         lore=["Die Endform der Kristallfledermäuse trägt Schwingen aus reinem Kristall.",
               "Kreist unter der Kuppel der großen Kaverne; ihr Ruf lässt die Wände in allen Farben leuchten.",
               "Die Bergleute nennen sie die Königin der Tiefe.",
               "Klirrathans sind die einzigen Flugreittiere, die in den engen Kavernen sicher navigieren.",
               "Trägt Reiter durch die Luft. Entsteht aus Klirrflug ab Level 38."])],
    branch=dict(name="Klirrnox", epithet="dissonans", cat="Missklang-Flatterer-Echo", arch="A05", size="L", h=1.7,
                types=("Void", "Crystal"), habitat="Missklang-Adern", zones=[], rarity="VeryRare", conds=["Spawn.None"],
                act="Nocturnal", traits=["Flier", "Echolocator", "Aggressive"], niches=["Combat", "Research"],
                role="Striker", growth="Swift", polish="Attack:3", stats=("Striker", 525), bond=20,
                lure="ITM_FOOD_CRYSTALSALT", evo_from_prev="Level>=38 & Zone=R09_Z04",
                sig="Missklangschrei: Gegner verlieren Harmonie; Klang-Fähigkeiten 2 Züge gesperrt",
                mark="Kristallschwingen mit schwarzen Rissen, aus denen ein schiefer Ton dringt",
                lore=["Ein Klirrflug, der in den Missklang-Adern wächst, nimmt deren falschen Ton an.",
                      "Jagt aggressiv; sein Schrei bringt Kristalle zum Springen.",
                      "Die Bergleute fürchten Klirrnox – wo sie schreien, brechen Stollen ein.",
                      "Die Akademie untersucht Klirrnox als lebenden Beweis, dass der Missklang ansteckend ist.",
                      "Entsteht aus Klirrflug ab Level 38 in den Missklang-Adern."]),
)

# L090 Spatwurm (Kristall, 3) – Grabreittier
c.line_of("Three", "Spathovermis", [
    dict(name="Spatling", epithet="lucidus", cat="Spatwurm-Echo", arch="A07", size="S", h=0.4, w=6, types=("Crystal",),
         habitat="Lockerer Quarzsand", zones=Z(2), rarity="Common", act="Nocturnal",
         traits=["Burrower", "Lithophage", "Shy"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 310), evo="Level>=22", bond=55, lure="ITM_FOOD_CRYSTALSALT",
         sig="Spatpanzer: VER +1, bei Treffern durch Kristall-Angriffe heilt er stattdessen",
         mark="Durchscheinende Segmente, in denen Kristallkörner rieseln",
         lore=["Ein Kristall-Oberton, der Quarz frisst und Spat ausscheidet.",
               "Gräbt durch weichen Quarzsand; hinterlässt glitzernde Gänge.",
               "Spatling-Gänge sind die ersten Wege, die junge Bergleute lernen.",
               "Prismaras Glasmacher kaufen Spatling-Spat für ihre klarsten Linsen.",
               "Ab Level 22 und Level 40 wächst er zum Geodenwurm."]),
    dict(name="Spatwurm", epithet="fodiens", cat="Kristallwurm-Echo", arch="A07", size="L", h=2.4, w=600, types=("Crystal", "Stone"),
         habitat="Quarzgrund und Glanzschacht", zones=Z(1, 2), rarity="Uncommon", act="Nocturnal",
         traits=["Burrower", "Lithophage", "Territorial"], niches=["Combat", "Mount"], role="Tank", mount="Dig",
         growth="Late", polish="Defense:2", stats=("Tank", 440), evo="Level>=40", bond=45, lure="ITM_FOOD_CRYSTALSALT",
         sig="Kristallbohrer: Angriff, der Barrieren durchbricht",
         mark="Ein Bohrkopf aus Kristallzacken, der beim Graben singt",
         lore=["Der heranwachsende Wurm bohrt sich durch massiven Fels.",
               "Legt Kristallgänge an, die anderen Echos als Wege dienen.",
               "Ein singender Stollen ist ein Spatwurm-Stollen – und sicher.",
               "Die Minen von Prismara nutzen Spatwürmer zum Vortrieb neuer Schächte.",
               "Trägt Reiter unter der Erde. Ab Level 40 erreicht er die Endform."]),
    dict(name="Spathorn", epithet="profundus", cat="Geodenwurm-Echo", arch="A07", size="XL", h=4.5, w=7000,
         types=("Crystal", "Gravity"), habitat="Tiefe Resonanz", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Nocturnal", traits=["Burrower", "Guardian", "Solitary"], niches=["Combat", "Mount"], role="Tank",
         mount="Dig", growth="Late", polish="Defense:3", stats=("Tank", 540), bond=30, lure="ITM_FOOD_CRYSTALSALT",
         sig="Geodenkern: Crescendo – hüllt die eigene Reihe in eine Geode (Schild, VER/SVE +1)",
         mark="Ein Körper wie eine aufgebrochene Geode, innen voller leuchtender Kristalle",
         lore=["Die Endform der Spatwürmer ist eine lebende Geode.",
               "Ruht in der Tiefen Resonanz; um ihn wachsen Kristalle schneller als irgendwo sonst.",
               "Die Bergleute glauben, die Prismtiefen seien aus Spathorn-Gängen entstanden.",
               "Ein Spathorn trägt Reiter durch Fels, in dem selbst Spatwürmer stecken bleiben.",
               "Trägt Reiter unter der Erde. Entsteht aus Spatwurm ab Level 40."])],
)

# L091 Höhlenspinne (Schwerkraft, 3) – Kletterreittier
c.line_of("Three", "Gravaranea", [
    dict(name="Ligrel", epithet="filatrix", cat="Fadenspinnen-Echo", arch="A10", size="S", h=0.35, types=("Gravity",),
         habitat="Schachtwände", zones=Z(1, 3), rarity="Common", act="Nocturnal",
         traits=["Climber", "Ambusher", "Camouflaged"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="Speed:1", stats=("Control", 305), evo="Level>=20", bond=50, lure="ITM_FOOD_CRYSTALSALT",
         sig="Schwerfaden: bindet das Ziel – es kann 1 Zug nicht die Reihe wechseln",
         mark="Fäden, die nach oben statt nach unten hängen",
         lore=["Ein Schwerkraft-Oberton, der Fäden spinnt, die der Schwere trotzen.",
               "Spannt Netze quer durch Schächte; Beute fällt nach oben hinein.",
               "Wer in Prismara stolpert und nicht fällt, wurde von einem Ligrel-Faden gehalten.",
               "Die Minenwache nutzt Ligrel-Seide für Sicherungsseile.",
               "Ab Level 20 und Level 38 wächst sie zur Schachtweberin."]),
    dict(name="Ligrath", epithet="pendula", cat="Schachtspinnen-Echo", arch="A10", size="M", h=1.3, types=("Gravity", "Void"),
         habitat="Prismara-Kaverne und Missklang-Adern", zones=Z(3, 4), rarity="Uncommon", act="Nocturnal",
         traits=["Climber", "Hunter", "Solitary"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="Speed:2", stats=("Control", 430), evo="Level>=38", bond=40, lure="ITM_FOOD_CRYSTALSALT",
         sig="Fallnetz: legt eine Falle; der nächste Gegner, der die Reihe wechselt, wird festgehalten",
         mark="Beine mit dunklen Ringen, um die kleine Steine schweben",
         lore=["Die heranwachsende Spinne webt Netze aus verdichteter Schwere.",
               "Hängt kopfüber in Schächten, wo sie Beute aus der Dunkelheit zieht.",
               "Die Bergleute meiden Ligrath-Schächte – nicht wegen der Spinne, sondern wegen der Stille darin.",
               "Ilyx Brannoc soll den Weg in die Tiefe Resonanz über Ligrath-Netze gefunden haben.",
               "Ab Level 38 erreicht sie die Endform."]),
    dict(name="Ligravor", epithet="regina", cat="Schachtweberinnen-Echo", arch="A10", size="L", h=2.2, types=("Gravity", "Crystal"),
         habitat="Tiefe Resonanz", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Climber", "Guardian", "Solitary"], niches=["Combat", "Mount"], role="Control", mount="Climb",
         growth="Steady", polish="Speed:3", stats=("Control", 525), bond=30, lure="ITM_FOOD_CRYSTALSALT",
         sig="Schwerenetz: Crescendo – alle Gegner gebunden, ihre Geschwindigkeit sinkt um 2 Stufen",
         mark="Ein Netz aus Kristallfäden über dem Rücken, das bei Bewegung klingt",
         lore=["Die Endform der Höhlenspinnen spinnt Fäden aus Kristall und Schwere.",
               "Webt Netze über Abgründe, die ganzen Karawanen als Brücke dienen.",
               "Die Bergleute glauben, die Ligravor halte die Tiefen zusammen.",
               "Ligravors tragen Reiter senkrecht durch Schächte – und kopfüber an der Decke entlang.",
               "Trägt Reiter an Wänden. Entsteht aus Ligrath ab Level 38."])],
)

# L093 Facettenkatze (Kristall, 2)
c.line_of("Two", "Facetofelis", [
    dict(name="Facetin", epithet="nitidus", cat="Facettenkätzchen-Echo", arch="A01", size="XS", h=0.25, types=("Crystal",),
         habitat="Prismara-Gassen und Kristallgrotten", zones=Z(3), rarity="Common", act="Crepuscular",
         traits=["Curious", "Playful", "Glowing"], niches=["Combat", "Research"], role="Caster", growth="Swift",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=28 & BondTier>=3", bond=60, lure="ITM_FOOD_CRYSTALSALT",
         sig="Facettenblick: Kristall-Angriff, der Licht bricht und Präzision senkt",
         mark="Augen mit vielen Facetten, die jedes Licht in Regenbogen zerlegen",
         lore=["Ein Kristall-Oberton, der aus dem Glitzern der Grotten geboren wurde.",
               "Spielt mit Lichtreflexen und jagt Regenbogen über die Wände.",
               "Ein Facetin in der Werkstatt bringt den Juwelieren Glück.",
               "In Prismara gibt es kaum ein Haus ohne Facetin – sie gelten als Schutz vor Missklang.",
               "Ab Level 28 bei hoher Bindung wächst es."]),
    dict(name="Facettor", epithet="splendens", cat="Prismakatzen-Echo", arch="A01", size="S", h=0.7, types=("Crystal", "Light"),
         habitat="Kristallgrotten", zones=Z(3, 5), rarity="Uncommon", act="Crepuscular",
         traits=["Hunter", "Glowing", "Solitary"], niches=["Combat", "Research"], role="Caster", growth="Swift",
         polish="SpAttack:2", stats=("Caster", 495), bond=45, lure="ITM_FOOD_CRYSTALSALT",
         sig="Prismastrahl: teilt einen Licht-Angriff auf bis zu 3 Ziele",
         mark="Ein Fell aus Kristallfacetten, das Licht wie ein Kronleuchter streut",
         lore=["Die ausgewachsene Kristallkatze bricht jeden Lichtstrahl in tausend Farben.",
               "Jagt in Grotten, indem sie Beute mit Lichtspielen verwirrt.",
               "Die Juweliere sagen, ein Facettor zeige dir den Wert eines Steins, indem er ihn anstrahlt.",
               "Prismaras Juwelierzunft führt einen Facettor im Wappen.",
               "Entwickelt sich nicht weiter."])],
)

# L094 Erzmull (Metall, 2)
c.line_of("Two", "Metallotalpa", [
    dict(name="Mullit", epithet="fossor", cat="Erzmull-Echo", arch="A01", size="S", h=0.35, types=("Metal",),
         habitat="Erzadern des Glanzschachts", zones=Z(1), rarity="Common", act="Nocturnal",
         traits=["Burrower", "Collector", "Hoarder"], niches=["Combat", "Field"], role="Striker", growth="Steady",
         polish="Attack:1", stats=("Striker", 345), evo="Level>=30", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Erzkralle: Metall-Angriff, Volltreffer bei Stein-Echos",
         mark="Grabkrallen aus Metall, die beim Graben klingeln",
         lore=["Ein Metall-Oberton, der Erzadern riecht wie andere Wasser.",
               "Gräbt nach Erz und hortet die glänzendsten Brocken in seinem Bau.",
               "Ein Mullit in der Mine ist besser als jede Wünschelrute, sagen die Bergleute.",
               "Prismaras Bergleute folgen Mullits zu neuen Adern – und teilen den Fund mit ihnen.",
               "Ab Level 30 wächst er."]),
    dict(name="Mullhorn", epithet="ferratus", cat="Bohrmull-Echo", arch="A01", size="M", h=0.9, types=("Metal", "Stone"),
         habitat="Tiefe Stollen", zones=Z(1, 2), rarity="Uncommon", act="Nocturnal",
         traits=["Burrower", "Hoarder", "Territorial"], niches=["Combat", "Field"], role="Striker", growth="Steady",
         polish="Attack:2", stats=("Striker", 495), bond=40, lure="ITM_FOOD_ORECRUMBS",
         sig="Bohrhorn: durchdringender Angriff, ignoriert VER-Erhöhungen",
         mark="Ein spiralförmiges Metallhorn auf der Schnauze",
         lore=["Der ausgewachsene Mull trägt ein Bohrhorn aus gehärtetem Erz.",
               "Bohrt Gänge durch Fels und verteidigt seinen Erzhort.",
               "Wer einen Mullhorn-Hort findet, ist reich – und hat einen wütenden Mullhorn am Hals.",
               "Die Minenzunft zahlt Prämien für Wärter, die Mullhorns zu Tunnelarbeit überreden.",
               "Entwickelt sich nicht weiter."])],
)

# L095 Missklang-Wesen (Leere, 2)
c.line_of("Two", "Dissonantia", [
    dict(name="Misslit", epithet="discors", cat="Missklang-Echo", arch="A12", size="S", h=0.5, w=6, types=("Void",),
         habitat="Missklang-Adern", zones=Z(4), rarity="Uncommon", act="Nocturnal",
         traits=["Drifter", "Aggressive", "Glowing"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=32", bond=40, lure="ITM_LURE_TUNINGFORK",
         sig="Schiefton: Leere-Angriff, Verwirrung gegen Klang-Echos",
         mark="Ein flackerndes Licht, das einen falschen, schiefen Ton erzeugt",
         lore=["Ein Leere-Oberton, entstanden aus einem Riss im Weltlied.",
               "Treibt durch die Missklang-Adern und stört jede Harmonie in seiner Nähe.",
               "Bergleute stopfen sich Wachs in die Ohren, wenn Misslits in der Nähe sind.",
               "Die Akademie untersucht Misslits, um den Ursprung des Missklangs zu finden.",
               "Ab Level 32 wächst er."]),
    dict(name="Missgrath", epithet="ruptor", cat="Riss-Echo", arch="A12", size="M", h=1.5, w=60, types=("Void", "Crystal"),
         habitat="Tiefste Missklang-Adern", zones=Z(4, 5), rarity="Rare", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Drifter", "Aggressive", "Solitary"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:2", stats=("Caster", 500), bond=25, lure="ITM_LURE_TUNINGFORK",
         sig="Weltriss: ändert das Feld zu Missklang-Terrain (Harmonie-Gewinn halbiert, 3 Züge)",
         mark="Ein Kristallsplitter mit einem schwarzen Riss, aus dem kein Ton dringt",
         lore=["Ein Missklang-Echo, das wuchs, wird selbst zum Riss im Weltlied.",
               "Schwebt in den tiefsten Adern; Kristalle um ihn werden grau und stumpf.",
               "Die Bergleute sagen, ein Missgrath sei ein Stück der Großen Stille, das nicht schlafen will.",
               "Für die Akademie sind Missgraths das wichtigste Indiz für die Wiederkehr der Stille (W2).",
               "Wild nur nachts. Entwickelt sich nicht weiter."])],
)

# L096 Gedankenkristall (Arkan, 2)
c.line_of("Two", "Psychocrystallus", [
    dict(name="Psionit", epithet="cogitans", cat="Gedankenkristall-Echo", arch="A12", size="XS", h=0.2, w=0.4, types=("Arcane",),
         habitat="Quarzgrund", zones=Z(2, 5), rarity="Uncommon", act="Nocturnal",
         traits=["Drifter", "Curious", "Glowing"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:1", stats=("Control", 345), evo="Level>=30 & Moon=FullMoon", bond=45, lure="ITM_LURE_GLYPHTOKEN",
         sig="Gedankenstoß: Arkan-Angriff, kann das Ziel auf der Zeitleiste zurücksetzen",
         mark="Ein schwebender Kristall, in dem Lichtpunkte wie Gedanken wandern",
         lore=["Ein Arkan-Oberton, der in Kristallen zu denken begann.",
               "Schwebt um Wärter und scheint ihre Stimmungen zu spiegeln.",
               "Wer einem Psionit zu lange in den Kern sieht, träumt von fremden Orten.",
               "Die Akademie erforscht Psionits als mögliche Speicher von Erinnerungen.",
               "Ab Level 30 bei Vollmond wächst er."]),
    dict(name="Psioneth", epithet="sapiens", cat="Denkkristall-Echo", arch="A12", size="M", h=1.2, w=40, types=("Arcane", "Crystal"),
         habitat="Tiefe Resonanz bei Vollmond", zones=Z(5), rarity="Rare", conds=["Moon.FullMoon"], act="Nocturnal",
         traits=["Drifter", "Solitary", "Glowing"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:2", stats=("Control", 500), bond=30, lure="ITM_LURE_GLYPHTOKEN",
         sig="Gedankenspiegel: kopiert die letzte Fähigkeit des Gegners",
         mark="Ein Kristallgebilde wie ein Gehirn, das in Gedankenfarben pulsiert",
         lore=["Ein Gedankenkristall, der bei Vollmond wuchs, kann ganze Erinnerungen tragen.",
               "Schwebt in der Tiefen Resonanz und zeigt Besuchern Bilder vergangener Zeiten.",
               "Die Bergleute glauben, Psioneths bewahren die Gedanken der Verschütteten.",
               "Die Akademie verwendet Psioneth-Bilder als Quelle für die Geschichte von Ael'Dorun.",
               "Wild nur bei Vollmond. Entwickelt sich nicht weiter."])],
)

# Einzelarten
c.line_of("Single", "Miasmatus", [
    dict(name="Miasmar", epithet="nebulosus", cat="Grubengas-Echo", arch="A12", size="M", h=1.2, w=50, types=("Venom", "Void"),
         habitat="Verlassene Stollen", zones=Z(1, 4), rarity="Rare", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Drifter", "Ambusher", "Glowing"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpDefense:2", stats=("Control", 480), bond=25, lure="ITM_LURE_LANTERN",
         sig="Schlagwetter: Gift auf alle Gegner; Glut-Angriffe lösen eine Explosion aus",
         mark="Eine grünlich glimmende Wolke mit dunklem Kern",
         lore=["Ein Gift-Oberton, der aus dem Atem alter Stollen entstand.",
               "Treibt durch verlassene Gänge und sammelt sich dort, wo die Luft stillsteht.",
               "Bergleute löschen Lampen nicht, wenn ein Miasmar naht – sie verlassen den Stollen.",
               "Die Minenwache verbietet offenes Feuer in Stollen, in denen Miasmars gesichtet wurden.",
               "Wild nur nachts. Entwickelt sich nicht."])],
)
c.line_of("Single", "Stalactophonus", [
    dict(name="Stalakkord", epithet="guttans", cat="Tropfstein-Echo", arch="A13", size="L", h=2.4, types=("Sound", "Crystal"),
         habitat="Tropfsteinhallen der Prismara-Kaverne", zones=Z(3, 5), rarity="Rare", conds=["Weather.Rain"],
         act="Nocturnal", traits=["Singer", "Sleepy", "Guardian"], niches=["Combat", "Research"], role="Support",
         growth="Late", polish="SpDefense:2", stats=("Support", 490), bond=30, lure="ITM_LURE_TUNINGFORK",
         sig="Tropfakkord: Verbündete erhalten jede Runde Harmonie und leichte Heilung",
         mark="Hängende Tropfsteine, auf denen Wassertropfen Melodien spielen",
         lore=["Ein Klang-Oberton, der in den Tropfsteinhallen seit Jahrtausenden wächst.",
               "Hängt von Decken; wenn es oben regnet, spielt er mit jedem Tropfen einen Ton.",
               "Die Bergleute nennen die Tropfsteinhalle ‚die Orgel‘ – wegen des Stalakkords.",
               "Prismaras Konzerte finden bei Regen in der Kaverne statt, mit Stalakkord als Solisten.",
               "Wild nur, wenn es an der Oberfläche regnet. Entwickelt sich nicht."])],
)

c.write()
