#!/usr/bin/env python3
"""K21/K22 – Kreaturenkatalog: Morvenmoor (R03), Kodex #059–#084."""
from catalog_lib import Catalog

c = Catalog(start_kodex=59, start_line=26, region="R03")
Z = lambda *n: [f"R03_Z{i:02d}" for i in n]

# L026 Giftkröte (Gift, 3)
c.line_of("Three", "Toxibufo", [
    dict(name="Mirepip", epithet="limosus", cat="Schlammkröten-Echo", arch="A09", size="XS", h=0.18, types=("Venom",),
         habitat="Schlammige Ufer im Ried", zones=Z(1, 2), rarity="Common", act="Nocturnal",
         traits=["Mudbather", "Singer", "FamilyGroup"], niches=["Combat", "Breeding"], role="Control", growth="Steady",
         polish="SpDefense:1", stats=("Control", 305), evo="Level>=18", bond=60, lure="ITM_FOOD_MOORBERRY",
         sig="Schlammspritzer: Gift-Stapel + Präzision −1",
         mark="Warzen in Spiralmustern leuchten giftgrün beim Quaken",
         lore=["Ein Oberton des Schlamms, häufig in jeder Pfütze Morvenmoors.",
               "Quakt nachts im Chor, suhlt sich tagsüber im Schlamm gegen Austrocknung.",
               "Wer eine Mirepip küsst, bekommt Warzen – und angeblich Glück im Fischfang.",
               "Moorweise nutzen den Hautschleim (verdünnt) als Salbe gegen Insektenstiche.",
               "Ab Level 18 und 32 wächst die Linie heran."]),
    dict(name="Mirel", epithet="pustulatus", cat="Sumpfkröten-Echo", arch="A09", size="S", h=0.5, types=("Venom", "Tide"),
         habitat="Duvreth-Sümpfe", zones=Z(3), rarity="Uncommon", act="Nocturnal",
         traits=["Mudbather", "Ambusher", "Territorial"], niches=["Combat", "Breeding"], role="Control", growth="Steady",
         polish="SpDefense:2", stats=("Control", 425), evo="Level>=32", bond=45, lure="ITM_FOOD_MOORBERRY",
         sig="Sumpfblase: Gift-Angriff auf eine Reihe, legt Terrain Sumpf",
         mark="Kehlsack mit leuchtenden Ringen, bläht sich zur Drohung",
         lore=["Die heranwachsende Kröte bläht ihren Kehlsack zu leuchtenden Blasen auf.",
               "Lauert halb versunken auf Insekten; verteidigt Laichplätze mit Giftblasen.",
               "Mirels quaken angeblich lauter, je näher ein Unwetter ist.",
               "Fischer meiden Mirel-Laichplätze; Netze verkleben dort im Schleim.",
               "Ab Level 32 erreicht es die Endform."]),
    dict(name="Toxmire", epithet="rex", cat="Moorkönigs-Echo", arch="A09", size="M", h=1.3, types=("Venom", "Tide"),
         habitat="Versunkene Senke", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Mudbather", "Territorial", "Solitary"], niches=["Combat"], role="Control", growth="Steady",
         polish="SpDefense:3", stats=("Control", 520, (0.05, 0, 0.05, 0, 0, -0.05)), bond=35, lure="ITM_FOOD_MOORBERRY",
         sig="Moorkrone: Crescendo – Sumpf-Terrain auf allen Reihen, alle Gegner erhalten 2 Gift-Stapel",
         mark="Krone aus Warzen auf dem Kopf leuchtet in Wellen",
         lore=["Die Endform der Krötenlinie herrscht über ganze Teiche.",
               "Sitzt auf versunkenen Steinen, gibt tiefe Rufe von sich, die das Wasser vibrieren lassen.",
               "Im Moorglauben ist der Toxmire der König, dem selbst Nebel gehorcht.",
               "Moorweise holen sich bei einem Toxmire Rat – sie behaupten, es antworte.",
               "Entsteht aus Mirel ab Level 32."])],
)

# L027 Wels (Flut, 3) – Schwimmreittier
c.line_of("Three", "Silurundina", [
    dict(name="Undling", epithet="barbatus", cat="Bartfisch-Echo", arch="A08", size="XS", h=0.25, types=("Tide",),
         habitat="Kanäle von Morvenfurt, Ried", zones=Z(1, 2), rarity="Common", act="Nocturnal",
         traits=["Swimmer", "Scavenger", "Curious"], niches=["Combat", "Mount"], role="Tank", growth="Steady",
         polish="HP:1", stats=("Tank", 310), evo="Level>=18", bond=55, lure="ITM_FOOD_SMOKEDFISH",
         sig="Schlammwirbel: Flut-Angriff, Ziel wird in die Hinterreihe gespült",
         mark="Lange Barteln leuchten wie Laternen im trüben Wasser",
         lore=["Ein Oberton trüben Wassers, der sich in jedem Kanal zu Hause fühlt.",
               "Durchwühlt den Grund nach Essbarem; folgt Booten auf Abfälle.",
               "Ein Undling unter der Brücke bewahrt sie vor dem Einsturz, sagen Fährleute.",
               "Morvenfurts Kanäle werden von Undlingen sauber gehalten.",
               "Ab Level 18 groß genug, um Schwimmer zu tragen."]),
    dict(name="Undfin", epithet="vector", cat="Kanalwels-Echo", arch="A08", size="M", h=1.4, types=("Tide",),
         habitat="Morve-Delta und tiefe Kanäle", zones=Z(2, 3), rarity="Uncommon", act="Nocturnal",
         traits=["Swimmer", "Guardian", "Sleepy"], niches=["Combat", "Mount"], role="Tank", mount="Swim", growth="Steady",
         polish="HP:2", stats=("Tank", 430), evo="Level>=34 & Weather=Rain", bond=45, lure="ITM_FOOD_SMOKEDFISH",
         sig="Strömungsschild: Schild für die Reihe, heilt bei Regen über Zeit",
         mark="Klangmal als Ringe um die Flossen; leuchtet unter Wasser bis 10 m weit",
         lore=["Der Kanalwels ist ruhig, stark und ein geduldiger Träger.",
               "Ruht tagsüber auf dem Grund; nachts patrouilliert er durch Kanäle und Delta.",
               "Fährleute sagen, ein Undfin finde jeden Ertrunkenen – und bringe Lebende sicher heim.",
               "Das erste Schwimmreittier vieler Wärter; Morvenfurts Fährleute vermieten Sättel.",
               "Trägt Schwimmer. Entwickelt sich ab Level 34 nur bei Regen."]),
    dict(name="Undrath", epithet="maximus", cat="Deltariesen-Echo", arch="A08", size="L", h=2.8, types=("Tide", "Spirit"),
         habitat="Tiefe Stellen im Morve-Delta", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Swimmer", "Solitary", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Swim", growth="Steady",
         polish="HP:3", stats=("Tank", 525), bond=35, lure="ITM_FOOD_SMOKEDFISH",
         sig="Deltaflut: Crescendo – alle Gegner werden in die Hinterreihe gespült, eigene Seite heilt",
         mark="Barteln wie Geisterlaternen; das Klangmal schimmert durch trübes Wasser",
         lore=["Ein uralter Wels, der so lange im Delta lebt, dass sich Erinnerungen in ihm sammeln.",
               "Bewegt sich kaum; Fische leben in seinem Schatten, Boote umfahren ihn ehrfürchtig.",
               "Die Morvenfurter glauben, im Undrath lebten die Stimmen versunkener Dörfer.",
               "Mit einem Undrath durchquert ein Wärter das ganze Delta in Minuten.",
               "Trägt Schwimmer. Entsteht aus Undfin bei Regen ab Level 34."])],
)

# L028 Irrlicht (Geist, 3) + Zweig (Arkan)
c.line_of("Three", "Ignisfatuus", [
    dict(name="Irrlit", epithet="errans", cat="Irrlicht-Echo", arch="A12", size="XS", h=0.15, types=("Spirit",),
         habitat="Nebelfelder über dem Ried", zones=Z(1, 4), rarity="Common", act="Nocturnal",
         traits=["Glowing", "Drifter", "Playful"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:1", stats=("Caster", 300), evo="Level>=16 & TimeOfDay=Night", bond=55, lure="ITM_LURE_LANTERN",
         sig="Irrführung: Geist-Angriff, Ziel greift 1 Zug lang zufällig an",
         mark="Ein kleiner Lichtkern, der beim Lachen flackert",
         lore=["Ein Oberton von Licht über Wasser, der Menschen gern in die Irre führt.",
               "Tanzt nachts über Nebelfeldern, lockt Wanderer an und verschwindet lachend.",
               "Wer einem Irrlit folgt, landet im Sumpf – oder bei einem Schatz, je nach Laune.",
               "Morvenfurts Kinder fangen Irrlits in Laternen; Erwachsene lassen sie wieder frei.",
               "Entwickelt sich nachts ab Level 16 und Level 32."]),
    dict(name="Irrel", epithet="ludibunda", cat="Nebelgaukler-Echo", arch="A12", size="S", h=0.5, types=("Spirit", "Light"),
         habitat="Nebelwald Corrach", zones=Z(4), rarity="Uncommon", act="Nocturnal",
         traits=["Glowing", "Mimic", "Playful"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:2", stats=("Caster", 425), evo="Level>=32", bond=45, lure="ITM_LURE_LANTERN",
         sig="Spiegellicht: erzeugt eine Täuschung, die einen Angriff abfängt",
         mark="Mehrere Lichtkerne, die sich umkreisen",
         lore=["Mehrere Irrlits verschmelzen zu einem Gaukler aus Licht und Nebel.",
               "Ahmt Stimmen nach, um Wanderer zu necken; führt Verirrte aber oft heim.",
               "Irrels sollen die Seelen Ertrunkener zum Licht begleiten.",
               "Die Laternennacht in Morvenfurt ehrt die Irrels mit schwimmenden Lichtern.",
               "Ab Level 32 entsteht die Endform; in der Versunkenen Senke bei Neumond eine andere."]),
    dict(name="Irraune", epithet="lanternaria", cat="Laternengeist-Echo", arch="A12", size="M", h=1.3, types=("Spirit", "Light"),
         habitat="Versunkene Senke, Turmruinen", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Glowing", "Guardian", "Drifter"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:3", stats=("Caster", 520), bond=30, lure="ITM_LURE_LANTERN",
         sig="Laternenreigen: Crescendo – trifft alle Gegner, blendet und reinigt die eigene Seite",
         mark="Ein Kranz aus Laternenlichtern um eine durchscheinende Gestalt",
         lore=["Die Endform der Irrlichter trägt ein Dutzend Lichter wie Laternen um sich.",
               "Wacht über Turmruinen in der Senke und weist Verirrten den Weg zum Ufer.",
               "Im Moorglauben ist die Irraune die Hüterin der Laternennacht.",
               "Fährleute stellen am Ufer Laternen für Irraunen auf – als Dank für geleitete Boote.",
               "Entsteht aus Irrel ab Level 32."])],
    branch=dict(name="Sigilaune", epithet="occulta", cat="Siegellicht-Echo", arch="A12", size="M", h=1.2,
                types=("Arcane", "Spirit"), habitat="Versunkener Turm", zones=[], rarity="VeryRare", conds=["Spawn.None"],
                act="Nocturnal", traits=["Glowing", "Collector", "Solitary"], niches=["Combat", "Research"],
                role="Control", growth="Wave", polish="SpAttack:3", stats=("Control", 520), bond=25,
                lure="ITM_LURE_GLYPHTOKEN", evo_from_prev="Level>=32 & Zone=R03_Z05 & Moon=NewMoon",
                sig="Siegelreigen: kehrt die Typtabelle für 1 Zug gegen ein Ziel um, versiegelt dessen Crescendo",
                mark="Statt Laternen umkreisen Glyphen die Gestalt",
                lore=["Ein Irrel, das bei Neumond nahe dem Versunkenen Turm wächst, liest dessen Glyphen.",
                      "Kreist um die Turmspitze und ordnet leuchtende Zeichen zu wechselnden Siegeln.",
                      "Niemand weiß, ob die Sigilaune den Turm bewacht oder den Schlaf darin.",
                      "Die Freien Stimmen nutzen ihre Glyphen angeblich als Geheimschrift.",
                      "Entsteht aus Irrel ab Level 32 bei Neumond in der Versunkenen Senke."]),
)

# L029 Fleischfressende Pflanze (Blüte, 3)
c.line_of("Three", "Dionaeflos", [
    dict(name="Blossi", epithet="captans", cat="Klappblüten-Echo", arch="A14", size="XS", h=0.25, types=("Bloom",),
         habitat="Moospolster im Ried", zones=Z(1, 3), rarity="Common", act="Diurnal",
         traits=["Ambusher", "Camouflaged", "Sunbather"], niches=["Combat", "Breeding"], role="Striker", growth="Steady",
         polish="Attack:1", stats=("Striker", 310), evo="Level>=20", bond=55, lure="ITM_FOOD_MOORBERRY",
         sig="Klappfalle: Blüte-Angriff, hält ein Ziel 1 Zug fest",
         mark="Blütenrand mit leuchtenden Härchen, die beim Zuschnappen aufblitzen",
         lore=["Ein Oberton der Moorblüte, die von Insekten statt von Erde lebt.",
               "Sonnt sich offen, schnappt zu, wenn Beute die Härchen berührt.",
               "Eine Blossi im Garten frisst die Mücken – deshalb lieben Fennhavener sie.",
               "Kräuterkundige züchten Blossis als natürliche Insektenfalle.",
               "Ab Level 20 und 36 wächst sie heran."]),
    dict(name="Blossar", epithet="vorax", cat="Fangblumen-Echo", arch="A14", size="S", h=0.7, types=("Bloom", "Venom"),
         habitat="Duvreth-Sümpfe", zones=Z(3), rarity="Uncommon", act="Diurnal",
         traits=["Ambusher", "Camouflaged", "Territorial"], niches=["Combat", "Breeding"], role="Striker", growth="Steady",
         polish="Attack:2", stats=("Striker", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_MOORBERRY",
         sig="Nektarfalle: lockt Gegner in die Vorderreihe und vergiftet",
         mark="Süßlich leuchtender Nektar im Kelch zeigt das Klangmal",
         lore=["Die heranwachsende Fangblume lockt mit Duft und Nektar.",
               "Wurzelt an Wegrändern im Sumpf; Tiere, die ihr zu nahe kommen, werden betäubt.",
               "Sagen warnen Kinder: Riecht es plötzlich süß im Sumpf, lauf zurück.",
               "Ihr Nektar ist Grundlage eines starken Betäubungsmittels der Moorweisen.",
               "Ab Level 36 erreicht sie die Endform."]),
    dict(name="Blossmire", epithet="regina", cat="Moorrosen-Echo", arch="A14", size="L", h=2.2, w=650, types=("Bloom", "Venom"),
         habitat="Versunkene Senke", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Ambusher", "Solitary", "Guardian"], niches=["Combat"], role="Striker", growth="Steady",
         polish="Attack:3", stats=("Striker", 525), bond=30, lure="ITM_FOOD_MOORBERRY",
         sig="Moorrosenblüte: Crescendo – greift alle Gegner an, heilt um den verursachten Schaden",
         mark="Riesige Blüte, deren Blätter wie ein Herz pulsieren",
         lore=["Die Endform der Fangblumen ist eine Rose so groß wie ein Haus.",
               "Herrscht über ganze Lichtungen der Senke; ihr Duft betäubt auf zwanzig Meter.",
               "Die Moorrose soll aus dem Grab einer Königin gewachsen sein.",
               "Moorweise ernten bei Vollmond vorsichtig ihren Nektar für Heiltränke.",
               "Entsteht aus Blossar ab Level 36."])],
)

# L030 Mückenschwarm (Gift, 2)
c.line_of("Two", "Culexmota", [
    dict(name="Virmote", epithet="susurrans", cat="Summschwarm-Echo", arch="A16", size="XS", h=0.05, w=0.01, types=("Venom",),
         habitat="Über stehendem Wasser", zones=Z(1, 2, 3), rarity="Common", act="Crepuscular",
         traits=["Swarm", "Flier", "Singer"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 340), evo="Level>=24", bond=60, lure="ITM_FOOD_MOORBERRY",
         sig="Stichschwarm: drei kleine Gift-Treffer",
         mark="Der Schwarm leuchtet in der Dämmerung als grünlicher Schleier",
         lore=["Ein Schwarm-Oberton aus tausend summenden Stimmen.",
               "Steigt in der Dämmerung über Tümpeln auf und summt im Gleichklang.",
               "Wer den Summton der Virmotes nachsingen kann, wird nicht gestochen, sagt man.",
               "Lästig, aber Teil des Kreislaufs: Virmotes bestäuben Moorpflanzen.",
               "Ab Level 24 wird der Schwarm zu einer größeren Gestalt."]),
    dict(name="Virwyn", epithet="nebulosus", cat="Fieberschwarm-Echo", arch="A16", size="S", h=0.7, w=0.3, types=("Venom", "Storm"),
         habitat="Nebelwald Corrach", zones=Z(4), rarity="Uncommon", act="Crepuscular",
         traits=["Swarm", "Flier", "Hunter"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 490), bond=40, lure="ITM_FOOD_MOORBERRY",
         sig="Fieberwolke: Gift auf eine Reihe, getroffene Gegner verlieren Präzision",
         mark="Der Schwarm formt flügelartige Schleier mit leuchtenden Adern",
         lore=["Ein verdichteter Schwarm, der sich zu einer flügelartigen Gestalt formt.",
               "Jagt in Nebelwäldern; der Schwarm folgt Wärme und Atem.",
               "Fieber nach einem Nebelwald-Besuch nennen die Morvenfurter Virwyn-Grüße.",
               "Moorweise verkaufen Räucherwerk gegen Virwyns.",
               "Entsteht aus Virmote ab Level 24."])],
)

# L031 Moorkrake (Gift, 2)
c.line_of("Two", "Paludopus", [
    dict(name="Blightkin", epithet="lentus", cat="Moorkraken-Echo", arch="A17", size="S", h=0.5, types=("Venom",),
         habitat="Schlammige Tümpel", zones=Z(3, 5), rarity="Uncommon", act="Nocturnal",
         traits=["Ambusher", "Camouflaged", "ToolUser"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="SpDefense:1", stats=("Control", 345), evo="Level>=26", bond=45, lure="ITM_FOOD_SMOKEDFISH",
         sig="Tintenschlamm: Gift + Präzision −1 für alle Gegner einer Reihe",
         mark="Saugnäpfe mit leuchtenden Rändern",
         lore=["Ein Oberton des Schlammgrunds, klug und geduldig.",
               "Versteckt sich im Schlamm, benutzt Muschelschalen als Schutz und Werkzeug.",
               "Ein Blightkin, das einem Fischer einen Stein schenkt, schenkt ihm Glück.",
               "Fährleute fürchten, dass Blightkins Netze stehlen – oft zu Recht.",
               "Ab Level 26 wird es zur großen Moorkrake."]),
    dict(name="Blightar", epithet="paludosus", cat="Sumpftentakel-Echo", arch="A17", size="M", h=1.4, types=("Venom", "Tide"),
         habitat="Versunkene Senke", zones=Z(5), rarity="Rare", conds=["Weather.Fog"], act="Nocturnal",
         traits=["Ambusher", "Territorial", "ToolUser"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="SpDefense:2", stats=("Control", 495), bond=35, lure="ITM_FOOD_SMOKEDFISH",
         sig="Tentakelnetz: hält zwei Ziele fest (Zeitleiste +) und vergiftet",
         mark="Lange Arme mit Leuchtringen, die im Nebel pulsieren",
         lore=["Die ausgewachsene Moorkrake beherrscht Tümpel der Senke.",
               "Greift mit acht Armen gleichzeitig; baut Höhlen aus versunkenem Holz.",
               "Die Legende sagt, ein Blightar habe den Turm von Morvenfurt versenkt – ein Märchen.",
               "Schmuggler nutzen ihre Höhlen als Verstecke – wenn sie sich hineintrauen.",
               "Wild nur bei Nebel."])],
)

# L032 Moorschildkröte (Flut, 2) – Bodenreittier
c.line_of("Two", "Uliginochelys", [
    dict(name="Brinlet", epithet="musci", cat="Moosschild-Echo", arch="A11", size="S", h=0.4, w=11, types=("Tide",),
         habitat="Morvenfurt-Kanäle, Ufer", zones=Z(1, 2), rarity="Common", act="Diurnal",
         traits=["Sunbather", "Swimmer", "Sleepy"], niches=["Combat", "Breeding"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 345), evo="Level>=28", bond=55, lure="ITM_FOOD_KELPSNACK",
         sig="Panzerdusche: Schild + Heilung über Zeit für sich",
         mark="Moos auf dem Panzer wächst entlang eines leuchtenden Musters",
         lore=["Ein Oberton geduldigen Wassers, auf dessen Panzer Moos wächst.",
               "Sonnt sich auf Stegen; Kinder reiten auf erwachsenen Exemplaren.",
               "Wer eine Brinlet auf dem Weg findet, soll sie zum Wasser tragen – das bringt Segen.",
               "Morvenfurts Stegwärter halten Brinlets als Glücksbringer.",
               "Ab Level 28 wächst sie zu einem Reittier."]),
    dict(name="Brinshell", epithet="vectrix", cat="Kanalpanzer-Echo", arch="A11", size="L", h=1.7, w=500, types=("Tide", "Bloom"),
         habitat="Delta und breite Kanäle", zones=Z(2, 3), rarity="Uncommon", act="Diurnal",
         traits=["Sunbather", "Swimmer", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Late", polish="Defense:2", stats=("Tank", 500), bond=45, lure="ITM_FOOD_KELPSNACK",
         sig="Gartenpanzer: Schild für die Reihe, Überwuchs auf der eigenen Reihe",
         mark="Auf dem Panzer wächst ein kleiner Garten, dessen Blüten im Takt leuchten",
         lore=["Eine ausgewachsene Moosschildkröte trägt einen Garten auf dem Rücken.",
               "Watet langsam durch Kanäle; Vögel nisten in ihrem Panzergarten.",
               "Man sagt, die ersten Häuser Morvenfurts standen auf einem Brinshell.",
               "Lastenträger der Kanalstadt; trittsicher auf Schlamm und Stegen.",
               "Trägt Reiter (Bodenreiten). Entsteht aus Brinlet ab Level 28."])],
)

# L033 Schattenaal (Leere, 2)
c.line_of("Two", "Umbranguilla", [
    dict(name="Umbrling", epithet="obscurus", cat="Schattenaal-Echo", arch="A07", size="S", h=0.7, w=3, types=("Void",),
         habitat="Dunkle Tiefen der Senke", zones=Z(5), rarity="Uncommon", act="Nocturnal",
         traits=["Ambusher", "Swimmer", "Shy"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=28 & TimeOfDay=Night", bond=45, lure="ITM_FOOD_SMOKEDFISH",
         sig="Schattensog: Leere-Angriff, entzieht dem Ziel einen Buff",
         mark="Statt Leuchtpunkten trägt es dunkle Ringe, in denen Licht verschwindet",
         lore=["Ein Leere-Oberton, entstanden in Wasser, das kein Licht mehr erreicht.",
               "Gleitet nachts durch die Senke; Licht scheint um ihn herum schwächer.",
               "Der Moorglaube sagt, ein Umbrling verschlucke die Stimmen der Ertrunkenen.",
               "Fischer werfen Netze nie dort aus, wo Laternen plötzlich dunkler werden.",
               "Entwickelt sich ab Level 28 nur nachts."]),
    dict(name="Umbracoil", epithet="vacuus", cat="Leerschlangen-Echo", arch="A07", size="M", h=1.55, w=25, types=("Void", "Tide"),
         habitat="Versunkener Turm", zones=Z(5), rarity="Rare", conds=["TimeOfDay.Night", "Weather.Fog"], act="Nocturnal",
         traits=["Ambusher", "Solitary", "Swimmer"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:2", stats=("Caster", 495), bond=30, lure="ITM_FOOD_SMOKEDFISH",
         sig="Stillstrom: entzieht dem Gegner 15 Harmonie und verlangsamt",
         mark="Die Ringe wurden zu Löchern im Licht – das Klangmal ist Abwesenheit",
         lore=["Ein ausgewachsener Schattenaal, um den das Licht selbst zu verstummen scheint.",
               "Umkreist nachts den Versunkenen Turm; nahe Laternen erlöschen.",
               "Der Orden der Stille hält Umbracoils für heilige Boten der Pause.",
               "Die Freien Stimmen meiden den Turm, wenn Umbracoils kreisen.",
               "Wild nur nachts bei Nebel nahe dem Turm."])],
)

# L034 Trauerweide (Blüte → Geist, 2)
c.line_of("Two", "Salixmanes", [
    dict(name="Weidlit", epithet="lacrimosa", cat="Weidenkätzchen-Echo", arch="A14", size="XS", h=0.28, types=("Bloom",),
         habitat="Uferweiden in Fennhaven", zones=Z(1), rarity="Uncommon", act="Crepuscular",
         traits=["Shy", "Sleepy", "Symbiont"], niches=["Combat", "Breeding"], role="Support", growth="Steady",
         polish="SpDefense:1", stats=("Support", 345), evo="BondTier>=3 & TimeOfDay=Dusk", bond=50, lure="ITM_FOOD_MOORBERRY",
         sig="Kätzchenflaum: heilt einen Verbündeten, reinigt Gift",
         mark="Weiche Kätzchen an den Zweigen leuchten silbern",
         lore=["Ein Oberton der Weide, der in ihren Zweigen schläft.",
               "Hängt kopfüber in Weidenzweigen; fällt nachts lautlos ins Gras, um zu fressen.",
               "Ein Weidlit über der Tür tröstet Trauernde, sagt der Moorglaube.",
               "In Fennhaven pflanzt man Weiden, damit Weidlits einziehen.",
               "Entwickelt sich bei Bindungsstufe 3 in der Abenddämmerung."]),
    dict(name="Weiduna", epithet="memorialis", cat="Trauerweiden-Echo", arch="A12", size="M", h=1.5, types=("Spirit", "Bloom"),
         habitat="Friedhofsweiden und Laternenstege", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Drifter", "Guardian", "Singer"], niches=["Combat", "Research"], role="Support", growth="Steady",
         polish="SpDefense:2", stats=("Support", 495), bond=35, lure="ITM_LURE_LANTERN",
         sig="Erinnerungshain: heilt die ganze Seite, Verbündete erhalten Furcht-Immunität",
         mark="Hängende Zweige aus Licht, an deren Enden Erinnerungsbilder aufscheinen",
         lore=["Ein Weidlit, das tiefe Bindung erfährt, wird zur geisterhaften Trauerweide.",
               "Schwebt über Gräbern und singt leise; Trauernde fühlen sich getröstet.",
               "Die Laternennacht wird für Weidunas gefeiert – sie tragen die Erinnerungen.",
               "Kein Moorbewohner würde eine Weiduna je vertreiben.",
               "Entsteht aus Weidlit bei Bindungsstufe 3 zur Abenddämmerung."])],
)

# Einzelarten
c.line_of("Single", "Ardeaventus", [
    dict(name="Morhaw", epithet="silens", cat="Nebelreiher-Echo", arch="A05", size="L", h=1.7, types=("Storm", "Tide"),
         habitat="Flache Wasser im Ried", zones=Z(1, 2), rarity="Uncommon", act="Crepuscular",
         traits=["Hunter", "Solitary", "Flier"], niches=["Combat", "Mount"], role="Striker", mount="Fly", growth="Steady",
         polish="Attack:2", stats=("Striker", 480), bond=40, lure="ITM_FOOD_SMOKEDFISH",
         sig="Speerstoß: schneller Angriff, kritischer Treffer gegen Flut-Ziele",
         mark="Lange Halsfedern mit leuchtenden Bändern",
         lore=["Ein Oberton von Wind über Wasser – das einzige Sturm-Echo des Moores.",
               "Steht reglos im Wasser, stößt blitzschnell zu; fliegt bei Nebel tief über das Ried.",
               "Ein Morhaw auf dem Dachfirst kündigt Gäste an.",
               "Fischer respektieren Morhaws; sie zeigen, wo die Fische stehen.",
               "Entwickelt sich nicht. Trägt Reiter durch die Luft, sobald Flugreiten erlaubt ist."])],
)
c.line_of("Single", "Bombinator", [
    dict(name="Humbog", epithet="profundus", cat="Unkenchor-Echo", arch="A09", size="M", h=0.9, types=("Sound", "Venom"),
         habitat="Tiefe Tümpel, Laternenstege", zones=Z(2, 3), rarity="Uncommon", act="Nocturnal",
         traits=["Singer", "Sleepy", "Territorial"], niches=["Combat", "Field"], role="Support", growth="Wave",
         polish="HP:2", stats=("Support", 470), bond=45, lure="ITM_FOOD_MOORBERRY",
         sig="Unkenruf: Klang-Angriff, gibt allen Verbündeten Harmonie",
         mark="Riesiger Kehlsack mit konzentrischen Leuchtringen",
         lore=["Ein Klang-Oberton der Tiefe, dessen Ruf den ganzen Sumpf erzittern lässt.",
               "Ruft nachts in langen, tiefen Tönen; andere Kröten stimmen ein.",
               "Der Ruf des Humbog soll Nebel heranrufen.",
               "Morvenfurts Nachtmarkt beginnt traditionell mit dem ersten Humbog-Ruf.",
               "Entwickelt sich nicht."])],
)
c.line_of("Single", "Turfagolem", [
    dict(name="Torfgor", epithet="paludis", cat="Torfriesen-Echo", arch="A13", size="L", h=2.1, w=800, types=("Stone", "Bloom"),
         habitat="Torfstiche bei Riedwacht", zones=Z(1, 3), rarity="Rare", conds=["Weather.Rain"], act="Cathemeral",
         traits=["Sleepy", "Guardian", "Camouflaged"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:2", stats=("Tank", 500), bond=35, lure="ITM_FOOD_MOSSCAKE",
         sig="Torfwand: Schild für die ganze Seite, kostet viel Zeit",
         mark="Moos und Torf auf einem Steinkern; das Klangmal schimmert durch Risse",
         lore=["Ein Stein-Oberton aus gepresstem Torf, so alt wie das Moor selbst.",
               "Schläft jahrelang als Hügel; erwacht bei Regen und wandert langsam.",
               "Torfstecher bitten den Torfgor um Erlaubnis, bevor sie stechen.",
               "Wo ein Torfgor schläft, wird nie gestochen – so will es die Zunft.",
               "Entwickelt sich nicht. Wild nur bei Regen."])],
)

c.write()
