#!/usr/bin/env python3
"""K24 – Kreaturenkatalog: Ignareth (R05), Kodex #135–#156."""
from catalog_lib import Catalog

c = Catalog(start_kodex=135, start_line=61, region="R05")
Z = lambda *n: [f"R05_Z{i:02d}" for i in n]

# L061 Lavamolch (Glut, 3)
c.line_of("Three", "Pyrotriton", [
    dict(name="Pyrolm", epithet="pusillus", cat="Funkenmolch-Echo", arch="A09", size="XS", h=0.2, types=("Ember",),
         habitat="Warme Tümpel der Aschefelder", zones=Z(1, 2), rarity="Common", act="Diurnal",
         traits=["Thermal", "Playful", "Mudbather"], niches=["Combat", "Field"], role="Caster", growth="Steady",
         polish="SpAttack:1", stats=("Caster", 305), evo="Level>=18", bond=60, lure="ITM_FOOD_SULFURCANDY",
         sig="Funkenspucke: Glut-Angriff mit Brand-Chance",
         mark="Leuchtende Kiemenbüschel, die bei Freude Funken sprühen",
         lore=["Ein munterer Oberton der heißen Tümpel, halb Wasser, halb Glut.",
               "Badet in warmem Schlamm und spuckt Funken nach Insekten.",
               "Ein Pyrolm im Brunnen bedeutet, dass das Wasser bald warm wird – gut für Bäder, schlecht für Bier.",
               "Die Bäder von Schlackenwehr halten Pyrolms, um das Wasser auf Temperatur zu bringen.",
               "Ab Level 18 und Level 36 wächst er zum Lavamolch."]),
    dict(name="Pyrolax", epithet="fervidus", cat="Glutmolch-Echo", arch="A09", size="S", h=0.6, types=("Ember",),
         habitat="Schlackenhang und heiße Quellen", zones=Z(2, 3), rarity="Uncommon", act="Diurnal",
         traits=["Thermal", "Swimmer", "Territorial"], niches=["Combat", "Field"], role="Caster", growth="Steady",
         polish="SpAttack:2", stats=("Caster", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_SULFURCANDY",
         sig="Glutbad: Terrain wird Glutboden; eigene Glut-Angriffe stärker",
         mark="Rückenkamm aus glühenden Platten, die im Wasser zischen",
         lore=["Der heranwachsende Molch schwimmt in Wasser, das andere verbrühen würde.",
               "Verteidigt heiße Quellen gegen Eindringlinge; sein Kamm glüht vor Wut.",
               "Wer in eine Pyrolax-Quelle steigt, kommt geheilt heraus – oder gar nicht.",
               "Schmiede aus Schlackenwehr härten Klingen in Pyrolax-Quellen.",
               "Ab Level 36 erreicht er die Endform."]),
    dict(name="Pyroluth", epithet="magmaticus", cat="Lavamolch-Echo", arch="A09", size="M", h=1.4, types=("Ember", "Stone"),
         habitat="Ränder des Vorthax-Schlackenstroms", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Thermal", "Swimmer", "Solitary"], niches=["Combat"], role="Caster", growth="Steady",
         polish="SpAttack:3", stats=("Caster", 525), bond=30, lure="ITM_FOOD_SULFURCANDY",
         sig="Lavaflut: Crescendo – Glut-Welle auf alle Gegner, Terrain Glutboden 3 Züge",
         mark="Haut aus erkaltender Lava, durch deren Risse Glut pulsiert",
         lore=["Die Endform der Molche schwimmt in flüssiger Lava wie in einem See.",
               "Taucht im Schlackenstrom auf und ab; erstarrt nachts zu einem Stein, der leise knistert.",
               "Die Bergleute sagen, Pyroluths halten die Lava in ihrem Bett.",
               "Kaldrex Vorn soll seinen ersten Pyroluth aus dem Strom gezogen haben – mit bloßen Händen.",
               "Entsteht aus Pyrolax ab Level 36."])],
)

# L062 Schmiedegolem (Metall, 3)
c.line_of("Three", "Incudomorphus", [
    dict(name="Ambolt", epithet="parvus", cat="Ambossling-Echo", arch="A13", size="S", h=0.5, types=("Metal",),
         habitat="Schmiedegassen und Schlackenhalden", zones=Z(2), rarity="Common", act="Diurnal",
         traits=["ToolUser", "Collector", "Curious"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 310), evo="Level>=20", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Hammerschlag: Metall-Angriff, der VER des Ziels senkt",
         mark="Ein kleiner Amboss als Rumpf, der beim Gehen klingt",
         lore=["Ein Metall-Oberton aus den Schlägen tausender Hämmer.",
               "Sammelt Eisenreste, klopft sie flach und baut sich kleine Werkzeuge.",
               "Ein Ambolt in der Werkstatt bringt gute Arbeit, sagen die Schmiede.",
               "Lehrlinge in Schlackenwehr beginnen ihre Lehre, indem sie einem Ambolt zuschauen.",
               "Ab Level 20 und Level 38 wächst er zum Schmiedeherrn."]),
    dict(name="Ambrak", epithet="faber", cat="Schmiedegolem-Echo", arch="A13", size="M", h=1.5, types=("Metal", "Ember"),
         habitat="Schmieden und Gießereien", zones=Z(2, 4), rarity="Uncommon", act="Diurnal",
         traits=["ToolUser", "Guardian", "Thermal"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:2", stats=("Tank", 440), evo="Level>=38", bond=45, lure="ITM_FOOD_ORECRUMBS",
         sig="Glühnieten: verstärkt die Rüstung eines Verbündeten (VER +1, 3 Züge)",
         mark="Esse im Brustkorb, deren Glut den Herzschlag zeigt",
         lore=["Der heranwachsende Golem trägt eine Esse in der Brust.",
               "Schmiedet aus Erz einfache Formen; repariert, was andere zerbrachen.",
               "Ein Ambrak, der nicht mehr glüht, ist traurig – man gibt ihm Kohle und ein Lied.",
               "Die Gießereien des Goldklang-Kontors setzen Ambraks an den heißesten Öfen ein.",
               "Ab Level 38 erreicht er die Endform."]),
    dict(name="Ambross", epithet="dominus", cat="Schmiedeherr-Echo", arch="A13", size="L", h=2.6, types=("Metal", "Ember"),
         habitat="Alte Zwergenschmieden in der Obsidianklamm", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Diurnal", traits=["ToolUser", "Guardian", "Solitary"], niches=["Combat", "Field"], role="Tank",
         growth="Late", polish="Defense:3", stats=("Tank", 535), bond=30, lure="ITM_FOOD_ORECRUMBS",
         sig="Weltamboss: Crescendo – Schild auf alle Verbündeten, Gegner, die ihn treffen, erleiden Rückstoß",
         mark="Hammerarme, deren Schläge einen tiefen Glockenton erzeugen",
         lore=["Die Endform der Schmiedegolems trägt Hämmer statt Hände.",
               "Bewacht verlassene Schmieden und arbeitet nachts an Werken, die niemand bestellt hat.",
               "Die Schmiedezunft sagt, das erste Schwert von Aethris sei auf einem Ambross geschmiedet worden.",
               "Ein Ambross im Kader ist in Schlackenwehr ein Zeichen höchsten Handwerksstolzes.",
               "Entsteht aus Ambrak ab Level 38."])],
)

# L063 Aschehund (Glut, 3)
c.line_of("Three", "Cinericanis", [
    dict(name="Aschwel", epithet="catulus", cat="Aschewelpen-Echo", arch="A01", size="XS", h=0.28, types=("Ember",),
         habitat="Aschefelder", zones=Z(1), rarity="Common", act="Crepuscular",
         traits=["Pack", "Playful", "Scavenger"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 305), evo="Level>=16", bond=60, lure="ITM_FOOD_CHARCOAL",
         sig="Aschesprung: schneller Angriff, hinterlässt Aschewolke (Präzision −1)",
         mark="Fell aus grauer Asche, darunter glimmende Punkte",
         lore=["Ein Oberton der Aschefelder, verspielt wie ein Funke im Wind.",
               "Tobt in Rudeln durch die Asche und gräbt nach glimmenden Kohlestücken.",
               "Ein Aschwel, der dir folgt, will spielen – lass keine Kohle offen liegen.",
               "Die Ascheklauber von Schlackenwehr halten Aschwels als Wachhunde und Spürnasen.",
               "Ab Level 16 und Level 34 wächst er zum Glutwolf."]),
    dict(name="Aschund", epithet="venator", cat="Glutjagdhund-Echo", arch="A01", size="S", h=0.75, types=("Ember",),
         habitat="Aschefelder und Schlackenhang", zones=Z(1, 2), rarity="Uncommon", act="Crepuscular",
         traits=["Pack", "Hunter", "Territorial"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 430), evo="Level>=34", bond=45, lure="ITM_FOOD_CHARCOAL",
         sig="Rudelhatz: stärker, je mehr Verbündete bereits handelten",
         mark="Glutadern entlang der Beine, die im Lauf aufleuchten",
         lore=["Der heranwachsende Aschehund jagt im Rudel über heiße Asche.",
               "Folgt Beute durch Rauch, den andere Jäger meiden.",
               "Ein heulendes Aschund-Rudel kündigt einen Ausbruch an, glauben die Bergleute.",
               "Die Ignar-Bergwacht arbeitet mit Aschund-Rudeln, um Verschüttete zu finden.",
               "Ab Level 34 erreicht er die Endform."]),
    dict(name="Aschgrim", epithet="umbrosus", cat="Glutwolf-Echo", arch="A01", size="M", h=1.2, types=("Ember", "Void"),
         habitat="Ignar-Krater bei Nacht", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Pack", "Hunter", "Solitary"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:3", stats=("Speed", 530), bond=30, lure="ITM_FOOD_CHARCOAL",
         sig="Schattenglut: Crescendo – verschwindet in Rauch und trifft alle Gegner nacheinander",
         mark="Rauchmähne, durch die rote Augen glühen",
         lore=["Die Endform der Aschehunde trägt Rauch wie ein Fell und Glut wie ein Herz.",
               "Führt Rudel am Kraterrand; erscheint und verschwindet in Rauchschwaden.",
               "Kinder fürchten den ‚Rauchwolf‘ – Erwachsene wissen, dass er Verirrte zum Weg führt.",
               "Der Orden der Stille beobachtet Aschgrims, weil ihre Leere-Glut an alte Stille-Zeichen erinnert.",
               "Entsteht aus Aschund ab Level 34."])],
)

# L064 Obsidiankrebs (Stein, 3) – Bodenreittier
c.line_of("Three", "Obsidicancer", [
    dict(name="Obsikin", epithet="vitreus", cat="Glaskrebs-Echo", arch="A11", size="S", h=0.4, types=("Stone",),
         habitat="Obsidianklamm", zones=Z(4), rarity="Common", act="Nocturnal",
         traits=["Lithophage", "Shy", "Camouflaged"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 310), evo="Level>=22", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Glaspanzer: verringert physischen Schaden; bei Krit zersplittert er (VER −1)",
         mark="Schwarzglänzende Schale, auf der das Klangmal als Schliff erscheint",
         lore=["Ein scheuer Oberton aus erkaltetem Vulkanglas.",
               "Frisst Steinstaub und verbirgt sich zwischen Obsidiansplittern.",
               "Wer einen Obsikin findet, findet Obsidian – sagen die Klammsucher.",
               "Werkzeugmacher sammeln abgeworfene Obsikin-Schalen für Klingen.",
               "Ab Level 22 und Level 40 wächst er zum Obsidianfürsten."]),
    dict(name="Obsidar", epithet="scutatus", cat="Obsidiankrebs-Echo", arch="A11", size="M", h=1.2, types=("Stone", "Crystal"),
         habitat="Obsidianklamm und Kraterhänge", zones=Z(4, 5), rarity="Uncommon", act="Nocturnal",
         traits=["Lithophage", "Territorial", "Camouflaged"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:2", stats=("Tank", 440), evo="Level>=40", bond=45, lure="ITM_FOOD_ORECRUMBS",
         sig="Splitterschere: Angriff, der Splitter-Fallen auf die gegnerische Reihe legt",
         mark="Scheren wie geschliffene Klingen, die im Licht singen",
         lore=["Der heranwachsende Krebs trägt Scheren aus geschliffenem Glas.",
               "Verteidigt Spalten, in denen frischer Obsidian entsteht.",
               "Die Klammsucher legen Obsidar-Futter am Eingang ab, bevor sie eine Spalte betreten.",
               "Schlackenwehrer Glasschleifer nutzen Obsidar, um Rohglas zu spalten.",
               "Ab Level 40 erreicht er die Endform."]),
    dict(name="Obsidrax", epithet="princeps", cat="Obsidianfürst-Echo", arch="A11", size="L", h=2.4, types=("Stone", "Crystal"),
         habitat="Tiefe Obsidianklamm", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Guardian", "Lithophage", "Solitary"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Late", polish="Defense:3", stats=("Tank", 540), bond=30, lure="ITM_FOOD_ORECRUMBS",
         sig="Obsidianwall: Crescendo – Kristallmauer schützt die eigene Reihe 2 Züge",
         mark="Ein Panzer wie eine Kathedrale aus schwarzem Glas",
         lore=["Die Endform der Obsidiankrebse ist ein Fürst aus schwarzem Glas.",
               "Durchquert glühende Klammen ungerührt; Lava perlt an ihm ab.",
               "Die Klammsucher glauben, ein Obsidrax trage ein erkaltetes Stück des Weltlieds in sich.",
               "Wärter reiten Obsidrax durch Hitzezonen, die andere Reittiere meiden.",
               "Trägt Reiter. Entsteht aus Obsidar ab Level 40."])],
)

# L065 Glutdrache (Glut, 2) – Flugreittier
c.line_of("Two", "Ignidraco", [
    dict(name="Ignavyr", epithet="iuvenis", cat="Glutdrachen-Echo", arch="A15", size="L", h=1.8, w=180, types=("Ember",),
         habitat="Kraterrand des Ignar", zones=Z(5), rarity="Rare", conds=["Weather.Heatwave"], act="Diurnal",
         traits=["Flier", "Thermal", "Territorial"], niches=["Combat"], role="Striker", growth="Late",
         polish="Attack:1", stats=("Striker", 375), evo="Level>=42", bond=30, lure="ITM_FOOD_SULFURCANDY",
         sig="Krateratem: Glut-Angriff auf eine Reihe, durchdringt Schilde",
         mark="Flügel mit Glutadern, die bei jedem Schlag aufglimmen",
         lore=["Ein junger Glut-Oberton, der in der Hitze des Kraters flügge wird.",
               "Kreist über dem Ignar-Krater und ruht auf heißen Felsen; meidet Regen.",
               "Ein Ignavyr am Himmel bedeutet, dass der Berg ruhig bleibt – solange er fliegt.",
               "Kaldrex Vorn verlangt von Herausforderern, einen Ignavyr nur zu beobachten, nicht zu fangen.",
               "Wild nur bei Hitzewelle. Ab Level 42 wächst er zum Kraterdrachen."]),
    dict(name="Ignavor", epithet="ignifer", cat="Kraterdrachen-Echo", arch="A15", size="XL", h=4.5, w=1400,
         types=("Ember", "Gravity"), habitat="Ignar-Krater", zones=[], rarity="VeryRare", conds=["Spawn.None"],
         act="Diurnal", traits=["Flier", "Thermal", "Solitary"], niches=["Combat", "Mount"], role="Striker",
         mount="Fly", growth="Late", polish="Attack:2", stats=("Striker", 520), bond=20, lure="ITM_FOOD_SULFURCANDY",
         sig="Kraterlast: Crescendo – Glut-Meteor aus der Höhe, Schwerkraft zieht Gegner nach vorn",
         mark="Hörner, um die Schlackebrocken kreisen wie kleine Monde",
         lore=["Die Endform des Glutdrachen wird so schwer vom Erz in ihm, dass Steine ihm folgen.",
               "Schläft im Krater; wenn er aufsteigt, regnet es Asche über Schlackenwehr.",
               "Die Bergleute sehen in Ignavor den Hüter, der den Berg vom Ausbruch abhält.",
               "Einen Ignavor zu reiten ist in Ignareth die höchste Ehre; nur wenige versuchten es.",
               "Trägt Reiter durch die Luft. Entsteht aus Ignavyr ab Level 42."])],
)

# L066 Rauchgeist (Leere, 2)
c.line_of("Two", "Fumivacuus", [
    dict(name="Fumel", epithet="tenebrosus", cat="Rauchschleier-Echo", arch="A12", size="S", h=0.6, types=("Void",),
         habitat="Fumarolen der Aschefelder", zones=Z(1, 5), rarity="Uncommon", act="Nocturnal",
         traits=["Drifter", "Shy", "Camouflaged"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:1", stats=("Control", 345), evo="Level>=28 & TimeOfDay=Night", bond=45, lure="ITM_LURE_LANTERN",
         sig="Rußhauch: Leere-Angriff, löscht positive Werteveränderungen des Ziels",
         mark="Ein Rauchwirbel mit zwei dunklen Löchern, die kein Licht zurückwerfen",
         lore=["Ein Leere-Oberton, der aus Rauch und Schweigen besteht.",
               "Treibt um Fumarolen und verschluckt Geräusche; wo er schwebt, wird es still.",
               "Die Bergleute flüstern, ein Fumel könne Lieder stehlen.",
               "Der Orden der Stille hält Fumels in Laternen, um Meditationen zu vertiefen.",
               "Ab Level 28 bei Nacht wächst er."]),
    dict(name="Fumaroth", epithet="silens", cat="Schlotgeist-Echo", arch="A12", size="M", h=1.5, types=("Void", "Ember"),
         habitat="Ignar-Krater nachts", zones=Z(5), rarity="Rare", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Drifter", "Solitary", "Glowing"], niches=["Combat", "Research"], role="Control", growth="Wave",
         polish="SpAttack:2", stats=("Control", 500), bond=30, lure="ITM_LURE_LANTERN",
         sig="Erstickender Schlot: Gegner können 1 Zug keine Klang-Fähigkeiten nutzen",
         mark="Rauchmantel mit glimmenden Rändern und einem stummen, offenen Mund",
         lore=["Ein Rauchgeist, der nachts im Krater wuchs, trägt Glut im schweigenden Inneren.",
               "Steigt aus den Schloten und schluckt Lärm; Tiere verstummen in seiner Nähe.",
               "Manche glauben, Fumaroths seien Reste der Großen Stille, die sich im Berg versteckt haben.",
               "Die Akademie misst um Fumaroths eine Abschwächung des Weltlieds – Grund zur Sorge.",
               "Wild nur nachts. Entwickelt sich nicht weiter."])],
)

# L067 Geodenaffe (Kristall, 2)
c.line_of("Two", "Drusopithecus", [
    dict(name="Drusil", epithet="scandens", cat="Drusenaffen-Echo", arch="A18", size="S", h=0.6, types=("Crystal",),
         habitat="Felswände der Obsidianklamm", zones=Z(4), rarity="Uncommon", act="Diurnal",
         traits=["Climber", "Collector", "Playful"], niches=["Combat", "Field"], role="Support", growth="Steady",
         polish="SpDefense:1", stats=("Support", 345), evo="Level>=28", bond=55, lure="ITM_FOOD_CRYSTALSALT",
         sig="Drusenwurf: wirft eine Kristalldruse, heilt Verbündeten oder trifft Gegner",
         mark="Rückenhaut mit Kristalldrusen, die beim Klettern klingeln",
         lore=["Ein Kristall-Oberton, der seine Schätze am eigenen Leib trägt.",
               "Klettert durch die Klamm, knackt Geoden und sammelt die schönsten Kristalle.",
               "Ein Drusil tauscht Kristalle gegen Essen – fair, aber hart verhandelnd.",
               "Händler in Schlackenwehr haben gelernt, mit Drusils um Rohkristalle zu feilschen.",
               "Ab Level 28 wächst er."]),
    dict(name="Drusaro", epithet="sapiens", cat="Geodenwächter-Echo", arch="A18", size="M", h=1.4, types=("Crystal", "Ember"),
         habitat="Kristallhöhlen der Obsidianklamm", zones=Z(4), rarity="Rare", conds=["Zone.R05_Z04"], act="Diurnal",
         traits=["Climber", "Guardian", "ToolUser"], niches=["Combat", "Field"], role="Support", growth="Steady",
         polish="SpDefense:2", stats=("Support", 495), bond=40, lure="ITM_FOOD_CRYSTALSALT",
         sig="Glutkristall: legt eine heilende Kristallfläche, die Glutangriffe abschwächt",
         mark="Kristallbart und Rückenplatten, die innen rot glühen",
         lore=["Ein Geodenaffe, der in der Hitze wuchs, trägt glühende Kristalle.",
               "Hütet Kristallhöhlen und lehrt Jungtiere das Knacken von Geoden.",
               "Klammsucher bitten einen Drusaro um Erlaubnis, bevor sie eine Höhle betreten.",
               "Die Akademie studiert Drusaro-Werkzeuge als Beispiel für Echo-Kultur.",
               "Entwickelt sich nicht weiter."])],
)

# L068 Blitzgeier (Sturm → Metall, 2) – Flugreittier
c.line_of("Two", "Fulgurvultur", [
    dict(name="Volket", epithet="crepitans", cat="Funkengeier-Echo", arch="A05", size="S", h=0.7, types=("Storm",),
         habitat="Schlackenhalden bei Gewitter", zones=Z(2, 3), rarity="Common", act="Diurnal",
         traits=["Flier", "Scavenger", "Collector"], niches=["Combat"], role="Speed", growth="Steady",
         polish="Speed:1", stats=("Speed", 345), evo="Level>=30", bond=50, lure="ITM_FOOD_ORECRUMBS",
         sig="Funkenhieb: Sturm-Angriff, der gegen Metall-Echos stärker wirkt",
         mark="Metallisch glänzende Federn, die Funken ziehen",
         lore=["Ein Sturm-Oberton, angezogen vom Metall der Halden.",
               "Pickt Metallreste aus der Schlacke und baut Horste aus Draht.",
               "Ein Volket auf dem Dach zieht den Blitz an – und hält ihn vom Haus fern.",
               "Schlackenwehr bezahlt Volket-Halter dafür, Metall von den Halden zu sammeln.",
               "Ab Level 30 wächst er zum Blitzgeier."]),
    dict(name="Voltarn", epithet="ferreus", cat="Blitzgeier-Echo", arch="A05", size="L", h=1.8, types=("Metal", "Storm"),
         habitat="Über dem Schlackenstrom bei Gewitter", zones=Z(3), rarity="Rare", conds=["Weather.Thunderstorm"],
         act="Diurnal", traits=["Flier", "Scavenger", "Hunter"], niches=["Combat", "Mount"], role="Speed",
         mount="Fly", growth="Steady", polish="Speed:2", stats=("Speed", 500), bond=35, lure="ITM_FOOD_ORECRUMBS",
         sig="Blitzableiter: zieht Sturm-Angriffe auf sich und lädt sich damit auf",
         mark="Schwingen aus Eisenfedern, zwischen denen Blitze knistern",
         lore=["Der ausgewachsene Geier hat seine Federn durch Metall ersetzt.",
               "Kreist bei Gewittern über dem Schlackenstrom und lässt sich vom Blitz treffen.",
               "Die Bergleute nennen ihn den Gewittervogt.",
               "Voltarns sind die bevorzugten Flugreittiere der Ignar-Bergwacht – blitzfest und zäh.",
               "Trägt Reiter durch die Luft. Wild nur bei Gewitter. Entwickelt sich nicht weiter."])],
)

# Einzelarten
c.line_of("Single", "Basaltophonus", [
    dict(name="Bassalt", epithet="organum", cat="Basaltorgel-Echo", arch="A13", size="L", h=2.4, types=("Sound", "Stone"),
         habitat="Basaltsäulen am Schlackenhang", zones=Z(2, 4), rarity="Rare", conds=["Weather.Thunderstorm"],
         act="Diurnal", traits=["Singer", "Guardian", "Sleepy"], niches=["Combat", "Research"], role="Support",
         growth="Late", polish="HP:2", stats=("Support", 480), bond=30, lure="ITM_LURE_TUNINGFORK",
         sig="Orgelgrollen: Klang-Angriff auf alle Gegner, Verbündete erhalten Harmonie",
         mark="Säulen aus Basalt, durch die der Wind tiefe Töne bläst",
         lore=["Ein Klang-Oberton, der in Basaltsäulen das Lied des Berges singt.",
               "Schläft als Felsformation und erwacht nur, wenn Donner ihn anstimmt.",
               "Wenn die Basaltorgel singt, wissen die Bergleute: Der Berg ist zufrieden.",
               "Musiker aus Dorunsruh pilgern zum Schlackenhang, um Bassalts Töne aufzuzeichnen.",
               "Wild nur bei Gewitter. Entwickelt sich nicht."])],
)
c.line_of("Single", "Nucleoignis", [
    dict(name="Nucleox", epithet="profundus", cat="Kraterherz-Echo", arch="A12", size="M", h=1.2, w=300,
         types=("Gravity", "Ember"), habitat="Tief im Ignar-Krater", zones=Z(5), rarity="VeryRare",
         conds=["Weather.Heatwave", "TimeOfDay.Night"], act="Nocturnal", traits=["Thermal", "Solitary", "Glowing"],
         niches=["Combat", "Research"], role="Caster", growth="Late", polish="SpAttack:2", stats=("Caster", 500),
         bond=20, lure="ITM_FOOD_SULFURCANDY",
         sig="Kernschwere: zieht alle Gegner in die Vorderreihe, Schaden steigt mit ihrem Gewicht",
         mark="Eine glühende Kugel, um die Gesteinsringe kreisen wie um einen Planeten",
         lore=["Ein Schwerkraft-Oberton, der wie ein kleines Herz im Inneren des Berges schlägt.",
               "Schwebt in heißen Kammern; Gestein kreist um ihn wie Monde.",
               "Die Bergleute glauben, Nucleox sei das Herz des Ignar – stirbt er, erkaltet der Berg.",
               "Die Akademie vermutet, dass Nucleox die Ausbrüche dämpft, und verbietet seine Jagd.",
               "Wild nur nachts bei Hitzewelle. Entwickelt sich nicht."])],
)

c.write()
