#!/usr/bin/env python3
"""K24/K25 – Kreaturenkatalog: Hvitfell (R07), Kodex #157–#178."""
from catalog_lib import Catalog

c = Catalog(start_kodex=157, start_line=71, region="R07")
Z = lambda *n: [f"R07_Z{i:02d}" for i in n]

# L071 Schneeluchs (Frost, 3)
c.line_of("Three", "Nivilynx", [
    dict(name="Snevel", epithet="catulus", cat="Schneeluchsjunges-Echo", arch="A01", size="XS", h=0.28, types=("Frost",),
         habitat="Verschneite Wälder des Fjallstad-Tals", zones=Z(1, 2), rarity="Common", act="Crepuscular",
         traits=["Playful", "Camouflaged", "Curious"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 305), evo="Level>=18", bond=60, lure="ITM_FOOD_ICEFISH",
         sig="Pulversprung: Frost-Angriff aus dem Schnee, Priorität +1 bei Schneefall",
         mark="Pinselohren mit Eiskristallen, die bei Kälte klingeln",
         lore=["Ein verspielter Oberton des Neuschnees, der lautlos über Wehen springt.",
               "Taucht kopfüber in Schneewehen, um Mäuse zu fangen, und verliert dabei oft die Orientierung.",
               "Ein Snevel auf der Schwelle bedeutet einen langen Winter – und ein fröhliches Haus.",
               "Die Kinder in Hvitmark ziehen Snevels auf, die später die Schlitten begleiten.",
               "Ab Level 18 und Level 36 wächst er zum Firnluchs."]),
    dict(name="Snevar", epithet="silvestris", cat="Schneeluchs-Echo", arch="A01", size="S", h=0.75, types=("Frost",),
         habitat="Bergwälder und Ruinen", zones=Z(2, 3), rarity="Uncommon", act="Crepuscular",
         traits=["Hunter", "Camouflaged", "Solitary"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_ICEFISH",
         sig="Weißer Schatten: erhöht Ausweichen, bei Schneefall unsichtbar für 1 Zug",
         mark="Fell, dessen Flecken wie Schneekristalle glitzern",
         lore=["Der heranwachsende Luchs bewegt sich im Schnee, ohne Spuren zu hinterlassen.",
               "Jagt in der Dämmerung; seine Pfoten sind breit wie Schneeschuhe.",
               "Jäger sagen: Wer einen Snevar sieht, hat ihn längst nicht gesehen.",
               "Die Grenzwächter von Hvitfell nutzen Snevars als lautlose Kundschafter.",
               "Ab Level 36 erreicht er die Endform."]),
    dict(name="Snevrik", epithet="borealis", cat="Firnluchs-Echo", arch="A01", size="M", h=1.2, types=("Frost", "Light"),
         habitat="Isvaldtind im Polarlicht", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Hunter", "Solitary", "Glowing"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:3", stats=("Speed", 530), bond=30, lure="ITM_FOOD_ICEFISH",
         sig="Polarlichtsprung: Crescendo – springt durch Lichtschleier und trifft jeden Gegner einmal",
         mark="Eine Mähne, in der Polarlichtbänder fließen",
         lore=["Die Endform der Schneeluchse trägt das Polarlicht im Fell.",
               "Jagt nachts auf den Gipfeln; wo er läuft, leuchtet der Schnee grün.",
               "Die Alten in Hvitmark sagen, Snevriks bewachen die Pfade der Toten zu den Sternen.",
               "Sigrun Fjall reitet nicht – sie läuft mit ihrem Snevrik durch den Schnee.",
               "Entsteht aus Snevar ab Level 36."])],
)

# L072 Frostmammut (Frost, 3) – Bodenreittier
c.line_of("Three", "Glaciomammut", [
    dict(name="Kjalf", epithet="lanatus", cat="Mammutkalb-Echo", arch="A02", size="M", h=1.2, types=("Frost",),
         habitat="Fjallstad-Tal und Weiden", zones=Z(1), rarity="Common", act="Diurnal",
         traits=["Herd", "Grazer", "FamilyGroup"], niches=["Combat", "Mount"], role="Tank", growth="Late",
         polish="HP:1", stats=("Tank", 315), evo="Level>=22", bond=60, lure="ITM_FOOD_ALPINECHEESE",
         sig="Wollpanzer: verringert Frost- und Sturmschaden",
         mark="Dichtes Fell mit Eisperlen, die beim Laufen klirren",
         lore=["Ein gutmütiger Oberton der Täler, eingehüllt in dicke Wolle.",
               "Weidet unter dem Schnee nach Moos; Kälber bleiben dicht bei der Herde.",
               "Ein Kjalf, der sich an dich lehnt, hat dich in die Familie aufgenommen.",
               "Hvitmarker Bauern scheren Kjalf-Wolle für die wärmsten Mäntel des Nordens.",
               "Ab Level 22 trägt es Reiter, ab Level 40 bei Schneefall wird es zum Gletscherriesen."]),
    dict(name="Kjalmur", epithet="vector", cat="Frostmammut-Echo", arch="A02", size="L", h=2.6, types=("Frost", "Stone"),
         habitat="Pässe und Gletschervorland", zones=Z(3, 4), rarity="Uncommon", act="Diurnal",
         traits=["Herd", "Grazer", "Guardian"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Late", polish="HP:2", stats=("Tank", 440), evo="Level>=40 & Weather=Snow", bond=45,
         lure="ITM_FOOD_ALPINECHEESE", sig="Schneepflug: Angriff auf die Vorderreihe, räumt Fallen",
         mark="Stoßzähne mit Eisrillen, in denen der Wind summt",
         lore=["Das ausgewachsene Mammut bahnt Wege durch meterhohen Schnee.",
               "Zieht im Winter über die Pässe und hält sie für andere Tiere offen.",
               "Ein Kjalmur, der die Pässe nicht mehr räumt, kündigt das Ende einer Ära an.",
               "Hvitmarks Postreiter nutzen Kjalmurs, um im Winter den Schweigfels-Pass zu überqueren.",
               "Trägt Reiter. Entwickelt sich ab Level 40 bei Schneefall."]),
    dict(name="Kjalgrund", epithet="antiquus", cat="Gletscherriesen-Echo", arch="A02", size="XL", h=4.2,
         types=("Frost", "Stone"), habitat="Gletscherzunge", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Diurnal", traits=["Herd", "Guardian", "Sleepy"], niches=["Combat", "Mount"], role="Tank",
         mount="Ground", growth="Late", polish="HP:3", stats=("Tank", 540), bond=30, lure="ITM_FOOD_ALPINECHEESE",
         sig="Gletscherschritt: Crescendo – Eiswall vor der eigenen Reihe, Gegner rutschen nach hinten",
         mark="Ein Rücken aus Gletschereis, in dem alte Luftblasen tönen",
         lore=["Die Endform der Mammuts trägt einen Gletscher auf dem Rücken.",
               "Schläft monatelang an der Gletscherzunge und wandert nur, wenn der Schnee ruft.",
               "Die Hvitfeller sagen, die Gletscher seien schlafende Kjalgrunde.",
               "Ein Kjalgrund trägt eine ganze Familie samt Hausrat über die Pässe.",
               "Trägt Reiter. Entsteht aus Kjalmur ab Level 40 bei Schneefall."])],
)

# L073 Schneeeule (Frost, 3) + Zweig (Leere)
c.line_of("Three", "Nivistrix", [
    dict(name="Uvlet", epithet="pullus", cat="Schneekauz-Echo", arch="A05", size="XS", h=0.25, types=("Frost",),
         habitat="Ruinen von Eiðvik", zones=Z(2), rarity="Common", act="Nocturnal",
         traits=["Flier", "Curious", "Nester"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:1", stats=("Caster", 300), evo="Level>=18", bond=55, lure="ITM_FOOD_ICEFISH",
         sig="Raureifblick: Frost-Angriff, Chance auf Erstarren",
         mark="Riesige Augen mit Eisringen, die im Dunkeln schimmern",
         lore=["Ein wacher Oberton der Winternächte.",
               "Nistet in Ruinen und beobachtet Reisende mit schief gelegtem Kopf.",
               "Ein Uvlet im Fenster bedeutet Besuch aus der Ferne.",
               "Die Archivare in Hvitmark halten Uvlets – sie wecken sie, wenn Kerzen umfallen.",
               "Ab Level 18 und Level 36 wächst er; am Schweigfels-Pass in der Nacht zu einer anderen Form."]),
    dict(name="Uvarn", epithet="vigilans", cat="Schneeeulen-Echo", arch="A05", size="S", h=0.7, types=("Frost", "Spirit"),
         habitat="Eiðvik-Ruinen und Pass", zones=Z(2, 3), rarity="Uncommon", act="Nocturnal",
         traits=["Flier", "Hunter", "Solitary"], niches=["Combat", "Research"], role="Caster", growth="Steady",
         polish="SpAttack:2", stats=("Caster", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_ICEFISH",
         sig="Lautloser Flug: erster Angriff jedes Kampfes kann nicht ausgewichen werden",
         mark="Federn, die Schneeflocken im Flug einfangen",
         lore=["Die heranwachsende Eule fliegt so lautlos, dass Schnee in ihrem Gefieder liegen bleibt.",
               "Jagt nachts über den Ruinen; ruft nur einmal im Jahr.",
               "Wer den Ruf eines Uvarn hört, erinnert sich an einen vergessenen Namen, glaubt man in Eiðvik.",
               "Die Akademie vermutet, dass Uvarns die Ruinen von Eiðvik seit der Großen Stille bewohnen.",
               "Ab Level 36 Endform; am Schweigfels-Pass nachts die Zweigform."]),
    dict(name="Uvalis", epithet="memor", cat="Ahneneulen-Echo", arch="A05", size="L", h=1.7, types=("Frost", "Spirit"),
         habitat="Eiðvik-Ruinen", zones=[], rarity="Rare", conds=["Spawn.None"], act="Nocturnal",
         traits=["Flier", "Guardian", "Stargazer"], niches=["Combat", "Mount"], role="Caster", mount="Fly",
         growth="Steady", polish="SpAttack:3", stats=("Caster", 525), bond=30, lure="ITM_FOOD_ICEFISH",
         sig="Ahnenruf: Crescendo – ruft die Stimme eines besiegten Verbündeten zurück (Wiederbelebung 30 %)",
         mark="Gefieder, in dem Gesichter von Ahnen schimmern",
         lore=["Die Endform der Schneeeulen trägt die Erinnerung der Toten im Gefieder.",
               "Wacht über die Ruinen von Eiðvik und singt nachts die Namen der Gefallenen.",
               "Die Hvitfeller ehren Uvalis als Botin der Ahnen.",
               "Eine Uvalis als Reittier wird in Hvitmark nur verdienten Wärtern zugestanden.",
               "Trägt Reiter durch die Luft. Entsteht aus Uvarn ab Level 36."])],
    branch=dict(name="Uvasil", epithet="tacita", cat="Stilleulen-Echo", arch="A05", size="L", h=1.6, types=("Void", "Frost"),
                habitat="Schweigfels-Pass in mondlosen Nächten", zones=[], rarity="VeryRare", conds=["Spawn.None"],
                act="Nocturnal", traits=["Flier", "Solitary", "Camouflaged"], niches=["Combat", "Research"],
                role="Control", growth="Steady", polish="SpAttack:3", stats=("Control", 525), bond=20,
                lure="ITM_LURE_BELLCHIME", evo_from_prev="Level>=36 & Zone=R07_Z03 & TimeOfDay=Night",
                sig="Schweigeschwinge: Gegner verlieren 1 Zug lang ihren Eigenklang-Bonus",
                mark="Schwarze Federn, die jeden Ton in ihrer Nähe verschlucken",
                lore=["Ein Uvarn, das nachts am Schweigfels-Pass wächst, nimmt die Stille des Klosters an.",
                      "Fliegt völlig lautlos – selbst der Wind verstummt um sie.",
                      "Der Orden der Stille verehrt die Uvasil als Zeichen, dass Stille nicht Tod bedeutet.",
                      "Sereth Vaun soll eine Uvasil als einzige Gefährtin besitzen.",
                      "Entsteht aus Uvarn ab Level 36 nachts am Schweigfels-Pass."]),
)

# L074 Polarlichtrochen (Licht, 3) – Flugreittier
c.line_of("Three", "Aurorabatis", [
    dict(name="Lyskin", epithet="lucidus", cat="Lichtschleier-Echo", arch="A06", size="M", h=0.9, w=25, types=("Light",),
         habitat="Über dem Fjallstad-Tal in klaren Nächten", zones=Z(1, 5), rarity="Uncommon", act="Nocturnal",
         traits=["Drifter", "Glowing", "Stargazer"], niches=["Combat", "Research"], role="Support", growth="Wave",
         polish="SpDefense:1", stats=("Support", 305), evo="Level>=20 & Weather=Clear", bond=50, lure="ITM_LURE_AURORAGLASS",
         sig="Schleierlicht: heilt den Verbündeten mit den wenigsten HP",
         mark="Ein durchscheinender Körper, der grün und violett flackert",
         lore=["Ein Licht-Oberton, aus dem ersten Polarlicht nach der Großen Stille geboren.",
               "Gleitet in klaren Nächten über die Täler; tagsüber schläft es in Schneehöhlen.",
               "Kinder in Hvitmark winken Lyskins zu, damit das Polarlicht wiederkommt.",
               "Die Sternwarte von Hvitmark zählt Lyskins, um Polarlichtnächte vorherzusagen.",
               "Ab Level 20 in klarer Nacht und Level 38 wächst es."]),
    dict(name="Lysmara", epithet="velata", cat="Polarlicht-Echo", arch="A06", size="L", h=2.2, w=320, types=("Light", "Frost"),
         habitat="Isvaldtind", zones=Z(5), rarity="Rare", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Drifter", "Glowing", "Migratory"], niches=["Combat", "Mount"], role="Support", mount="Fly",
         growth="Wave", polish="SpDefense:2", stats=("Support", 435), evo="Level>=38", bond=40,
         lure="ITM_LURE_AURORAGLASS", sig="Nordlichtschleier: Verbündete erhalten Schutz gegen Statusveränderungen",
         mark="Lange Flossenbänder wie Vorhänge aus Licht",
         lore=["Das heranwachsende Licht-Echo zieht Polarlichter wie Schleier hinter sich her.",
               "Wandert nachts zwischen Gipfeln; sein Licht spiegelt sich auf Gletschern.",
               "Die Hvitfeller sagen, Lysmaras weben das Polarlicht.",
               "Eine Lysmara trägt Reiter durch klare Nächte – tagsüber verweigert sie den Flug.",
               "Trägt Reiter durch die Luft. Wild nur nachts. Ab Level 38 Endform."]),
    dict(name="Lysthane", epithet="sonora", cat="Himmelsvorhang-Echo", arch="A06", size="XL", h=4.8, w=3200,
         types=("Light", "Sound"), habitat="Über dem Isvaldtind", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Nocturnal", traits=["Drifter", "Singer", "Glowing"], niches=["Combat", "Mount"], role="Support",
         mount="Fly", growth="Wave", polish="SpDefense:3", stats=("Support", 530), bond=30,
         lure="ITM_LURE_AURORAGLASS", sig="Himmelschor: Crescendo – volle Heilung der Reihe, Harmonie +20",
         mark="Ein Himmelsvorhang, der beim Gleiten hörbar singt",
         lore=["Die Endform des Polarlicht-Echos singt, während es leuchtet.",
               "Erscheint in den klarsten Nächten über dem höchsten Gipfel; sein Lied hört man im ganzen Tal.",
               "Wer das Lied einer Lysthane hört, vergisst für eine Nacht jeden Kummer.",
               "Die Akademie hält das Lysthane-Lied für die reinste bekannte Weltlied-Harmonie.",
               "Trägt Reiter durch die Luft. Entsteht aus Lysmara ab Level 38."])],
)

# L075 Steinwarte (Stein, 2)
c.line_of("Two", "Cairnomorphus", [
    dict(name="Vardlit", epithet="lapillus", cat="Steinmännchen-Echo", arch="A13", size="S", h=0.6, types=("Stone",),
         habitat="Wegmarken am Pass", zones=Z(3, 4), rarity="Common", act="Diurnal",
         traits=["Guardian", "Sleepy", "Collector"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 345), evo="Level>=28", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Wegzeichen: Verbündete können 1 Zug nicht verschoben werden",
         mark="Gestapelte Steine, die beim Bewegen leise knirschen",
         lore=["Ein Stein-Oberton aus den Wegmarken der Wanderer.",
               "Steht reglos an Pfaden und richtet sich nach Schneestürmen wieder auf.",
               "Wer an einem Vardlit vorbeigeht, legt einen Stein dazu – für eine sichere Reise.",
               "Die Postreiter Hvitmarks orientieren sich an Vardlits, wenn der Schnee die Wege verschluckt.",
               "Ab Level 28 wächst er zur Steinwarte."]),
    dict(name="Vardholm", epithet="custos", cat="Steinwarten-Echo", arch="A13", size="L", h=2.6, types=("Stone", "Frost"),
         habitat="Pässe und Gletscherränder", zones=Z(3, 4), rarity="Uncommon", act="Diurnal",
         traits=["Guardian", "Sleepy", "Territorial"], niches=["Combat", "Field"], role="Tank", growth="Late",
         polish="Defense:2", stats=("Tank", 500), bond=40, lure="ITM_FOOD_ORECRUMBS",
         sig="Lawinenschild: schützt die Hinterreihe vor dem nächsten Flächenangriff",
         mark="Ein Turm aus Steinen mit einem Eiskern, der nachts blau glimmt",
         lore=["Die ausgewachsene Steinwarte ist ein lebender Wegturm.",
               "Hält Lawinen von Pfaden ab, indem sie sich quer zum Hang stellt.",
               "Die Hvitfeller glauben, jede Vardholm sei einem Wanderer geweiht, der nicht heimkam.",
               "Der Bund schützt alle Vardholms am Schweigfels-Pass als Wegwächter.",
               "Entwickelt sich nicht weiter."])],
)

# L076 Ahnengeist (Geist, 2)
c.line_of("Two", "Maiorumbra", [
    dict(name="Eidrun", epithet="memor", cat="Ahnenhauch-Echo", arch="A12", size="S", h=0.7, types=("Spirit",),
         habitat="Eiðvik-Ruinen", zones=Z(2), rarity="Uncommon", conds=["TimeOfDay.Night"], act="Nocturnal",
         traits=["Drifter", "Singer", "Shy"], niches=["Combat", "Research"], role="Caster", growth="Wave",
         polish="SpAttack:1", stats=("Caster", 345), evo="Level>=30 & Moon=FullMoon", bond=45, lure="ITM_LURE_BELLCHIME",
         sig="Ahnenflüstern: Geist-Angriff, erhöht nächsten Verbündetenangriff",
         mark="Ein Atemhauch in Menschengestalt, der leise summt",
         lore=["Ein Geist-Oberton aus den Liedern, die einst in Eiðvik gesungen wurden.",
               "Schwebt nachts durch die Ruinen und summt Melodien, die niemand mehr kennt.",
               "Wer ein Eidrun-Lied nachsingt, lernt ein Wort der alten Sprache, sagen die Archivare.",
               "Die Archivare Hvitmarks schreiben Eidrun-Melodien seit Generationen auf.",
               "Wild nur nachts. Ab Level 30 bei Vollmond wächst es."]),
    dict(name="Eidwacht", epithet="cantor", cat="Ahnenchor-Echo", arch="A12", size="M", h=1.55, types=("Spirit", "Sound"),
         habitat="Großhalle von Eiðvik bei Vollmond", zones=Z(2), rarity="Rare", conds=["Moon.FullMoon"],
         act="Nocturnal", traits=["Singer", "Guardian", "Glowing"], niches=["Combat", "Research"], role="Caster",
         growth="Wave", polish="SpAttack:2", stats=("Caster", 500), bond=30, lure="ITM_LURE_BELLCHIME",
         sig="Totenchor: Klang-Angriff, stärker je mehr Verbündete besiegt wurden",
         mark="Mehrere Stimmen gleichzeitig, als sänge ein ganzer Chor",
         lore=["Ein Ahnenhauch, der bei Vollmond wuchs, singt mit den Stimmen vieler.",
               "Versammelt sich in der Großhalle und singt bis zum Morgengrauen.",
               "Die Hvitfeller glauben, die Eidwacht hüte das Gedächtnis des Nordens.",
               "Der Orden der Stille und die Akademie streiten, ob Eidwachten Lebende oder Echos sind.",
               "Wild nur bei Vollmond. Entwickelt sich nicht weiter."])],
)

# L077 Hallbock (Klang, 2) – Kletterreittier
c.line_of("Two", "Echocapra", [
    dict(name="Hallkid", epithet="saltans", cat="Halltier-Echo", arch="A18", size="S", h=0.7, types=("Sound",),
         habitat="Felsbänder über dem Fjallstad-Tal", zones=Z(1, 3), rarity="Common", act="Diurnal",
         traits=["Climber", "Playful", "Echolocator"], niches=["Combat"], role="Speed", growth="Steady",
         polish="Speed:1", stats=("Speed", 345), evo="Level>=30", bond=55, lure="ITM_FOOD_ALPINECHEESE",
         sig="Echoruf: Klang-Angriff, der im Gebirge doppelt widerhallt (zweiter Treffer 50 %)",
         mark="Hohle Hörnchen, durch die jeder Ruf als Echo zurückkommt",
         lore=["Ein Klang-Oberton der Felswände, der mit dem Echo spielt.",
               "Springt von Fels zu Fels und ruft, um seine Herde im Nebel zu finden.",
               "Hirten jodeln mit Hallkids um die Wette – die Hallkids gewinnen immer.",
               "Die Kinder Hvitmarks lernen das Klettern, indem sie Hallkids folgen.",
               "Ab Level 30 wächst es zum Hallbock."]),
    dict(name="Hallbrand", epithet="cornutus", cat="Hallbock-Echo", arch="A18", size="L", h=1.8, types=("Sound", "Stone"),
         habitat="Steilwände am Isvaldtind", zones=Z(3, 5), rarity="Uncommon", act="Diurnal",
         traits=["Climber", "Territorial", "Echolocator"], niches=["Combat", "Mount"], role="Speed", mount="Climb",
         growth="Steady", polish="Speed:2", stats=("Speed", 495), bond=40, lure="ITM_FOOD_ALPINECHEESE",
         sig="Bergdonner: Klang-Stoß, der Gegner eine Reihe zurückstößt",
         mark="Gewaltige Spiralhörner, die wie Hörner eines Orchesters klingen",
         lore=["Der ausgewachsene Bock klettert an Wänden, wo kein Pfad mehr ist.",
               "Kämpft mit Rivalen, indem er Hörner zusammenschlägt – der Klang hallt kilometerweit.",
               "Ein Hallbrand-Ruf vor dem Sturm warnt das ganze Tal.",
               "Bergführer in Hvitfell reiten Hallbrands auf die Gipfel, die sonst nur Vögel erreichen.",
               "Trägt Reiter an Steilwänden. Entwickelt sich nicht weiter."])],
)

# L078 Schneeflockenschwarm (Kristall → Sturm, 2)
c.line_of("Two", "Crystallonix", [
    dict(name="Glazil", epithet="minuta", cat="Schneeflocken-Echo", arch="A16", size="XS", h=0.2, types=("Crystal",),
         habitat="Gletscherzunge bei Schneefall", zones=Z(4, 5), rarity="Common", conds=["Weather.Snow"], act="Diurnal",
         traits=["Swarm", "Drifter", "Glowing"], niches=["Combat", "Research"], role="Control", growth="Swift",
         polish="SpDefense:1", stats=("Control", 345), evo="Level>=28 & Weather=Snow", bond=50, lure="ITM_LURE_WINDCHIME",
         sig="Flockenwirbel: Kristall-Angriff, senkt Ausweichen",
         mark="Hunderte Flocken, jede mit demselben sechszackigen Klangmal",
         lore=["Ein Oberton aus Schneeflocken, die zusammen ein Lied ergeben.",
               "Treibt im Schneefall; jede Flocke ist ein Teil desselben Wesens.",
               "Keine zwei Flocken sind gleich – außer bei Glazil, sagen die Kinder.",
               "Die Akademie erforscht, wie ein Schwarm aus Kristallen ein gemeinsames Bewusstsein trägt.",
               "Wild nur bei Schneefall. Ab Level 28 im Schnee wächst er zum Blizzard."]),
    dict(name="Glazvind", epithet="procellosa", cat="Blizzard-Echo", arch="A16", size="M", h=1.5, w=40, types=("Storm", "Crystal"),
         habitat="Isvaldtind bei Schneesturm", zones=Z(5), rarity="Rare", conds=["Weather.Snow"], act="Diurnal",
         traits=["Swarm", "Drifter", "Aggressive"], niches=["Combat"], role="Control", growth="Swift",
         polish="SpDefense:2", stats=("Control", 495), bond=35, lure="ITM_LURE_WINDCHIME",
         sig="Weißer Sturm: ruft Schneefall herbei; Gegner verlieren jede Runde HP",
         mark="Eine heulende Wolke aus Eiskristallen mit einem ruhigen Auge",
         lore=["Ein Flockenschwarm, der im Schnee wuchs, wird zum Blizzard.",
               "Fegt über den Gipfel; in seinem Zentrum ist es völlig windstill.",
               "Die Hvitfeller sagen: Wer ins Auge des Glazvind gelangt, hört das Weltlied klar.",
               "Bergretter tragen Glocken, damit Glazvind sie nicht für Beute halten.",
               "Wild nur bei Schneefall. Entwickelt sich nicht weiter."])],
)

# Einzelart
c.line_of("Single", "Silentiserpens", [
    dict(name="Tysvorn", epithet="taciturnus", cat="Schweigewurm-Echo", arch="A07", size="XL", h=3.5, w=1600,
         types=("Void", "Frost"), habitat="Spalten der Gletscherzunge", zones=Z(4), rarity="VeryRare",
         conds=["Weather.Snow", "TimeOfDay.Night"], act="Nocturnal", traits=["Burrower", "Solitary", "Ambusher"],
         niches=["Combat", "Research"], role="Striker", growth="Late", polish="Attack:2", stats=("Striker", 500),
         bond=20, lure="ITM_FOOD_ICEFISH",
         sig="Gletscherschlund: Leere-Angriff, der Schilde und Barrieren ignoriert",
         mark="Ein Körper aus blauem Eis, in dem ein schwarzer Strang ohne Ton liegt",
         lore=["Ein Leere-Oberton, der seit der Großen Stille im Gletscher schläft.",
               "Gleitet durch Gletscherspalten; wo er sich bewegt, verstummen die Eisgesänge.",
               "Die Alten sagen, der Tysvorn habe die Stille gefressen, damit sie nicht zurückkehrt.",
               "Der Orden der Stille hütet die Spalte, in der der Tysvorn gesehen wurde.",
               "Wild nur nachts bei Schneefall. Entwickelt sich nicht."])],
)

c.write()
