#!/usr/bin/env python3
"""K23/K24 – Kreaturenkatalog: Sahrun-Weite (R04), Kodex #111–#134."""
from catalog_lib import Catalog

c = Catalog(start_kodex=111, start_line=50, region="R04")
Z = lambda *n: [f"R04_Z{i:02d}" for i in n]

# L050 Sonnenfuchs (Licht, 3)
c.line_of("Three", "Heliovulpes", [
    dict(name="Solkit", epithet="minimus", cat="Sonnenfuchs-Echo", arch="A01", size="XS", h=0.28, types=("Light",),
         habitat="Dünenkämme und Oasenränder", zones=Z(1, 2), rarity="Common", act="Crepuscular",
         traits=["Curious", "Playful", "Sunbather"], niches=["Combat", "Field"], role="Striker", growth="Swift",
         polish="Attack:1", stats=("Striker", 300), evo="Level>=18", bond=60, lure="ITM_FOOD_DATES",
         sig="Glanzbiss: Licht-Angriff, der in der Mittagssonne kritisch trifft",
         mark="Übergroße Ohren mit goldenem Saum, die bei Freude summen",
         lore=["Ein kleiner Oberton des Morgenlichts, der in der Weite die ersten Sonnenstrahlen begrüßt.",
               "Gräbt kühle Mulden in Dünen, jagt Käfer im Dämmerlicht und sonnt sich mit gespreizten Ohren.",
               "Karawanenkinder glauben, ein Solkit, der dir folgt, führt dich zum nächsten Brunnen.",
               "In Qasr Sahrun füttern Händler Solkits mit Datteln, damit sie Skorpione von den Ständen fernhalten.",
               "Ab Level 18 und Level 36 wächst er zum Sonnenjäger heran."]),
    dict(name="Solvar", epithet="rutilans", cat="Glutfuchs-Echo", arch="A01", size="S", h=0.7, types=("Light",),
         habitat="Sonnenhof-Plateau und Dünen", zones=Z(2, 4), rarity="Uncommon", act="Diurnal",
         traits=["Hunter", "Sunbather", "Territorial"], niches=["Combat", "Field"], role="Striker", growth="Swift",
         polish="Attack:2", stats=("Striker", 430), evo="Level>=36", bond=45, lure="ITM_FOOD_DATES",
         sig="Spiegelsprung: springt durch einen Lichtreflex hinter das Ziel (Positionswechsel)",
         mark="Schweif mit Lichtsträhnen, die im Lauf flirren wie Hitze",
         lore=["Der heranwachsende Sonnenfuchs speichert Mittagslicht in seinem Fell.",
               "Jagt in der größten Hitze, wenn andere Räuber schlafen; leuchtet nachts schwach nach.",
               "Ein Solvar, der dich ansieht, prüft, ob du die Weite überleben würdest, sagen die Nomaden.",
               "Schirah Harrâds Lehrlinge beginnen ihre Ausbildung mit einem Solvar-Gefährten.",
               "Ab Level 36 erreicht er die Endform."]),
    dict(name="Solaryx", epithet="regina", cat="Sonnenkronen-Echo", arch="A01", size="M", h=1.3, types=("Light", "Ember"),
         habitat="Sonnenhof-Plateau zur Mittagszeit", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Hunter", "Sunbather", "Solitary"], niches=["Combat"], role="Striker", growth="Swift",
         polish="Attack:3", stats=("Striker", 530), bond=30, lure="ITM_FOOD_DATES",
         sig="Zenitstrahl: Crescendo – mächtiger Licht-Angriff, bei Sonnenwetter ohne Abklingzeit",
         mark="Eine Mähne aus Strahlen, die zur Mittagszeit eine Krone bildet",
         lore=["Die Endform der Sonnenfüchse trägt eine Strahlenkrone – ein Splitter des Mittagslichts selbst.",
               "Beherrscht ein Revier um eine Oase; duldet nur andere Solaryx während der Paarungszeit.",
               "Alte Lieder nennen den Solaryx den Wächter, der die Sonne jeden Morgen über den Rand zieht.",
               "Das Wappen Qasr Sahruns zeigt einen Solaryx; ihn zu verletzen gilt dort als Frevel.",
               "Entsteht aus Solvar ab Level 36."])],
)

# L051 Dünenkamel (Stein, 3) – Bodenreittier
c.line_of("Three", "Psammocamelus", [
    dict(name="Dunkalb", epithet="tenellus", cat="Dünenkalb-Echo", arch="A03", size="M", h=1.1, types=("Stone",),
         habitat="Karawanenwege und Oasen", zones=Z(1, 2), rarity="Common", act="Diurnal",
         traits=["Herd", "Grazer", "Shy"], niches=["Combat", "Mount"], role="Tank", growth="Steady",
         polish="HP:1", stats=("Tank", 315), evo="Level>=20", bond=60, lure="ITM_FOOD_DATES",
         sig="Sandpanzer: erhöht eigene VER, bei Sandsturm doppelt",
         mark="Steinerne Höckerplatten, die beim Atmen leise knacken",
         lore=["Ein geduldiger Oberton der Weite, aus Sandstein und Ausdauer geboren.",
               "Zieht in Herden von Oase zu Oase und speichert Wasser in steinernen Höckern.",
               "Wer einem Dunkalb sein Wasser teilt, dem zeigt die Herde den Weg, sagt man in Harrâd.",
               "Fast jede Karawane des Goldklang-Kontors führt Dunkalbs als Lastenträger mit.",
               "Ab Level 20 trägt es Reiter; ab Level 38 auf dem Plateau wird es zum Wüstenkoloss."]),
    dict(name="Dunhorn", epithet="vector", cat="Karawanen-Echo", arch="A03", size="L", h=2.2, types=("Stone",),
         habitat="Karawanenwege durch die Dünen", zones=Z(2, 5), rarity="Uncommon", act="Diurnal",
         traits=["Herd", "Grazer", "Migratory"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Steady", polish="HP:2", stats=("Tank", 440), evo="Level>=38 & Zone=R04_Z04", bond=45,
         lure="ITM_FOOD_DATES", sig="Karawanenschritt: Formation – Verbündete hinter ihm erhalten Schutz",
         mark="Hörner wie gewundene Sandsteinsäulen, in denen der Wind singt",
         lore=["Das ausgewachsene Dünenkamel trägt Hörner, in denen der Wüstenwind Melodien formt.",
               "Findet Wasser tief unter dem Sand und kniet nieder, wo es gräbt.",
               "Nomaden sagen, ein Dunhorn vergesse nie eine Oase – und nie einen Treiber, der es schlug.",
               "Das Standardreittier der Weite; Kontor-Karawanen mieten sie in Qasr Sahrun.",
               "Trägt Reiter. Entwickelt sich ab Level 38 auf dem Sonnenhof-Plateau."]),
    dict(name="Dunmarsch", epithet="colossus", cat="Wüstenkoloss-Echo", arch="A03", size="XL", h=3.6,
         types=("Stone", "Gravity"), habitat="Tiefe Weite", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Diurnal", traits=["Herd", "Guardian", "Migratory"], niches=["Combat", "Mount"], role="Tank",
         mount="Ground", growth="Steady", polish="HP:3", stats=("Tank", 530), bond=30, lure="ITM_FOOD_DATES",
         sig="Erdlast: Crescendo – erhöht Schwerkraft auf dem Feld, alle Gegner werden langsamer",
         mark="Rücken trägt einen Felsgrat, um den Sandkörner schweben",
         lore=["Die Endform der Dünenkamele ist so schwer, dass der Sand um sie leicht wird.",
               "Führt die großen Herden durch die Tiefe Weite; Sandstürme teilen sich vor ihr.",
               "Die Nomaden erzählen, die ersten Dunmarsch hätten die Dünen der Weite aufgeschichtet.",
               "Ein Dunmarsch kann ein ganzes Zelthaus tragen; Karawanenführer kaufen sie für Vermögen.",
               "Trägt Reiter. Entsteht aus Dunhorn ab Level 38 auf dem Sonnenhof-Plateau."])],
)

# L052 Skarabäus (Schwerkraft, 3)
c.line_of("Three", "Gravicarabus", [
    dict(name="Skarit", epithet="volvens", cat="Kugelkäfer-Echo", arch="A10", size="XS", h=0.15, types=("Gravity",),
         habitat="Sandflächen und Dungkugeln", zones=Z(2, 3), rarity="Common", act="Diurnal",
         traits=["Collector", "Burrower", "Hoarder"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="Defense:1", stats=("Control", 305), evo="Level>=18", bond=55, lure="ITM_FOOD_ORECRUMBS",
         sig="Kugelstoß: rollt eine Sandkugel, verschiebt das Ziel eine Reihe nach hinten",
         mark="Panzer mit konzentrischen Ringen, die bei Bewegung leise schnurren",
         lore=["Ein Oberton der Schwere, der gelernt hat, die Welt in Kugeln zu formen.",
               "Rollt Kugeln aus Sand und Erz, in denen es Vorräte vergräbt; orientiert sich an der Sonne.",
               "Kinder in Harrâd verfolgen Skarit-Kugeln, weil sie manchmal kleine Erzkörner enthalten.",
               "Schmiede in Qasr Sahrun kaufen Skarit-Kugeln für ihr seltenes Eisenpulver.",
               "Ab Level 18 und Level 34 wächst er zum Sonnenträger."]),
    dict(name="Skaral", epithet="portator", cat="Lastkäfer-Echo", arch="A10", size="S", h=0.5, types=("Gravity", "Stone"),
         habitat="Glasebene und Dünentäler", zones=Z(3, 5), rarity="Uncommon", act="Diurnal",
         traits=["Collector", "Burrower", "Territorial"], niches=["Combat", "Field"], role="Control", growth="Steady",
         polish="Defense:2", stats=("Control", 430), evo="Level>=34", bond=45, lure="ITM_FOOD_ORECRUMBS",
         sig="Schwerkugel: Schwerkraft-Angriff, Ziel kann 1 Zug nicht die Reihe wechseln",
         mark="Hornschild, um das winzige Steinchen kreisen",
         lore=["Der heranwachsende Käfer rollt Kugeln, die schwerer sind als er selbst – mithilfe der Schwerkraft.",
               "Verteidigt seine Kugel mit erstaunlicher Wut und hebt Gegner kurz vom Boden.",
               "Ein Skaral auf deinem Weg bedeutet: Hier liegt etwas vergraben.",
               "Archäologen der Akademie folgen Skarals, um verschüttete Ruinen zu finden.",
               "Ab Level 34 erreicht er die Endform."]),
    dict(name="Skarabon", epithet="solifer", cat="Sonnenträger-Echo", arch="A10", size="M", h=1.2, types=("Gravity", "Light"),
         habitat="Über der Glasebene im Morgenlicht", zones=[], rarity="Rare", conds=["Spawn.None"], act="Diurnal",
         traits=["Guardian", "Collector", "Stargazer"], niches=["Combat", "Research"], role="Control", growth="Steady",
         polish="SpDefense:3", stats=("Control", 525), bond=30, lure="ITM_FOOD_ORECRUMBS",
         sig="Sonnenkugel: Crescendo – erzeugt eine schwebende Lichtkugel, die 3 Züge lang Gegner trifft",
         mark="Zwischen den Vorderbeinen schwebt eine leuchtende Kugel",
         lore=["Die Endform der Skarabäen trägt eine Kugel aus Licht statt aus Sand.",
               "Hebt die Kugel jeden Morgen über den Horizont; schläft nachts in der Glasebene.",
               "Die Nomaden glauben, Skarabons rollen die Sonne über den Himmel, damit sie nie stehen bleibt.",
               "Eine verwitterte Skarabon-Reliefplatte schmückt das Tor von Qasr Sahrun.",
               "Entsteht aus Skaral ab Level 34."])],
)

# L053 Sandwurm (Glut, 3) – Grabreittier
c.line_of("Three", "Ignivermis", [
    dict(name="Sengel", epithet="tenuis", cat="Glutwurm-Echo", arch="A07", size="S", h=0.5, w=6, types=("Ember",),
         habitat="Heißer Sand der Mirsaan-Dünen", zones=Z(2, 5), rarity="Common", act="Diurnal",
         traits=["Burrower", "Thermal", "Ambusher"], niches=["Combat"], role="Striker", growth="Late",
         polish="Attack:1", stats=("Striker", 310), evo="Level>=22", bond=55, lure="ITM_FOOD_CHARCOAL",
         sig="Glutstich: schießt aus dem Sand, trifft zuerst (Priorität +1)",
         mark="Glühende Ringe, die unter dem Sand sichtbar bleiben",
         lore=["Ein Glut-Oberton, der in der Hitze des Sandes schwimmt wie ein Fisch im Wasser.",
               "Gräbt dicht unter der Oberfläche und schnappt nach allem, was Schatten wirft.",
               "Wer barfuß über heißen Sand geht, weckt die Sengel, warnen die Mütter in Harrâd.",
               "Glasbläser in Qasr Sahrun halten Sengel, um ihre Öfen mit Wüstenglut zu nähren.",
               "Ab Level 22 und Level 40 wächst er zum Sandleviathan."]),
    dict(name="Sengar", epithet="fodiens", cat="Dünenwurm-Echo", arch="A07", size="L", h=2.8, w=700, types=("Ember", "Stone"),
         habitat="Tiefe Dünen", zones=Z(5), rarity="Uncommon", act="Diurnal",
         traits=["Burrower", "Thermal", "Hunter"], niches=["Combat", "Mount"], role="Striker", mount="Dig",
         growth="Late", polish="Attack:2", stats=("Striker", 445), evo="Level>=40", bond=40,
         lure="ITM_FOOD_CHARCOAL", sig="Dünenbruch: Erdbeben-Angriff, trifft beide gegnerischen Reihen",
         mark="Hitzewellen steigen dort auf, wo er unter dem Sand zieht",
         lore=["Der heranwachsende Wurm zieht glühende Tunnel durch die Dünen.",
               "Spürt Schritte auf hundert Schritt Entfernung; verschmilzt Sand zu Glasröhren.",
               "Karawanen stampfen nachts nicht – damit die Sengar schlafen.",
               "Mutige Reiter der Weite lassen sich von Sengar durch Dünen tragen, um Sandstürmen zu entgehen.",
               "Trägt Reiter unter dem Sand. Ab Level 40 erreicht er die Endform."]),
    dict(name="Sengrath", epithet="leviathan", cat="Sandleviathan-Echo", arch="A07", size="XXL", h=9.0, w=22000,
         types=("Ember", "Stone"), habitat="Tiefe Weite", zones=[], rarity="Rare", conds=["Spawn.None"],
         act="Diurnal", traits=["Burrower", "Thermal", "Solitary"], niches=["Combat", "Mount"], role="Striker",
         mount="Dig", growth="Late", polish="Attack:3", stats=("Striker", 545), bond=25, lure="ITM_FOOD_CHARCOAL",
         sig="Glutschlund: Crescendo – verschlingt das Feld, Terrain wird Glutsand (3 Züge)",
         mark="Ein Maul aus glühenden Ringen, das beim Auftauchen tief brummt",
         lore=["Die Endform der Glutwürmer ist ein Leviathan, der die Tiefe Weite durchpflügt.",
               "Taucht nur auf, wenn die Erde vor Hitze bebt; hinterlässt Spuren aus geschmolzenem Glas.",
               "Die Glasebene, sagen die Nomaden, sei die Spur eines einzigen Sengrath vor tausend Jahren.",
               "Den Sengrath zu reiten gilt in Qasr Sahrun als größte Prüfung eines Wärters.",
               "Trägt Reiter unter dem Sand. Entsteht aus Sengar ab Level 40."])],
)

# L054 Skorpion (Gift, 2)
c.line_of("Two", "Aculeoscorpio", [
    dict(name="Stachik", epithet="parvus", cat="Stachelskorpion-Echo", arch="A10", size="XS", h=0.2, types=("Venom",),
         habitat="Unter Steinen der Glasebene", zones=Z(3, 4), rarity="Common", act="Nocturnal",
         traits=["Ambusher", "Aggressive", "Camouflaged"], niches=["Combat"], role="Striker", growth="Steady",
         polish="Attack:1", stats=("Striker", 340), evo="Level>=26", bond=50, lure="ITM_FOOD_ORECRUMBS",
         sig="Doppelstich: zwei Treffer, der zweite vergiftet",
         mark="Stachel leuchtet im Dunkeln grünlich",
         lore=["Ein scharfer Oberton der Nacht, klein und gefährlich.",
               "Wartet unter warmen Steinen auf Beute; tanzt vor der Paarung im Mondlicht.",
               "Schüttle deine Stiefel aus, bevor du sie anziehst – Stachiks lieben dunkle Orte.",
               "Heiler in Harrâd melken Stachik-Gift für Schmerzsalben.",
               "Ab Level 26 bei Nacht wächst er zum Wüstenskorpion."]),
    dict(name="Stacharon", epithet="imperator", cat="Wüstenskorpion-Echo", arch="A10", size="M", h=1.4,
         types=("Venom", "Stone"), habitat="Felsen der Glasebene", zones=Z(3, 5), rarity="Rare",
         conds=["TimeOfDay.Night"], act="Nocturnal", traits=["Ambusher", "Territorial", "Hunter"],
         niches=["Combat"], role="Striker", growth="Steady", polish="Attack:2", stats=("Striker", 500), bond=35,
         lure="ITM_FOOD_ORECRUMBS", sig="Giftzange: hält das Ziel fest; Gift stapelt sich jede Runde",
         mark="Steinplatten mit grünen Leuchtadern, Stachel wie ein Glaskolben",
         lore=["Der ausgewachsene Skorpion trägt eine Rüstung aus Wüstenstein.",
               "Jagt nachts; seine Leuchtadern verraten ihn nur, wenn er angreifen will.",
               "Die Nomaden schnitzen Stacharon-Abbilder an Zeltpfosten – als Wächter gegen Diebe.",
               "Shirah Harrâds Arenakader führt einen Stacharon mit dem Beinamen ‚die Wache‘.",
               "Wild nur nachts. Entwickelt sich nicht weiter."])],
)

# L055 Sandschwarm (Sturm, 2)
c.line_of("Two", "Psammonubes", [
    dict(name="Sirrkorn", epithet="volitans", cat="Sandkorn-Schwarm-Echo", arch="A16", size="XS", h=0.28, types=("Storm",),
         habitat="Über den Dünen bei Wind", zones=Z(2, 5), rarity="Common", act="Diurnal",
         traits=["Swarm", "Drifter", "Migratory"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:1", stats=("Speed", 345), evo="Level>=26 & Weather=Sandstorm", bond=55, lure="ITM_LURE_WINDCHIME",
         sig="Schmirgelwind: Sturm-Angriff, senkt Präzision",
         mark="Hunderte Körnchen, die zusammen einen hohen Ton sirren",
         lore=["Ein Oberton aus tausend singenden Sandkörnern.",
               "Wirbelt im Wind über den Dünen; formt Muster, die nach Gesichtern aussehen.",
               "Wenn die Dünen singen, sind es die Sirrkorn – und dann kommt Sturm.",
               "Karawanen binden Tücher vor die Gesichter ihrer Reittiere, wenn Sirrkorn ziehen.",
               "Ab Level 26 wächst der Schwarm im Sandsturm."]),
    dict(name="Sirrsturm", epithet="turbo", cat="Sandteufel-Echo", arch="A16", size="M", h=1.5, w=90, types=("Storm", "Stone"),
         habitat="Tiefe Weite bei Sandsturm", zones=Z(5), rarity="Rare", conds=["Weather.Sandstorm"],
         act="Diurnal", traits=["Swarm", "Drifter", "Aggressive"], niches=["Combat"], role="Speed", growth="Swift",
         polish="Speed:2", stats=("Speed", 495), bond=35, lure="ITM_LURE_WINDCHIME",
         sig="Sandteufel: ruft Sandsturm herbei; im Sturm Ausweichen +2",
         mark="Eine wirbelnde Säule mit zwei glühenden Augenkörnern",
         lore=["Ein Schwarm, der im Sandsturm wuchs, wird zu einer lebenden Windhose.",
               "Zieht mit Sandstürmen über die Weite und verschwindet, wenn der Wind abflaut.",
               "Die Nomaden werfen Salz in einen Sirrsturm, um ihn zu besänftigen.",
               "Die Akademie misst mit eingefangenen Sirrsturm die Windstärke von Stürmen.",
               "Wild nur im Sandsturm. Entwickelt sich nicht weiter."])],
)

# L056 Trugbild (Arkan, 2)
c.line_of("Two", "Phantasmagus", [
    dict(name="Mirasel", epithet="fallax", cat="Trugbild-Echo", arch="A04", size="S", h=0.75, types=("Arcane",),
         habitat="Flimmernde Hitze über der Glasebene", zones=Z(3), rarity="Uncommon", conds=["TimeOfDay.Noon"],
         act="Diurnal", traits=["Mimic", "Shy", "Playful"], niches=["Combat", "Research"], role="Control",
         growth="Wave", polish="SpAttack:1", stats=("Control", 350), evo="Level>=28 & Weather=Heatwave", bond=45,
         lure="ITM_LURE_MIRROR", sig="Flimmerbild: erschafft ein Spiegelbild, das einen Angriff abfängt",
         mark="Umrisse, die wie Hitze flimmern; ein Ton wie ferne Glöckchen",
         lore=["Ein Arkan-Oberton, gewebt aus Hitze und Erwartung.",
               "Zeigt Durstigen, was sie sehen wollen – Wasser, Schatten, Freunde – und lacht lautlos.",
               "Folge niemals einer Oase, die näher kommt, wenn du stehen bleibst, sagen die Nomaden.",
               "Kontor-Karten verzeichnen ‚Mirasel-Felder‘, in denen Kompasse nicht trauen sind.",
               "Wild nur mittags. Ab Level 28 bei Hitzewelle wächst es."]),
    dict(name="Mirazhar", epithet="magnus", cat="Fata-Morgana-Echo", arch="A04", size="M", h=1.55, types=("Arcane", "Light"),
         habitat="Glasebene bei Hitzewelle", zones=Z(3, 5), rarity="VeryRare", conds=["Weather.Heatwave", "TimeOfDay.Noon"],
         act="Diurnal", traits=["Mimic", "Solitary", "Dancer"], niches=["Combat", "Research"], role="Control",
         growth="Wave", polish="SpAttack:2", stats=("Control", 505), bond=25, lure="ITM_LURE_MIRROR",
         sig="Spiegelstadt: Crescendo-artige Feldkarte – Gegner treffen 2 Züge zufällige Ziele",
         mark="Ein Gewand aus gespiegelten Horizonten, das Türme und Wasser zeigt",
         lore=["Ein Trugbild, das in der Hitze wuchs, zeigt ganze Städte, die es nie gab – oder einst gab.",
               "Tanzt über der Glasebene; Reisende sehen in ihm Türme aus Glas und Brunnen.",
               "Manche glauben, Mirazhar zeigten die Stadt, die unter der Glasebene begraben liegt.",
               "Die Akademie streitet, ob Mirazhar-Bilder Erinnerungen der Weite sind.",
               "Wild nur bei Hitzewelle zur Mittagszeit. Entwickelt sich nicht weiter."])],
)

# L057 Glasmotte (Licht, 2)
c.line_of("Two", "Vitrilepis", [
    dict(name="Vitrel", epithet="pellucida", cat="Glasmotten-Echo", arch="A10", size="XS", h=0.12, types=("Light",),
         habitat="Glasebene nachts, an Lagerfeuern", zones=Z(1, 3), rarity="Common", act="Nocturnal",
         traits=["Glowing", "Pollinator", "Swarm"], niches=["Combat", "Research"], role="Support", growth="Swift",
         polish="SpDefense:1", stats=("Support", 340), evo="Level>=24 & TimeOfDay=Night", bond=60, lure="ITM_LURE_LANTERN",
         sig="Glasstaub: heilt einen Verbündeten und entfernt Blendung",
         mark="Durchsichtige Flügel, die Licht in Regenbogen brechen",
         lore=["Ein Licht-Oberton, so zart wie das Glas, auf dem er ruht.",
               "Bestäubt Nachtblüher an Oasen und sammelt sich um Feuer, ohne zu verbrennen.",
               "Eine Vitrel auf deiner Hand bedeutet, dass jemand an dich denkt.",
               "Glasbläser in Qasr Sahrun nutzen Vitrel-Staub für ihre schimmerndsten Gläser.",
               "Ab Level 24 nachts wächst sie."]),
    dict(name="Vitrapha", epithet="prismatica", cat="Prismamotten-Echo", arch="A10", size="S", h=0.5, w=1.2,
         types=("Light", "Crystal"), habitat="Glasebene im Mondlicht", zones=Z(3), rarity="Rare", conds=["TimeOfDay.Night"],
         act="Nocturnal", traits=["Glowing", "Pollinator", "Dancer"], niches=["Combat", "Research"], role="Support",
         growth="Swift", polish="SpDefense:2", stats=("Support", 485), bond=40, lure="ITM_LURE_LANTERN",
         sig="Prismaflug: verteilt Heilung auf alle Verbündeten; bei Mondlicht doppelt",
         mark="Kristallflügel werfen Lichtmuster auf den Sand",
         lore=["Eine Glasmotte, die in Mondnächten wuchs, trägt Flügel aus echtem Kristall.",
               "Tanzt nachts über der Glasebene; ihr Tanz zeichnet leuchtende Muster in den Sand.",
               "Die Muster der Vitrapha sind Karten zu verborgenen Brunnen, glauben die Nomaden.",
               "Die Akademie kartiert Vitrapha-Muster – bislang ohne Ergebnis.",
               "Wild nur nachts. Entwickelt sich nicht weiter."])],
)

# L058 Tafelschildkröte (Stein, 2) – Bodenreittier
c.line_of("Two", "Mesatestudo", [
    dict(name="Mesakil", epithet="tardus", cat="Tafelschildkröten-Echo", arch="A11", size="S", h=0.5, types=("Stone",),
         habitat="Felsplatten am Sonnenhof-Plateau", zones=Z(4), rarity="Uncommon", act="Diurnal",
         traits=["Sunbather", "Sleepy", "Lithophage"], niches=["Combat", "Breeding"], role="Tank", growth="Late",
         polish="Defense:1", stats=("Tank", 350), evo="Level>=30", bond=50, lure="ITM_FOOD_ORECRUMBS",
         sig="Tafelschild: schützt die eigene Reihe einen Zug vor Bodenangriffen",
         mark="Flacher Panzer mit Schichtlinien wie ein Tafelberg",
         lore=["Ein langsamer Oberton der Felsplateaus, alt schon bei der Geburt.",
               "Sonnt sich auf flachen Felsen, frisst Mineralkrusten und schläft in der Mittagshitze.",
               "Wer einen Mesakil umdreht, dem bleibt das Wasser aus – so die Nomaden.",
               "Kinder auf dem Plateau nutzen schlafende Mesakils als Sitzplätze.",
               "Ab Level 30 wächst er zum Tafelberg."]),
    dict(name="Mesakor", epithet="tabularis", cat="Tafelberg-Echo", arch="A11", size="L", h=2.0, types=("Stone", "Ember"),
         habitat="Sonnenhof-Plateau", zones=Z(4), rarity="Rare", conds=["Weather.Heatwave"], act="Diurnal",
         traits=["Sunbather", "Guardian", "Lithophage"], niches=["Combat", "Mount"], role="Tank", mount="Ground",
         growth="Late", polish="Defense:2", stats=("Tank", 500), bond=35, lure="ITM_FOOD_ORECRUMBS",
         sig="Glutplateau: Rückstoß-Schaden gegen Nahkampfangreifer, bei Hitze erhöht",
         mark="Panzer wie ein kleiner Tafelberg mit glühenden Spalten",
         lore=["Der ausgewachsene Panzerträger gleicht einem wandernden Tafelberg.",
               "Speichert die Tageshitze im Panzer und strahlt sie nachts wieder ab.",
               "Ein schlafender Mesakor wärmt ein ganzes Lager – und sieht aus wie ein Felsen.",
               "Plateau-Hirten reiten Mesakor auf steinigen Wegen, wo Kamele straucheln.",
               "Trägt Reiter. Wild nur bei Hitzewelle. Entwickelt sich nicht weiter."])],
)

# Einzelarten
c.line_of("Single", "Astrolabium", [
    dict(name="Qadrant", epithet="mensor", cat="Sternmess-Echo", arch="A13", size="M", h=1.55, types=("Metal", "Gravity"),
         habitat="Ruinen der alten Sternwarten", zones=Z(4, 5), rarity="Rare", conds=["TimeOfDay.Night"],
         act="Nocturnal", traits=["Stargazer", "Guardian", "Solitary"], niches=["Combat", "Research"], role="Control",
         growth="Late", polish="SpDefense:2", stats=("Control", 490), bond=30, lure="ITM_LURE_STARCHIME",
         sig="Sternvermessung: sagt den nächsten gegnerischen Zug voraus und verlangsamt ihn",
         mark="Kreisende Messingringe mit Sternzeichen, die beim Drehen klicken",
         lore=["Ein Metall-Oberton aus den Instrumenten einer vergessenen Sternwarte.",
               "Steht nachts auf Ruinen und richtet seine Ringe nach den Sternen aus.",
               "Die Nomaden sagen, ein Qadrant zähle die Nächte bis zur nächsten Stille.",
               "Die Akademie betrachtet Qadrants als Beweis für eine Hochkultur in der Weite.",
               "Wild nur nachts. Entwickelt sich nicht."])],
)
c.line_of("Single", "Caravanimus", [
    dict(name="Mahrsil", epithet="errans", cat="Karawanengeist-Echo", arch="A12", size="M", h=1.55, types=("Spirit", "Storm"),
         habitat="Verlassene Karawanenwege", zones=Z(2, 5), rarity="VeryRare",
         conds=["Weather.Sandstorm", "TimeOfDay.Night"], act="Nocturnal", traits=["Drifter", "Singer", "Solitary"],
         niches=["Combat", "Research"], role="Caster", growth="Wave", polish="SpAttack:2", stats=("Caster", 485),
         bond=25, lure="ITM_LURE_BELLCHIME",
         sig="Glockenruf: Geist-Angriff, Verbündete mit niedrigem HP erhalten Schild",
         mark="Ein Schleier aus Sand, in dem leise Kamelglocken läuten",
         lore=["Ein Geist-Oberton, der aus den Liedern verschollener Karawanen entstand.",
               "Wandert im Sandsturm die alten Wege entlang und läutet Glocken, die niemand trägt.",
               "Wer einem Mahrsil folgt, findet sicheren Lagerplatz – oder die Knochen der Verirrten.",
               "In Harrâd hängt man Glocken an die Tore, damit verlorene Karawanen heimfinden.",
               "Wild nur nachts im Sandsturm. Entwickelt sich nicht."])],
)

c.write()
