// Copyright AETHRIS Team.
#pragma once

#include "NativeGameplayTags.h"

/**
 * Native GameplayTags, die der C++-Code direkt benötigt (K04 §8).
 * Inhaltliche Tags (z. B. einzelne Statuszustände) werden in Config/Tags/*.ini gepflegt.
 */
namespace AethrisTags
{
	// Typen (CANON §5.1)
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Ember);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Tide);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Stone);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Storm);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Bloom);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Frost);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Void);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Light);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Venom);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Metal);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Spirit);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Crystal);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Sound);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Gravity);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Type_Arcane);

	// Event-Bus-Kanäle (Auszug, K06 §4)
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_GameFlow_StateChanged);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Started);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Ended);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Echo_Bonded);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Echo_Evolved);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Echo_LevelUp);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_World_WeatherChanged);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_World_TimeOfDayChanged);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_World_Zone_BandFixed);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Quest_StepCompleted);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Save_Requested);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Reputation_Changed);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Reputation_RankUp);

	// Fraktionen (K47, Data/Factions/Factions.csv)
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Academy);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Goldklang);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Wildwatch);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_FreeVoices);
	AETHRISCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Faction_Order);
}
